### ISSUE TITLE
Large content imports failing 

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#20789] opened 2021-08-12 19:37 UTC
I tested a large 13k content import multiple times on dotCMS version 21.06 and the importer moves progressively slower until the server gets stuck with a memory leak and out of heap space error even thought Java Heap space was configured to 20G on a larger EC2 instance.  DB connections were upped to 1000 and shared buffers at 4G, ha proxy timeouts increased for no time-out on preview screen... and was tested on a m5.2xlarge instance. 

https://gist.github.com/DeanGonzalez/310f5afc5652082e7db11e2f62d0485e

However this memory leak is new as the same import of the same file on the same instance DOES work properly on dotCMS 5.3.8.5lts version.

Here is a google drive link with the .csv files and the bundles for both versions to import the content type as a PP bundle so you don't have to manually create anything:

https://drive.google.com/drive/folders/1g8T_lEApJaxcz7Rd_tsKwQTCzNxDKd2Q?usp=sharing

**Comment by wezell** [comment] 2021-08-17 20:35
I believe this is the same as #20799

**Comment by john-thomas-dotcms** [comment] 2021-08-24 18:29
Duplicate of #20799

**Closed by john-thomas-dotcms** 2021-08-24 18:29 UTC
Labels: Type : Bug
