### ISSUE TITLE
Need delete the html pages portlet in the upgrade tasks  

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7598] opened 2015-04-16 18:27 UTC
After make any upgrade from 1.9 to 3.2, we are showing the html pages portlet in the site browser submenu... Since this portlet was removed, we need delete this link from here, because if you clisk you will have a "Ooops, sorry. This has caused a problem " message and an error on log 

Here the log: https://gist.github.com/bryanboza/8401c797e2474b64253c

Tested on nightly build 2015-04-15 // Postgres // FF

**Comment by jtesser** [comment] 2015-04-16 19:05
Users actually have to remove it

**Comment by jtesser** [comment] 2015-04-16 19:06
fix the JSP error so at least the portlet renders

**Comment by maurizo** [comment] 2015-05-08 18:53
The upgrade process from 1.9 to 3.x requires the plugin to change file extensions on 3.x (https://github.com/dotCMS/support/tree/master/hotfixes/com.dotcms.page.extension.config-v-3.0.x-for-dist-version). The issue is somewhere else than the “Html Pages” portlet. The cause is the upgrade task taking old pages (not content pages) with a “dot” extension and identifying them as file assets instead of HTML pages.  So the HTML page identifier exists in the “HTMLPAGE” table but the identifier type on the “IDENTIFIER” table is set to “file_asset”, so the VersionaleFactory (Impl) methods look for the page identifiers on the FILEASSET_VERSION_INFO table and it is never found.  If the plugin is installed the portlet works correctly.

The upgrade task00785 uses the VELOCITY_PAGE_EXTENSION value set on dotmarketing-config.properties (https://github.com/dotCMS/core/blob/master-3.2/src-conf/dotmarketing-config.properties#L105) like this  https://github.com/dotCMS/core/blob/master-3.2/src/com/dotmarketing/startup/runonce/Task00785DataModelChanges.java#L1501-L1508

So the pages ending with “dot” will never be treated as “htmlpage” unless the VELOCITY_PAGE_EXTENSION is changed before the upgrade, so the next “if” is evaluated and the identifier type is set to “file_asset”.  The use of “dot” extension in old dotCMS versions carries some other implications addressed by the plugin but to fix the current issue just replacing the VELOCITY_PAGE_EXTENSION to “dot” is enough.

**Closed by maurizo** 2015-05-08 18:53 UTC
Labels: Type : bug

**Comment by oarrietadotcms** [comment] 2015-05-11 13:18
@bryanboza could you test with Rizo's solution and let us know?

**Comment by bryanboza** [comment] 2015-05-15 16:11
Fixed, now we have the same portlet and is showing all the content pages, and legacy pages... Tested on Nightly build 2015-05-15 // Postgres // FF
