### ISSUE TITLE
Symlink felix folder issue

### ISSUE THREAD

**Issue by danlaguna** [dotCMS/core#11469] opened 2017-05-02 22:23 UTC
When having the WEB-INF/felix folder as a symlink, the OSGI process fails to deploy any plugin.

## Expected Behavior
When uploading a new plugin, the OSGI should deploy it correctly.

## Current Behavior
OSGI does nothing (no deploy of uploaded jar).

## Possible Solution
Review the way the symlink path is being generated.

## Known Workarounds
None.

## Steps to Reproduce (for bugs)
1. Have a clean install
2. Create an external folder on any path (/usr/local/felix)
3. Modify the felix.base.dir = /usr/local/felix 
4. Start dotCMS on a clean install
5. After startup stop tomcat
6. Go to <TOMCAT_ROOT>/webapps/ROOT/WEB-INF and create a symlink to /usr/local/felix (ln -s /usr/local/felix <TOMCAT_ROOT>/webapps/ROOT/WEB-INF/felix)
6. Start tomcat and upload a jar

## Your Environment
* dotCMS version used: master 4.1
* Browser Name and version: any
* Operating System and version: MacOS (any)
* Application Server and version: any
* Java Brand and version: any
* Database and version: any

**Comment by wezell** [comment] 2017-05-11 19:40
Dupe of #10370

**Closed by wezell** 2017-05-11 19:40 UTC
Labels: Cat : OSGi, Release : 4.1.0
