### ISSUE TITLE
Page statistics broken for htmlpage as content

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#6986] opened 2015-01-15 17:04 UTC
```
2015-01-15 12:01:40,827 ERROR com.dotmarketing.velocity.VelocityServlet - #--------------------------------------------------------------------------------------
2015-01-15 12:03:01,765 ERROR com.liferay.portal.servlet.MainServlet - Versionable is null
com.dotmarketing.business.DotStateException: Versionable is null
	at com.dotmarketing.business.IdentifierAPIImpl.find(IdentifierAPIImpl.java:86)
	at com.dotmarketing.portlets.htmlpageviews.action.ViewHTMLPageViewsAction._viewWebAssets(ViewHTMLPageViewsAction.java:109)
	at com.dotmarketing.portlets.htmlpageviews.action.ViewHTMLPageViewsAction.render(ViewHTMLPageViewsAction.java:88)
	at com.liferay.portal.struts.PortletAction.execute(PortletAction.java:66)
	at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:421)
	at com.liferay.portal.struts.PortletRequestProcessor.processActionPerform(PortletRequestProcessor.java:192)
	at com.dotcms.repackage.org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:226)
	at com.liferay.portal.struts.PortletRequestProcessor.process(PortletRequestProcessor.java:91)
	at com.liferay.portlet.StrutsPortlet.include(StrutsPortlet.java:148)
	at com.liferay.portlet.StrutsPortlet.doView(StrutsPortlet.java:100)
	at com.dotcms.repackage.javax.portlet.GenericPortlet.doDispatch(GenericPortlet.java:235)
	at com.dotcms.repackage.javax.portlet.GenericPortlet.render(GenericPortlet.java:163)
	at com.liferay.portlet.CachePortlet.render(CachePortlet.java:159)
	at org.apache.jsp.html.portal.layout_jsp._jspService(layout_jsp.java:437)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
```

**Comment by jtesser** [comment] 2015-01-16 19:03
@maurizo see this also. I think it is a duplicate of this one https://github.com/dotCMS/core/issues/6998

**Comment by maurizo** [comment] 2015-01-20 20:51
Pull request: #7024

**Closed by maurizo** 2015-01-20 20:51 UTC
Labels: Type : bug

**Comment by bryanboza** [comment] 2015-01-21 14:57
Fixed, Tested on nightly build 2015-01-20 // H2 // FF

**Comment by shayngr** [comment] 2015-02-02 14:51
Added to test rail:
http://qa.dotcms.com/index.php?/cases/view/52894
http://qa.dotcms.com/index.php?/cases/view/52873
