### ISSUE TITLE
#dotParse does not work across hosts in custom fields

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#18573] opened 2020-06-01 23:10 UTC
If you try to use dotParse with host notation in a custom field, and try to use it on a different host,  dotCMS cannot resolve the asset correctly.

```
#dotParse("//demo.dotcms.com/application/vtl/custom-fields/urlmap.vtl")
```

### To see this issue
I f I create a brand new site. A Blank site. Then I attempt to create an instance of the type Blog.
Fill in the required fields then hit save. I get the error 
I get an error "The Field URL Title is required" 
Even though all the required fields have been filled.

### Steps to reproduce the behavior:
1. Build dotCMS with the starter version 20200429 
2. Create a blank site (Name it blank-site)
3. Switch to that new blank-site. 
4. Go to content search. Then create a brand new instance of Blog 
5. Fill all the required fields and hit save.

### Expected behavior
You should be able to create a brand new Blog since Blogs belong to System Host

### Screenshots
![image](https://user-images.githubusercontent.com/37148755/83463059-2c7a0f80-a42a-11ea-9518-f0cbf96ba7e8.png)

**Comment by wezell** [comment] 2020-06-02 19:25
dupe: #18574

**Comment by fmontes** [comment] 2020-06-22 18:28
Only happen in custom fields

**Comment by wezell** [comment] 2020-09-08 15:35
Might be a dupe of #19214  - please test

**Comment by jdotcms** [comment] 2020-09-18 19:25
If you include the host on the custom field, there is not an issue

**Closed** 2020-09-22 16:48 UTC
Labels: Next Release, Not an Issue, Severity : Support Requested, Type : Bug
