### ISSUE TITLE
Prevent Content save if content has legacy relationships and ES is in read only mode

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17601] opened 2019-11-07 16:39 UTC
If you save a piece of content that has a legacy relationships and the Elasticsearch index is in read only mode (disk full, etc), you run the risk of having your legacy relationships getting wiped out.  

We need to prevent content that has a legacy relationships from being saved if the index is in read-only.
 
This does not happen to new relationship fields.

**Comment by nollymar** [comment] 2019-11-08 18:20
A new validation was included. PR against branch `issue-15942`: https://github.com/dotCMS/core/pull/17608

**Comment by dsilvam** [comment] 2019-12-02 15:10
Merged into _External ES branch_ `issue-15942`

**Comment by dsilvam** [comment] 2020-02-26 23:57
Needs work. Looks like we have a missing case here.  

**Tested scenario:**
Updating via REST, using the workflows API, an existing _News_ (old starter) content with Legacy Relationships and having Open Distro cluster in _read_only_ mode *passes the isCheckinSafe* validation, which should not, and as a result saving new version on DB, but throwing an error when trying to update the index, theferefor leaving an inconsistency between the Index and the DB. 

To get technical, the cause of this is that when sending null relationships to our internalCheckin, this is not loading the legacy relationships before executing the `isCheckinSafe`, resulting in that validation being passed and continuing with the checkin process, being able to update the content to db but failing to reindex because of the read_only mode. 

This validation is working as expected from the UI. The issues is presented via REST and would also happen if using our java API directly, calling the contentAPI.checkin method.

**Comment by bryanboza** [comment] 2020-04-27 16:08
Fixed, tested on mater // Postgres // FF

**Closed** 2020-05-05 19:39 UTC
Labels: Merged, Passed Internal QA, Passed QA, Release : 5.3.0, Type : Bug
