### ISSUE TITLE
Error when editing multilingual content that is referenced on monolingual HTML pages

### ISSUE THREAD

**Issue by splotzky** [dotCMS/core#19686] opened 2020-12-10 10:04 UTC
**Describe the bug**
Editing of content in another language is not possible if this content is referenced on an HTML page that does not exist in that other language.

**To Reproduce**
1. Go to 'demo.dotcms.com/dotAdmin'
2. Go to 'Site' > 'Browser' > 'destinations' and notice that the HTML page 'Frensh Alps' only exists in the default language English (US)
3. Now go to 'Content' > 'Banners' and edit 'Frensh Alps' banner content, which is referenced by the HTML page 'Frensh Alps'
4. Translate this banner content to Espanol (ES), populate the English content, click 'Publish' and close the edit popup
5. Now try to edit the newly created Spanish content by clicking on it
6. The edit popup opens and shows the following error message:
```
An unexpected system error occurred.

An exception occurred processing JSP page [/html/portal/view_portlet_inc.jsp] at line [87] 84: 85: boolean portletException = false; 86: 87: cachePortlet.render(renderRequest, renderResponse); 88: 89: SessionMessages.clear(renderRequest); 90: SessionErrors.clear(renderRequest); Stacktrace:
```

**Expected behavior**
The content should be editable without any errors.

**Additional context**
dotCMS version: 20.11

Worked for us before in version 5.3.6.1.

This bug is a big problem for us because we have multiple sites with multiple languages and we can no longer edit hundreds of pieces of content. Because on every site the HTML pages only exist in one language. Only the contents are translated into all languages and referenced on the HTML pages of all sites.

Stacktrace from 'dotcms.log':
```
Caused by: com.dotmarketing.business.DotStateException: Contentlet is null
        at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.fromContentlet_aroundBody2(HTMLPageAssetAPIImpl.java:185) ~[dotcms_20.11_e2cd856.jar:?]
        at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl$AjcClosure3.run(HTMLPageAssetAPIImpl.java:1) ~[dotcms_20.11_e2cd856.jar:?]
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
        at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_20.11_e2cd856.jar:?]
        at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_20.11_e2cd856.jar:?]
        at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_20.11_e2cd856.jar:?]
        at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.fromContentlet(HTMLPageAssetAPIImpl.java:179) ~[dotcms_20.11_e2cd856.jar:?]
        at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.loadPageByIdentifier(ESContentletAPIImpl.java:1163) ~[dotcms_20.11_e2cd856.jar:?]
        at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.getContentletReferences_aroundBody48(ESContentletAPIImpl.java:1194) ~[dotcms_20.11_e2cd856.jar:?]
        at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure49.run(ESContentletAPIImpl.java:1) ~[dotcms_20.11_e2cd856.jar:?]
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
        at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_20.11_e2cd856.jar:?]
        at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_20.11_e2cd856.jar:?]
        at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_20.11_e2cd856.jar:?]
        at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.getContentletReferences(ESContentletAPIImpl.java:1176) ~[dotcms_20.11_e2cd856.jar:?]
        at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.getContentletReferences(ContentletAPIInterceptor.java:1104) ~[dotcms_20.11_e2cd856.jar:?]
        at org.apache.jsp.html.portlet.ext.contentlet.edit_005fcontentlet_jsp._jspService(edit_005fcontentlet_jsp.java:787) ~[?:?]
        ...
```

We debugged dotCMS and found out that the error happened at this point in the code:
https://github.com/dotCMS/core/blob/e2cd8567e8e3c0b1489328afa8a583fc93e11bd0/dotCMS/src/main/java/com/dotcms/content/elasticsearch/business/ESContentletAPIImpl.java#L1194

**Comment by bryanboza** [comment] 2020-12-10 18:33
Able to reproduce on master, here the complete log: https://gist.github.com/bryanboza/a701062d67cc0e1859830fbcdc4359cc

**Comment by fabrizzio-dotCMS** [comment] 2020-12-15 22:34
Verified the error has been fixed in branch `release-20-12`

**Comment by bryanboza** [comment] 2021-01-06 15:23
Fixed, unable to reproduce after the last changes, Tested on release-21.01 // Postgres // FF

**Closed** 2021-01-06 15:47 UTC
Labels: Cat : Content Management, Merged, Passed Internal QA, Passed QA, Release : 21.01, Severity : Support Requested, Type : Bug
