### ISSUE TITLE
When doing a hardlink the copy byte by byte is not being executed

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#9997] opened 2016-10-20 14:56 UTC
When doing a hardlink if an error is throwed, should be run the fallback (copy byte by byte)
## Expected Behavior

Currently when an user uploads a resources and the tomcat temp and assets directory are in diff devices, the hardlink will fails, currently is throwing an exception  and it is not catch, consequently the fallback is not executed. 
## Current Behavior

The fallback must be executed when the hardlink does not work
## Possible Solution

Catch the exception on copyLink and runs the fallback code
## Known Workarounds

Set the CONTENT_VERSION_HARD_LINK to false
## Steps to Reproduce (for bugs)

They are described on this ticket: https://my.dotcms.com/ticket/auto-15
## Context

https://my.dotcms.com/ticket/auto-15

## Your Environment

- dotCMS version used: 3.6
- Browser Name and version: N/A
- Operating System and version: Unix
- Application Server and version: 
- Java Brand and version: 1.8
- Database and version: 
- Application module (if apply):

**Comment by wezell** [comment] 2016-11-01 13:54
Is this a dupe of #9848?

**Comment by wezell** [comment] 2016-11-01 14:00
See pull request: #10002

**Closed** 2016-11-21 19:41 UTC
Labels: Release : 3.6.1, Release : 3.7.0, WF : Merged, WF : Passed QA
