### ISSUE TITLE
We need to keep the My account modal open after you change the password, now we are showing a pop-up with the notification, but we need to go back to the same window after closing it.

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22666] opened 2022-08-02 18:30 UTC
We need to keep the My account modal open after you change the password, now we are showing a pop-up with the notification, but we need to go back to the same window after closing it.

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/22276#issuecomment-1199717563_

**Comment by alfredo-dotcms** [comment] 2022-08-05 17:03
this is a new requirement and not a bug, before doing this task My Account Modal closes after the alert so the behaviour is the same
https://monosnap.com/file/QgSG8S0BYmTtttY7W84ymU9MVa2NL2

**Comment by bryanboza** [comment] 2022-08-05 17:51
According to the @alfredo-dotcms comment maybe does not make sense to come back to the same window b/c we are clicking on the save button. Then is ok to close this window, and proceed to close this card.

**Closed by bryanboza** 2022-08-05 17:51 UTC
Labels: Maintenance Sprint, Next Release
