### ISSUE TITLE
setting language in session at top of template doesn't work

### ISSUE THREAD

**Issue by jtesser** [dotCMS/core#9576] opened 2016-08-12 18:50 UTC
If you do something like this at the top of a template $request.getSession().setAttribute('com.dotmarketing.htmlpage.language', '2')

English images will still show. I would think this would set the language in the session and the follow up requests would serve based on the set session language

**Comment by jtesser** [comment] 2016-08-12 18:51
https://www.flowdock.com/app/dotcms/dev-team-rex/threads/1lOB6s8zqzcwhnpSZ2Nh7hQ2cER

**Comment by dotcmsCodeReview** [comment] 2016-08-12 19:20
Even if you flush cache?

**Comment by wezell** [comment] 2016-08-12 19:22
Sorry, don't mean to reply to my own post - I mean browser cache?

**Comment by jtesser** [comment] 2016-08-16 15:50
not a cache thing here from what I can tell

**Comment by erickgonzalez** [comment] 2016-08-16 16:11
Not able to reproduce, probably fixed with this one https://github.com/dotCMS/core/issues/9512 @DeanGonzalez is gonna update the server with the latest changes and try once again.

**Comment by DeanGonzalez** [comment] 2016-08-17 16:58
I tested and reported to Erick that I am still seeing the errors in my local as of today's build - he is re-testing.

**Comment by dsilvam** [comment] 2016-08-17 21:27
make sure this is working still: https://github.com/dotCMS/core/issues/8388

**Comment by erickgonzalez** [comment] 2016-08-17 21:34
PR: https://github.com/dotCMS/core/pull/9603

**Comment by DeanGonzalez** [comment] 2016-08-18 16:26
I tested this issue again, seems like latest changes have fixed all cases... looking good!

**Comment by DeanGonzalez** [comment] 2016-08-19 14:30
I also tested the case in this task: https://github.com/dotCMS/core/issues/8388 - and something like: http://localhost:8080/?language_id=45 - does pass the test and resolves to the default language, you do have to remember to ctrl/cmd-R to get the image to refresh because of the browser cache, but it works.

**Closed** 2016-08-23 14:20 UTC
Labels: WF : Merged, WF : Passed QA, z-iter-7
