### ISSUE TITLE
Time machine: The system is not working new folders and pages in the snapshot

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7559] opened 2015-04-06 19:44 UTC
When you run a past time machine snapshot and enable the incremental field the system just include the starer sites, and is not showing all the new pages and folders with the show on menu property enabled into the snapshot.... 

To recreate: 
- Create a new folder with a new page in to it
- Enable the show on menu property on both 
- Create a past time machine snapshot 

In the preview try to see the created folder and the page

Tested on nightly build 2015-04-02 // MSSQL // FF

**Comment by bryanboza** [comment] 2015-04-06 19:45
Also maybe we need try to fix this errors that we have in the log:
ERROR viewtools.CalendarWebAPI: find
ERROR util.UtilMethods: addDays
ERROR util.UtilMethods: addDays
ERROR viewtools.CalendarWebAPI: findRelatedEvents

**Comment by dsilvam** [comment] 2016-05-03 20:55
Not able to reproduce

**Comment by bryanboza** [comment] 2016-05-03 21:04
Tested in the last master-3.5 and now this is working as expected, maybe fixed in a different card since this is too old...

**Comment by bryanboza** [comment] 2016-05-03 21:05
Maybe we need check just the errors in the comment #2

**Comment by maurizo** [comment] 2016-05-04 14:23
Second part of the issue is fixed on starter (/application/vtl/pages/events/calendar-detail.vtl)

**Comment by bryanboza** [comment] 2016-05-05 20:02
We need wait the new starter to test...

**Closed** 2017-06-06 14:20 UTC
Labels: Release : 4.1.0, Type : Bug, WF : Needs QA
