### ISSUE TITLE
Can't insert images in the WYSIWYG fields 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6889] opened 2015-01-05 18:00 UTC
We have a console error when you try to insert a new image in a wysiwyg field, the system is showing the follow error and you can't add the image to the filed 

TypeError: wysiwyg_win.document.forms[0].elements[wysiwyg_field_name] is undefined

Tested on master-3.1 // H2 // FF

**Comment by samuelmortha** [comment] 2015-01-12 11:47
This is a duplicate of https://github.com/dotCMS/core/issues/6860

**Closed** 2015-01-12 12:29 UTC
Labels: Merged, Type : bug, WF : Needs QA

**Comment by bryanboza** [comment] 2015-01-12 14:54
Fixed, tested on master- 3.1 // H2  // FF
