### ISSUE TITLE
Unable to add new tags after adding a tag in a double-byte language

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#15107] opened 2018-08-14 18:06 UTC
After you add one tag in a double-byte language, you can not add a second tag in any double-byte language.

## Expected Behavior

Any number of tags should be able to be added in any languages.

## Current Behavior

If you add a first tag in any double-byte language (such as Persian or Chinese), and then attempt to add a second tag in any double-byte language, adding the second tag fails, and the tag UI highlights the first tag in red, indicating that the second tag is identical to the first tag.  This happens even though the strings entered for each tag are different, and even if the languages of the first and second tags are different (as long as both tags are in double-byte languages).

## Possible Solution

From additional testing, it appears that when we compare the tags, any text using double-byte languages is essentially ignored (possibly resolving to an empty string internally).  So whatever code we're using to compare the tags is not handling double-byte characters properly (or at all).

**Note:**
* We should probably have a standard text comparison method that handles double-byte strings properly (and that we can write automated tests for).
* We should then use that method when comparing the tags.
* And ideally we should also search to find other places in our code where we're comparing text strings, and make sure they all use the standard method.
    * This will help us find and fix other issues like this which may be hidden in parts of the code where the problem just hasn't been discovered yet.

## Known Workarounds

The only known workaround is to add a unique string in a non-double-byte language to each of the tags (such as the translation of the tag into English).  This is not a good workaround, but it's all we know of at the moment.

## Steps to Reproduce (for bugs)

1. Login to the demo site (demo.dotcms.com or demo4.dotcms.com).
2. Open the Content Search screen.
3. Select the "News" Content Type.
4. Click the first News content in the list to edit it.
5. In the `Tags` field, add a tag with the following name: مشتری
6. After that tag is added, add a new tag with the following name: 顾客
**Result:** The first tag (مشتری) flashes red, and the second tag (顾客) is not added.

## Context

This practically prevents the use of tags at all in double-byte languages, which include but are not limited to Chinese (Simplified and Traditional), Japanese, Korean, Persian, and Thai.

## Your Environment

* dotCMS version used: 4.3.3 and 5.0.0 (demo4 and demo)
* Browser Name and version: Chrome
* Operating System and version: Win 10 Pro
* Application Server and version: Tomcat (distro)
* Java Brand and version: 1.8

**Comment by wezell** [comment] 2018-08-14 19:54
In javascript, we should to calculate the hash of the tag (ascii or utf8, who cares) and use tag--{hash} as the dom.id when managing the tags. 


![image 1](https://user-images.githubusercontent.com/934364/44114825-45f5fb50-9fda-11e8-9ec0-51e3e60becd9.png)

**Comment by bryanboza** [comment] 2018-08-17 17:51
Tested after the last changes and we still having problems with this values, now we are unable to add more than one tag on this language, this because we recognize that is the same tag that the existing one.
SC: https://screencast.com/t/6Y9mma98mv

**Comment by fmontes** [comment] 2018-08-17 17:55
Changes are not in the release-5.0.1 branch, @dsilvam please cherry-pick it.

**Comment by dsilvam** [comment] 2018-08-17 18:00
where is the PR? I don't see any connected or as a comment @fmontes

**Comment by dsilvam** [comment] 2018-08-17 18:06
PR: https://github.com/dotCMS/core/pull/15113

**Comment by dsilvam** [comment] 2018-08-17 18:10
@bryanboza @fmontes commit: 94d6ba3 cherry-picked into release-5.0.1

**Comment by bryanboza** [comment] 2018-08-20 15:50
Now we are able to add tags with this characters, but we have an error if you try to search by this tags on the Tags portlet 
```
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:476)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:687)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by wezell** [comment] 2018-08-20 18:52
@bryanboza the above needs to be in another card.

**Comment by bryanboza** [comment] 2018-08-20 19:58
The pending case was moved to a new card... The main problem was fixed on this PR... Tested on master // Postgres // FF

**Comment by bryanboza** [comment] 2018-08-22 22:07
The same behavior on master... The new card is pending

**Closed** 2018-09-18 23:56 UTC
Labels: Passed Internal QA, Release : 5.0.1, Type : Bug, WF : Merged, WF : Merged 5.0.1, WF : Passed QA, WF : Passed QA 5.0.1

**Comment by bryanboza** [comment] 2019-09-10 20:01
Yes, also the filtering is working too, the problem is specifically on the tags portlet

**Comment by wezell** [comment] 2019-09-10 20:02
ah, this is a bit less important.
