### ISSUE TITLE
Uploading a new version of an existing plugin with no package changes causes a felix framework restart on a cluster

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#27553] opened 2024-02-08 14:59 UTC
### Problem Statement

When you upload a new plugin version on a cluster, even if it does not update the exported packages, it triggers a cluster-wide restart of the Felix framework. This can lead to short downtimes on instances with critical plugins.

This does not appear to occur on a single-node instance.

### Steps to Reproduce

1. Upload a plugin to a clustered instance.
2. Reupload the same plugin; you will see the cluster restart the Felix framework

### Acceptance Criteria

The behavior should be the same on a single node instance or a clustered instance; if there are no changes to exported packages then just load the plugin.

### dotCMS Version

23.10.24, latest

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/113945

**Comment by jcastro-dotcms** [comment] 2024-02-26 18:19
Hey @swicken-dotcms ! I was not able to reproduce the issue described in this ticket. Here's the test scenario I used to check the current behavior of the OSGi deployment process in a clustered environment:

- I set up a two-node cluster.
- Compiled the [ViewTool Plugin example](https://github.com/dotCMS/plugin-seeds/tree/master/com.dotcms.viewtool) and deployed it to Node 1.
- This caused the OSGi Framework to restart since we're adding classes to the Exported Packages list. This is the expected behavior, and the following message was logged:
```
There are a new changes into the exported packages
```
- Now, I changed the code, and re-compiled it using the provided Gradle Wrapper. The new version was deployed and no restart was made because the list of exported packages didn't change.
- Then, I took one of the plugins provided by the customer in the support ticket, and deployed it to Node 1.
- Just like the first plugin I deployed, this caused the OSGi Framework to restart since we're adding classes to the Exported Packages list.
- Finally, I re-deployed the plugin -- I don't have the source code so I can't re-compile it, unfortunately -- and no OSGi Framework restart was triggered.

Please let me know your thoughts!

**Comment by jcastro-dotcms** [comment] 2024-03-20 13:24
Closing ticket as the described scenario cannot be reproduced in latest master.

**Closed by jcastro-dotcms** 2024-03-20 13:24 UTC
Labels: Type : Defect, Triage, OKR : Customer Support
