### ISSUE TITLE
Copy URL Should Copy URL, not Just URL Slug

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24858] opened 2023-05-08 14:50 UTC
[![Screenshot_2023-05-08_14-50-44.png](https://mrkr.io/s/64590c445d2af2f4d17aa3c1/2)](https://mrkr.io/s/64590c445d2af2f4d17aa3c1/0)

### Problem Statement

Currently, if click "Copy URL" only the slug is copied. 

I only get:

/destinations/french-alps

But I want:

https://demo.dotcms.com/destinations/french-alps

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/edit-page/content?url=%2Fdestinations%2Ffrench-alps&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://demo.dotcms.com/dotAdmin/#/edit-page/content?url=%2Fdestinations%2Ffrench-alps&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/64590c445d2af2f4d17aa3c4_37f560ea108cbe2f?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 112.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1200</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by erickgonzalez** [comment] 2023-05-08 15:38
Dupe of https://github.com/dotCMS/core/issues/24683 ??

**Closed** 2023-05-08 15:47 UTC
Labels: Triage
