### ISSUE TITLE
Aliases not working correctly

### ISSUE THREAD

**Issue by Xander-Steinmann** [dotCMS/core#18187] opened 2020-03-25 16:26 UTC
### Describe the bug
After performing an upgrade from dotCMS 5.1.6 to dotCMS 5.2.6 or 5.2.7 the system doesn't recognize all aliases any more and therefore defaults to the default site. This means that many sites are not accessible any more.

### Steps to reproduce the behavior:
1. Go to the demo site
2. Edit demo.dotcms.com: Set the hostname to test.dotcms.com and add alias demo.dotcms.com
3. Flush all caches

If you now go to demo.dotcms.com the site will display correctly
4. Create a new empty site called "empty" and make it the default host
5. Add alias not-demo.dotcms.com to the empty site
6. Flush all caches

Now when you go to demo.dotcms.com the site will not display. That's because dotCMS tries to show you the empty site.

### Cause
The reason is a piece of code in HostAPIImpl.findByAlias. It executes a query to find the aliases but it uses the following script: "+Host.aliases:demo.dotcms.com". This will return the host with alias demo.dotcms.com and the host with alias not-demo.dotcms.com. Because the empty site is the default site that one will be returned. This is not correct.

### Solution
The query in findByAlias (and findByName) should use exact matching of the alias/name and not partial matching. I'm not sure whether this can be achieved in the query but it can be checked in the results. In that case the 'use default site in case of multiple results' code should be changed/replaced.

**Comment by wezell** [comment] 2020-03-25 17:13
@Xander-Steinmann can you try something?  Can you add a custom es mapping to the `host.alias` field from the content type screen?   I think the problem might be worked around via a custom es mapping to the `host.alias` field.  You can add a field variable for the field like so:

https://dotcms.com/docs/latest/how-content-is-mapped-to-elasticsearch#CustomFieldExample1

I would think the `whitespace` analyzer would fix it.

**Comment by Xander-Steinmann** [comment] 2020-03-31 14:45
@wezell : Unfortunately I can't test your solution since the index does not finish when I add the elasticsearch settings.

**Comment by wezell** [comment] 2020-07-01 18:58
I believe this is a dupe of #18805

**Comment by freddyucv** [comment] 2020-07-07 14:21
PR: https://github.com/dotCMS/core/pull/18829

**Comment by wezell** [comment] 2020-07-08 19:11
dupe: #18805

**Comment by dsilvam** [comment] 2020-07-14 19:43
Passed Internal QA: demo.dotcms.com displaying properly after following described steps

**Comment by bryanboza** [comment] 2020-07-14 20:11
Fixed, tested on release-5.3.4 // Postgres // FF. 

FYI: To test locally you need to add the URL to the host file.

**Closed** 2020-07-15 19:06 UTC
Labels: Merged, Passed Internal QA, Passed QA, Release : 5.3.4, Type : Bug
