### ISSUE TITLE
Instances created with a different default language than the one that is currently set break when upgrading past 20.10.1

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#20786] opened 2021-08-12 15:10 UTC
**Describe the bug**
When a dotCMS instance was initially created with a starter with a default language (say English), and that default language was changed after, upgrading the instance to 20.11 and beyond causes several errors related to looking up the host.

Reproduced on: 20.11, 21.06
Ticket: https://dotcms.zendesk.com/agent/tickets/105010

**To Reproduce**
- Setup the system with version 5.3.8.5 with the standard default language (I did so on docker)
- Create the German language with the following settings:  
![image](https://user-images.githubusercontent.com/78741732/129220720-deb359bf-5311-4d13-8e19-68551ea0be96.png)
- Shut down the system and add the following environment variables
```
      "DOT_DEFAULT_LANGUAGE_COUNTRY": 'Deutschland'
      "DOT_DEFAULT_LANGUAGE": 'de_DE'
      "DOT_DEFAULT_LANGUAGE_CODE": 'de'
      "DOT_DEFAULT_LANGUAGE_STR": 'Deutsch'
      "DOT_DEFAULT_LANGUAGE_COUNTRY_CODE": 'DE'
```
- Change the image to `dotcms/dotcms:20.11`
- Start up dotCMS

You will no longer be able to access many portlets, they will result in JSP/NPE errors.

**Expected behavior**
You should be able to upgrade without issue even if the site initially started in another default language.

Currently there is a workaround detailed in this comment: 

https://github.com/dotCMS/core/issues/20112#issuecomment-842661608

The thought for the current fix is to take those SQL statements and make an upgrade task for them. 

```
update contentlet set language_id = {langId} where language_id = '1' and identifier not in (select identifier from contentlet where language_id = {langId});
update contentlet_version_info set lang = {langId} where lang = 1 and identifier not in (select identifier from contentlet_version_info where lang = {langId});
update workflow_task set language_id = {langId} where language_id = 1 and webasset not in (select webasset from workflow_task where language_id = {langId});
```

NOTE: After completing this workaround you must clear cache/reindex.

**Comment by wezell** [comment] 2021-08-17 20:30
1. We need to not break if the default language changes.  This means hosts will still resolve.

2. We need a field on the company table that holds the default language (use the iso lang value, e.g. en_us).

Users can set the default language to whatever they want there.  If the default language is NOT set in the company table but is set in the `dotmarketing-config.properties` file, we should insert the language into the language table and also into the company table as the defaul.

**Comment by fabrizzio-dotCMS** [comment] 2021-08-31 15:34
I added code that will attempt to match the default language. if not found we default to the first ContentletVersion info entry found. Change seems harmless. We could consider overriding Host.setLanguage to prevent having sites under different languages too. 

Upon fixing this and on further testing,  I changed the default language to another different from English and again I found another similar problem looking up Templates.

```
0:48:44.891  ERROR business.TemplateFactoryImpl - Can't find ContentletVersionInfo. Identifier:6d43c00c44584db623193b545670a8d5. Lang:4660718
com.dotmarketing.exception.DotDataException: Can't find ContentletVersionInfo. Identifier:6d43c00c44584db623193b545670a8d5. Lang:4660718
    at com.dotmarketing.portlets.templates.business.TemplateFactoryImpl.getTemplateByFolder(TemplateFactoryImpl.java:700) ~[dotcms_master_dad3615.jar:?]
    at com.dotmarketing.portlets.templates.business.TemplateFactoryImpl.convertFoldersToTemplates(TemplateFactoryImpl.java:877) ~[dotcms_master_dad3615.jar:?]
    at com.dotmarketing.portlets.templates.business.TemplateFactoryImpl.findFolderAssetTemplate(TemplateFactoryImpl.java:906) ~[dotcms_master_dad3615.jar:?]
    at com.dotmarketing.portlets.templates.business.TemplateFactoryImpl.findTemplates(TemplateFactoryImpl.java:272) ~[dotcms_master_dad3615.jar:?]

```

The Exception is handled well but I don't think we can control the language on which templates are created. 
They Will always be created under the default language. Therefore the template becomes useless if created under a different language.

**Comment by alfredo-dotcms** [comment] 2021-08-31 18:59
As menctioned here https://github.com/dotCMS/core/issues/20786#issuecomment-909348058

also there's an error in Container's page 
https://gist.github.com/alfredo-dotcms/4527c8df5c1130152f30f354dbdbfc31

**Comment by alfredo-dotcms** [comment] 2021-08-31 19:02
also when trying to open a `rich text` in the Content Search page, the dialog breaks (not sure if it's related with this task)
![image](https://user-images.githubusercontent.com/37185433/131560712-e1758acc-7888-4ab0-a6e8-063dc03cd7ee.png)

log:
https://gist.github.com/alfredo-dotcms/aff9a93c19ca341a059632aa784d18f1

**Comment by nollymar** [comment] 2021-08-31 22:37
The issue reported by @alfredo-dotcms will be fixed here: https://github.com/dotCMS/core/issues/20887

**Comment by fabrizzio-dotCMS** [comment] 2021-09-29 17:06
Note For QA: 
The scenario that needs to be tested here is: 

1. You start dot cms with a full starter. Using the original default language that comes out of the box. 
2. Now create a new Language that will be used as the new default lang let's say, German.   
    So on dotmarketing-config.properties
   Look for this: 
       DEFAULT_LANGUAGE_COUNTRY = United States
       DEFAULT_LANGUAGE = en_US
       DEFAULT_LANGUAGE_CODE = en
       DEFAULT_LANGUAGE_STR = English
       DEFAULT_LANGUAGE_COUNTRY_CODE = US
       And make those properties point to the new language you want to use a default 
3. Now start dotCMS again and check pages to see if the container loads  
4. If the problem persists it can be fixed from the Languages portlet transferring all assets from the old default language to the new one.

**Comment by alfredo-dotcms** [comment] 2021-09-29 18:02
New issue:

When creating a new page with the empty starter with default language `DE` a BAD REQUEST error is thrown

![image.png](https://images.zenhubusercontent.com/5aa153f34b5806bc2bca024d/bfd698ba-7ea8-463d-b972-ad943b8307de)

Steps:
- Start with empty starter
- Add `DE` language and make it default
- Go to SITE BROWSER and add a new page


Error log:

https://gist.github.com/alfredo-dotcms/457f150491fb8b3003ac0262779a81fb

**Comment by bryanboza** [comment] 2021-11-02 20:41
Fixed, unable to reproduce after the last changes changing the default language, now it is working as expected. 
Tested on release-21.11 // Docker // FF

**Closed** 2021-11-15 17:24 UTC
Labels: Type : Bug, Passed QA, Merged, Severity : Support Requested, Passed Internal QA, Release : 21.11, Team: Scout

**Comment by swicken-dotcms** [comment] 2021-11-17 19:13
Evaluating this change for 21.06.X, but not 5.3.8.X
