### ISSUE TITLE
Resolve CLI Issues in Latest Trunk

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#28980] opened 2024-06-21 22:25 UTC
### Problem Statement

Users are unable to use the CLI in the latest trunk version of the application. This issue prevents users from performing essential command-line operations, affecting their productivity and workflow.
![image](https://github.com/dotCMS/core/assets/2641437/4f92cc2c-0b64-438e-a68d-5ed3db5fc8f7)

### Steps to Reproduce

- Check out the latest trunk version of the application.
- Update the CLI to the latest version using `npm install -g @dotcms/dotcli@rc`
- Attempt to login the CLI to perform various operations.
- Observe that the CLI fails to execute commands or returns errors.

### Acceptance Criteria

**Functioning CLI**: Ensure that the CLI works correctly in the latest trunk version, allowing users to execute commands without errors.

### dotCMS Version

Tested on trunk [_bbb39f0]

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by fabrizzio-dotCMS** [comment] 2024-06-21 22:41
It seems to be happening only withe the native image.  I tried login in using only the jar and it works. Perhaps the native image is missing the build.properties file

**Comment by nollymar** [comment] 2024-06-24 15:29
Dupe of https://github.com/dotCMS/core/issues/28915

**Closed by nollymar** 2024-06-24 15:29 UTC
Labels: Type : Defect, Team : Scout, Triage
