### ISSUE TITLE
Changing a page's template removes all content from the page's containers

### ISSUE THREAD

**Issue by flackend** [dotCMS/core#23180] opened 2022-10-17 18:14 UTC
When editing pages that utilize a designer template, making any number of changes (e.g. adding a new container or a row CSS class) to the template that's in use removes all content from the page's containers.

1. Open a page to edit in dotAdmin
2. Switch to the layout editor
3. Make a change (add a container, add CSS class to a row, etc)
4. Switch back to the content editor
5. Click "Publish"

At this point all the content that had been in the containers disappears forcing the user to rebuild the page.

I've noticed in some cases that returning to the layout editor, making an additional change, then publishing the page will restore _some_ of the content to the containers.

This issue occurs on all of the existing designer templates we have (none of which have been edited for 2 years beyond the ones I've created while debugging). It is not reproducible on newly created templates. Even those that replicate existing templates. So creating a new designer template and replicating the number and type of rows and containers of an existing template, and utilizing that on a page, results in not being able to reproduce this issue on that page. Though I can reproduce the issue after making a direct copy of a one of the existing templates (i.e. go to templates portlet, click the actions menu and then "Copy").

I found that I can reproduce this by making any number of changes to the template (adding a new row and new container, adding a new container to an existing row, adding a row CSS class, etc).

Another way to reproduce this is to switch to any other template via the page's "Properties" modal other than a direct copy of whatever the current template is. Even creating a new designer template and replicating the same number and type of rows and containers. Switching to the replica will result in all containers being emptied.

This puts us in a tight spot since I haven't yet found a way to edit a page's template without having to add all the content back afterwords.

Reproducible in 21.06.1

**Comment by flackend** [comment] 2022-10-20 16:31
I did some debugging this morning. I created a new template then took a look at the `template` table in the database to see if I could see any differences between it and the old templates. The thing that stuck out was the `drawed_body` column. The old templates hold HTML in that column and newly created templates hold JSON. I also copied (via dotAdmin) one of the old templates and noticed the copy retained HTML in that column until I made a change to the copy (again, in dotAdmin). At that point the HTML had been swapped out with JSON in that `drawed_body` column.

I'm sure there's more to this than I understand. I don't even know what that column is used for. But this does line up perfectly with the debugging I had already done for this issue and #23181 — the content disappears from containers when transitioning between what I assume is an old/deprecated format and the a new format for template records in the database.

**Comment by muhammadfaizandotcms** [comment] 2022-10-24 16:47
I was able to reproduce it on 22.03.2 but I could not reproduce it on the demo 22.09.
[screencast-from-10-24-2022-092804-pm_bLgFWbTq.webm](https://user-images.githubusercontent.com/103441252/197580402-ef3ef779-cdd3-40dc-9303-b949af1f9afa.webm)

**Comment by erickgonzalez** [comment] 2022-11-15 18:34
Not able to reproduce this in 21.06.11 LTS 

https://user-images.githubusercontent.com/5278970/201998277-c59b34ec-851c-4a6f-8022-ee82e2feaab2.mov

**Comment by erickgonzalez** [comment] 2023-02-02 23:01
fixed in https://github.com/dotCMS/core/issues/22140

**Closed by erickgonzalez** 2023-02-02 23:01 UTC
Labels: Type : Defect, Severity : Support Requested, Maintenance Sprint, OKR: Customer Support
