### ISSUE TITLE
Turn off Image Drag and Drop Into WYSIWYG Field

### ISSUE THREAD

**Issue by ian-b-cooper** [dotCMS/core#21466] opened 2022-01-03 20:55 UTC
**Is your feature request related to a problem? Please describe.**
When users drag and drop local image files into the WYSIWYG editor, they files are uploaded as a binary into the root folder. This makes it difficult for editors to find these images again.

Please see this ticket for additional context: https://dotcms.zendesk.com/agent/tickets/106063

**Describe the solution you'd like**
Create the ability to prohibit drag and drop of images into the WYSIWYG editor

**Describe alternatives you've considered**
When an image is dropped into the WYSIWYG editor, allow for a menu to pop up that enables a selection of where the binary will be stored in the folder structure. 

**Additional context**
As per this request: https://github.com/dotCMS/core/issues/19972 if turning off the ability to upload via drag and drop is not an option, then perhaps the alternative solution of selecting where the binary can be stored can be similar to the suggested solution for the above request

**Comment by alfredo-dotcms** [comment] 2022-05-09 17:40
this was fixed on this ticket https://github.com/dotCMS/core/issues/19956

**Comment by wezell** [comment] 2022-05-17 18:09
This should be enabled by default and only be disabled if the config `dragAndDrop` is set to false

**Comment by bryanboza** [comment] 2022-05-17 18:12
The D&D to those fields is not working in the release branch

**Comment by alfredo-dotcms** [comment] 2022-05-19 19:06
PR: [https://github.com/dotCMS/core/pull/22260](https://github.com/dotCMS/core/pull/22260#pullrequestreview-979111977)

**Comment by nollymar** [comment] 2022-05-20 22:42
**Internal QA:** I think it needs work

Now, it is enabled by default which is correct. But when I disable it, the component behaves a bit odd because it doesn't add the image but opens it in a new tab. 

I've recorded a video with more details: 

https://user-images.githubusercontent.com/8741395/169621328-fd15567d-293b-4632-8b7c-f85d2da3a995.mov

**Comment by alfredo-dotcms** [comment] 2022-05-20 22:49
that's the normal behaviour of the browser when a file is dragged into a html page, IMO not an issue

**Comment by nollymar** [comment] 2022-05-24 20:35
As this is the expected behavior, I'm passing the internal QA

**Comment by bryanboza** [comment] 2022-05-26 21:17
Fixed, now this is working as expected. Tested on release-22.06 // Docker // FF

**Closed** 2022-05-31 18:35 UTC
Labels: Type : Enhancement, Passed QA, Merged, Cat : UI, Passed Internal QA, Team: Scout, Release : 22.06
