### ISSUE TITLE
UVE content pallet is not being filtered by the containers on the page

### ISSUE THREAD

**Issue by fishsmith** [dotCMS/core#30065] opened 2024-09-18 21:30 UTC
### Problem Statement

UVE content pallet is not being filtered by the containers on the page. You should only see the content type sin the pallet that are allowed on the page.

<img width="1605" alt="Screenshot 2024-09-18 at 5 25 47 PM" src="https://github.com/user-attachments/assets/0971bd85-8f24-4a63-ab7e-6e9fa9b448c4">

### Steps to Reproduce

1. create a page and add a container that only takes a specific type of content.
2. open in UVE
3. You will see all content types including system content types like personas etc...

### Acceptance Criteria

Only show the content types and widget that the containers on the page except

### dotCMS Version

current

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

**Comment by valentinogiardino** [comment] 2024-09-24 15:13
We began by testing the filter functionality by switching between different containers and creating new ones with restricted content types. In all cases, the filter worked as expected locally, and we were unable to reproduce the issue.

To further investigate, we collaborated with @zJaaal to attempt to reproduce the issue in the environment where it was originally reported. Upon analyzing the page's API response, we discovered that a system container was unexpectedly appearing in the container structure, even though it wasn’t placed in the defined layout. This caused the content pallet to display content types allowed for both the specified containers and this system container.

Despite our efforts, we were unable to reproduce this condition on other pages locally or in different environments.

**Workaround:** As a workaround, the page can be recreated without specifying the system container.

**Closing the issue, as we were unable to reproduce it.**

### Videos
#### Adding a custom container
https://github.com/user-attachments/assets/f8cbe9f9-dc91-489f-bd9a-2546621a6fa4
#### Creating a copy of a page with system container
https://github.com/user-attachments/assets/6c500ce7-ad78-4fed-85a6-a6fb3b58ebe4
#### Creating a copy of a page without system container
https://github.com/user-attachments/assets/0fb50b48-d116-4e8b-ace4-6b6f30ce099c
#### Creating a page with multiple containers
https://github.com/user-attachments/assets/560b8692-dc78-4cbc-be2c-716051999a82

**Closed by valentinogiardino** 2024-09-24 15:13 UTC
Labels: Type : Defect, Team : Scout, Gardening Day

**Comment by fmontes** [comment] 2024-09-24 15:38
👍🏽
