### ISSUE TITLE
WYSIWYG field doesn't show any images in folder

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#24089] opened 2023-02-13 14:41 UTC
### Problem Statement

When you go into a WYSIWIG editor called and try to add an image using that editor, no result will be shown in any folder.

### Steps to Reproduce

Create a new content type with both an Image field and a WYSIWYG field.  Then create a new content item of that content type.  You can add an image to the Image field from any of the subfolders on the site that have images in them.  But in the WYWISYG field, you can't see any images in the subfolders.

If you check Network request then response is empty list for images

### Acceptance Criteria

WYSIWYG editor should allow to add images as Image field allows to add images

### dotCMS Version

23.01

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/110036

**Comment by erickgonzalez** [comment] 2023-02-13 14:52
Dupe of https://github.com/dotCMS/core/issues/23926

**Closed by erickgonzalez** 2023-02-13 14:52 UTC
Labels: Type : Defect, Triage
