### ISSUE TITLE
Respect the contentlet language to search for contentlets in the editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#22159] opened 2022-05-05 21:45 UTC
**Is your feature request related to a problem? Please describe.**
When the user is adding contentless to a block editor we need to show only the contentlets in the language of the "current contentlets" where the field is.

**Describe the solution you'd like**
We need to pass, from the JSP, the current language to the block editor so we can use that to filter the contentlets.

**Describe alternatives you've considered**
I think there is no way to get the current language from inside the block editor.

**Additional context**
We definitely needs JSP work here.

**Comment by oidacra** [comment] 2022-05-10 18:08
Core PR: https://github.com/dotCMS/core/pull/22185
Core-Web Pr: https://github.com/dotCMS/core-web/pull/1976

**Comment by oidacra** [comment] 2022-05-12 16:25
Moved to 22.06

**Comment by rjvelazco** [comment] 2022-05-13 17:40
The `contentlets` request fail while I was doing `Internal QA`, which can be due to this issue: #22039

That issue has two parts:
- https://github.com/dotCMS/core-web/pull/1975
- https://github.com/dotCMS/core/pull/22158

I am waiting for those changes to be merged to try again.

**Error**

https://user-images.githubusercontent.com/72418962/168337833-9708dbb4-d23b-4b8e-846f-1514454af487.mov

**Comment by bryanboza** [comment] 2022-05-25 22:33
We still getting the same error in the JS console, if you try to change the language of the content and then type "/" in the blog editor field, we are getting those errors 
![image](https://user-images.githubusercontent.com/2641437/170380465-b6fe1ed6-b315-4936-98b9-57e71a4effe2.png)

To recreate: 
- Login as admin 
- Try to add a new blog 
- Change the lang to Spanish 
- Type "/" in the blog editor
- Check your console 

Video: 
https://user-images.githubusercontent.com/2641437/170380616-37807310-2eab-4f5d-a83b-6f2102a04440.mov

**Comment by oidacra** [comment] 2022-05-26 17:18
Hi, after check. We found the origin of the console error and it's not related to this ticket. Was entered on the ticket https://github.com/dotCMS/core-web/pull/1973 @hmoreras is taking a look to fix it. 

The other message in the console `Assertion failed...` come from LastPass

**Comment by hmoreras** [comment] 2022-05-31 16:16
fix the subscription error: https://github.com/dotCMS/core/pull/22314/

**Comment by oidacra** [comment] 2022-06-02 17:02
@bryanboza I cant simulate the problem, I'm using the tag `22.06_413b9cb5_SNAPSHOT`

https://www.loom.com/share/04f8ca65c1fd45628971092cdd5c7243

**Comment by bryanboza** [comment] 2022-06-10 19:07
Fixed, tested on release-22.06 // Docker // FF. Unable to reproduce the case of my last comment, maybe was fixed by a recent change or related to the browser cache.

**Closed** 2022-06-14 14:46 UTC
Labels: Type : Enhancement, Passed QA, Maintenance Sprint, Release : 22.06
