### ISSUE TITLE
Unable to edit or add files to the themes folders 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#14691] opened 2018-06-21 18:49 UTC
We have an error when you try to edit some themes folder, we have the follow error and you are unable to see the folder properties.  Additionally, you cannot add a new file under a them folder.

Error: **"The page information is out of date"**

## Expected Behavior
We need be able to edit this folders without problems 

## Current Behavior
Seems the those folders don't have identifier then we are unable to edit or upload files in to it
ST: https://gist.github.com/bryanboza/6b8d483d8b67458ff98c578323b5cfb0

## Steps to Reproduce (for bugs)
1. Login as admin 
2. Go to site browser 
3. Navigate to application --> Themes 
4. Try to edit any of the folders 

## Your Environment
Tested on master // Postgres // FF

**Comment by wezell** [comment] 2018-06-21 21:16
Caused by changes here: #14456

**Comment by nollymar** [comment] 2018-06-22 18:37
Fixed in https://github.com/dotCMS/core/issues/14456

**Comment by bryanboza** [comment] 2018-06-28 16:37
Fixed, tested in the last master code and now this is working

**Closed** 2018-07-03 14:39 UTC
Labels: Passed Internal QA, Release : 5.0.0, Type : Bug, WF : Merged, WF : Passed QA
