### ISSUE TITLE
UI - Favorite Page: Contentlets infinite scroll table on Pages Portlet

### ISSUE THREAD

**Issue by alfredo-dotcms** [dotCMS/core#23792] opened 2023-01-11 22:56 UTC
### Parent Issue
#22343 

As an user I would like to display on the Pages portlet a table that displays Pages and Contentlets following the design:

![image.png](https://images.zenhubusercontent.com/5aa153f34b5806bc2bca024d/c7552a4c-8236-4366-8a00-e6d985860d67)

Acceptance criteria (**more on comments**)
- when clicked on "Create Page" it should behave like the `Welcome` portlet link (STEP 4), which opens a dialog to create a new page
- the options displayed on each row button (depending on the current contentlet status) can be the following:
![image.png](https://images.zenhubusercontent.com/5aa153f34b5806bc2bca024d/b0d35e83-3fa9-4754-a760-9787dec4b2be)
- a filter box should allow the user to do specific searches by TITLE and URL
- the data should be sorted by last modified by default
- the data displayed on the table must belong to the current site/host
- the table should have an infinite scroll behaviour for loading data

**Comment by wezell** [comment] 2023-01-11 23:15
@alfredo-dotcms - regarding the options, I would use the same logic as we use on the card view.  This is important because different pages can be in different workflow steps and have different options.
![Screen Shot 2023-01-11 at 6 15 02 PM](https://user-images.githubusercontent.com/934364/211938449-052ef32a-9402-4940-a0ec-7b6ae82ea6cb.png)

**Comment by alfredo-dotcms** [comment] 2023-02-17 18:34
PR: https://github.com/dotCMS/core/pull/23929

**Comment by alfredo-dotcms** [comment] 2023-02-17 18:39
more requirements:
- Group STATUS & LANGUAGE into a single column called “Status” and add the lock icon
- When the new column “Status” is clicked it will sort by Status field
- The language flag needs to be removed and design needs to match what we currently have on Content Search listing portlet
- The URL field needs to have a tooltip
- The table needs to have a min-width to avoid header’s title to wrap
- “Last Edit Date” header title needs to be changed to “Last Edited”
- Focus on filter input text when page loads
- Remove gray border on PAGES portlet

Favorite Pages
- We need to add the dotted icon button and it needs to behave just like the pages table

**Comment by alfredo-dotcms** [comment] 2023-02-17 18:40
latest design mock
![image](https://user-images.githubusercontent.com/37185433/219756871-357600ad-b0f4-47f1-8f7a-dc823e055488.png)

**Comment by nollymar** [comment] 2023-02-24 17:08
**Internal QA results:** Needs work

- [ ] When I search by URL I need to type exactly the full url to get a match. Searching by title works ok 
- [ ] Clicking on "Create Page" opens the Edit Page dialog to create a new one but it's redirecting to the Content Search under the covers, then when I close the dialog, the Favorite Pages portlet is gone
- [ ] If I edit a page using right click and save it, the new changes aren't always displayed in the table. The Pages table doesn't refresh sometimes
- [ ] There are two missing keys: `create.page` and last.edited

**Comment by alfredo-dotcms** [comment] 2023-02-27 22:52
![image](https://user-images.githubusercontent.com/37185433/221705184-7dc65cf9-76b4-4720-8061-8dda8d8f78ca.png)

this is the expected behavior when creating new content

**Comment by alfredo-dotcms** [comment] 2023-02-27 22:53
![image](https://user-images.githubusercontent.com/37185433/221705891-952dcb83-caa3-4944-927a-59fdf0bbc589.png)

this will be fixed when this PR gets merged https://github.com/dotcms/core/issues/24173

**Comment by alfredo-dotcms** [comment] 2023-03-02 21:07
PR: https://github.com/dotCMS/core/pull/24265/files

**Comment by jgambarios** [comment] 2023-03-16 18:29
**Internal QA:** Needs work

### Edit Page don't refresh list
I'm still able to reproduce a previously reported issue:
"If I edit a page using right click and save it, the new changes aren't always displayed in the table and the context menu doesn't list the options correctly. The Pages table seems to not be refreshing sometimes."

https://user-images.githubusercontent.com/923947/225717986-c5a886c2-9a10-48b3-a879-04600660b8c8.mp4

**Comment by jgambarios** [comment] 2023-04-14 18:19
Just for tracking, I'm able to reproduce the issue in the latest 23.05, but it is fixed in master.

**Comment by josemejias11** [comment] 2023-05-15 16:00
**Failed QA** - Tested on **23.06_21c1c10b_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

When scroll bar is take it to the bottom of the line and you scroll once again, the scrolling goes into infinite scrolling and beyond.


https://github.com/dotCMS/core/assets/129882031/238e754f-aa4b-4218-a28e-a3a9f5f9d1b5

**Comment by fmontes** [comment] 2023-05-22 15:14
Fixed!

https://github.com/dotCMS/core/assets/751424/2189a08f-2628-4590-9daf-7a4ef43718c6

**Closed** 2023-07-31 20:57 UTC
Labels: QA : Approved, Merged, dotCMS : Admin Tools, QA : Passed Internal, Team : Lunik, OKR : Core Features, Release : 23.06
