### ISSUE TITLE
Pull announcements from the feeding endpoint

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25735] opened 2023-08-08 20:54 UTC
### Parent Issue

https://github.com/dotCMS/core/issues/25733

### Task

This card is meant to integrate FE logic with the endpoint implemented on #25734

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

Announcements should be pulled from the endpoint as a JSON

**Comment by nollymar** [comment] 2024-01-17 15:45
Dupe of #25738

**Comment by dcolina** [comment] 2024-01-29 18:33
Internal QA: Passed.

**Comment by bryanboza** [comment] 2024-01-30 23:51
Fixes, tested on master and it is working as expected some enhancements reported here: https://github.com/dotCMS/core/issues/25736#issuecomment-1915291003

**Comment by bryanboza** [comment] 2024-01-31 00:34
We need some work here: 

We are unable to pull announcements in multiple languages, if you change the default lang we are unable to use the announcements in the selected language. 

- We need to pull the announcement in the session language, and if this does not exist pull the default language.

**Comment by manuelrojas** [comment] 2024-02-05 17:59
**Internal QA Approved** 

![image](https://github.com/dotCMS/core/assets/3438705/87a66bbf-ef55-403c-bab4-2d7dda6cf1a2)

**Closed** 2024-02-09 21:10 UTC
Labels: QA : Approved, QA : Passed Internal, Team : Scout, Type : New Functionality, OKR : Core Features, OKR : Marketing, Priority : 3 Average, Next Release
