### ISSUE TITLE
We are duplicating pages when you add a new experiment 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#23880] opened 2023-01-24 20:02 UTC
### Problem Statement

When you add some experiment to a page, we are duplicating the page in Site Browser. After this happens, we are unable to delete the page 
![image](https://user-images.githubusercontent.com/2641437/214395029-fc21e277-9d92-41a2-a10a-c1e9363ecee4.png)

When you try to delete one of these, we are getting the following error 
![image](https://user-images.githubusercontent.com/2641437/214395147-10be759d-74f1-4cb0-bfee-024e9a290b0b.png)

Complete ST: https://gist.github.com/bryanboza/15463573b5e62e311368ef5d54ff119a

### Steps to Reproduce

- Login as admin
- Apply EE license 
- Add a new page 
- Create a new variant for this page 
- Go back to site browser and see the duplicated page 

### Acceptance Criteria

- We need to be able to create experiments on every page
- Need be able to delete the page, does not matter if have experiments associated or not 

### dotCMS Version

Tested on release-23.02 // Docker

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by freddyucv** [comment] 2023-01-24 20:35
this is the same issue of https://github.com/dotCMS/core/issues/23833

**Comment by damen-dotcms** [comment] 2023-01-26 02:54
Dupe of https://github.com/dotCMS/core/issues/23833

**Closed by damen-dotcms** 2023-01-26 02:54 UTC
Labels: Type : Defect, Team : Falcon, Release : 23.02, Triage
