### ISSUE TITLE
Page Navigation not work for SAML Backend User with Front-End role 

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#23657] opened 2022-12-22 19:45 UTC
### Describe the bug
When a SAML user has access to backend as well as Front-End role then while page editing navigation doesn't work as expected and always returns to source page. 

### To Reproduce
1. Create SAML user
2. Give access to DOTCMS_FRONT_END_USER Role
 ![SAML user with Front-end role](https://user-images.githubusercontent.com/102758033/209212361-04b027cf-53ed-4650-97f1-c2ff5741844a.png)
4. Open page 
![image](https://user-images.githubusercontent.com/102758033/209213166-1bb1e7a0-861a-4e7b-882e-dba5891747f4.png)

5. E.g After opening (Blog Detail) page then click on any button/page that (Navigate) leads to another page/source (Activities). It will show target page (Activities) but whenever click on Edit button then it opens source page (Blog Detail) for editing not target (Activities).

### Expected behavior
The expected behavior is to allow editing for target page after navigation (e.g Activities).

The full details discussion on slack.
https://dotcms.slack.com/archives/G01N0AU1NUC/p1671468948118499

**Comment by damen-dotcms** [comment] 2023-02-15 21:22
Dupe of #23948

**Closed by damen-dotcms** 2023-02-15 21:22 UTC
Labels: Type : Defect, Priority : 3 Average, OKR : Code Maintenance, OKR: Customer Support
