### ISSUE TITLE
Workflow Import api throws workflowImportObject required

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#28584] opened 2024-05-16 10:36 UTC
### Problem Statement

 When importing workflow using by export api so it returns error workflowImportObject required due to https://github.com/dotCMS/core/blob/0ba9739fee96b648530bd0180303e681d3efd99f/dotCMS/src/main/java/com/dotcms/workflow/form/WorkflowSchemeImportObjectForm.java#L13
 
 ![image](https://github.com/dotCMS/core/assets/102758033/5a699fc4-9146-460d-95f3-1dddbb295711)

### Steps to Reproduce

When workflow is exported through API e.g https://demo.dotcms.com/api/v1/workflow/schemes/484b88b7-c766-44db-bd34-c36741d7d0ac/export#

![image](https://github.com/dotCMS/core/assets/102758033/5fc62ff9-40ed-4fed-b8bc-2c0409ebc6b2)

It returns json with **entity** object. However when using exactly that json in import API (https://demo.dotcms.com/api/v1/api/v1/workflow/schemes/import) it returns error workflowImportObject required due to https://github.com/dotCMS/core/blob/0ba9739fee96b648530bd0180303e681d3efd99f/dotCMS/src/main/java/com/dotcms/workflow/form/WorkflowSchemeImportObjectForm.java#L13

![image](https://github.com/dotCMS/core/assets/102758033/5a699fc4-9146-460d-95f3-1dddbb295711)

So the solution is to remove entity object and only keep **permissions** and **workflowObject**

<img width="395" alt="image" src="https://github.com/dotCMS/core/assets/102758033/ba50b720-3250-4d11-ad77-b09334da7833">

### Acceptance Criteria

Whether export tool should return json without entity object or import tool accept entity object however both should align and import tool can create workflow without editing json that returns by export API.

### dotCMS Version

All version including 24.05.13

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/116340

**Comment by erickgonzalez** [comment] 2024-10-01 15:27
Dupe of https://github.com/dotCMS/core/issues/29730. Closing this one

**Closed by erickgonzalez** 2024-10-01 15:27 UTC
Labels: Type : Defect, Triage, OKR : Customer Support, Team : Bug Fixers
