### ISSUE TITLE
End point being NULL causing issues with retreving content

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#27460] opened 2024-01-26 20:54 UTC
### User Story

End point being NULL causing issues with retrieving content

Records being created in database for inodes with endpoint as null
This is causing an issue with opening the contentlets

### Acceptance Criteria

we should be able to open the content regardless of that and maybe throw a WARN in the log saying that the endpoint_ids is blank/null.
Right now, the workaround is to delete the rows manually from the DB.

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/114817

**Comment by erickgonzalez** [comment] 2024-04-11 20:28
Closing since dupe of: [Investigate why endpoint_ids in the table publishing_pushed_assets are null](https://github.com/dotCMS/core/issues/27928)

**Closed by erickgonzalez** 2024-04-11 20:28 UTC
Labels: Priority : 4 Low, Triage, OKR : Customer Support
