### ISSUE TITLE
Edit Content: Relationship table does not render correctly with non-live children 

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#17275] opened 2019-09-17 22:25 UTC
Steps to reproduce: 
- Create a new piece of content with legacy relationships and/or relationship fields
- Add multilingual children (live and non-live) 

For Relationship Fields all flags load the default language and the non-live record is shown in gray (as if it were archived): 

![Screen Shot 2019-09-17 at 3.55.23 PM.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/63d209ef-ec8d-43d8-afcb-4584957c8562)

For Legacy Relationships the flag is not highlighted when the child is not published 

![Screen Shot 2019-09-17 at 4.02.10 PM.png](https://images.zenhubusercontent.com/5730f592bf93871ccd9ac00c/dbf71a0f-1edc-4a00-b9d3-ea128833f02b)

**Comment by nollymar** [comment] 2019-09-17 22:52
**Note to QA:** Please perform tests with archived related content too

**Comment by nollymar** [comment] 2019-09-17 22:56
PR: https://github.com/dotCMS/core/pull/17276

**Comment by erickgonzalez** [comment] 2019-09-19 16:00
After talking with @nollymar regarding the expected behavior, we agree that we need to discuss with @wezell about it. Showing the language flag even when there is no version of the content in that language.
<img width="1524" alt="Screen Shot 2019-09-19 at 9 30 44 AM" src="https://user-images.githubusercontent.com/5278970/65258690-90d58880-dac0-11e9-8912-07211a34dd53.png">

**Comment by erickgonzalez** [comment] 2019-09-20 17:03
After talking with Will this is fine. Should show the flag in grayscale when the content does not exist in the select lang or the content is archived. The status of the content is shown regardless of the lang.

For legacy relationships: the flag is shown in grayscale if the content does not exist in the lang or if the content is archived. If the content is unpublished or published the flag should be in color and around it the status color.

**Comment by bryanboza** [comment] 2019-09-24 19:20
We have a problem when you are using generic languages and we have no flag to show since we take this from the country code field. 

In the relationship field we can’t put the flag in color and then seems the content does not exist
SC: https://screencast.com/t/Puuc2yeyuR

FYI: This is happening in both relationships, legacy and the new field

**Comment by wezell** [comment] 2019-09-24 19:30
Fixed in this PR: #17348

**Comment by dsilvam** [comment] 2019-09-25 17:17
Passed Internal QA: After adding a new language and filling only the required fields, and then relating new content on that language, the related content shows the expected flag from both legacy relationships tab and new relationship field

![Sep-25-2019 12-13-19](https://user-images.githubusercontent.com/1576794/65623767-2758ec80-df8e-11e9-8f87-08a6d5a53de8.gif)

**Comment by bryanboza** [comment] 2019-09-26 21:54
Fixed, tested on master // Postgres // FF.

**Closed** 2019-09-27 18:32 UTC
Labels: Merged, Note to QA, Passed Internal QA, Passed QA, Release : 5.2.0, Type : Bug
