### ISSUE TITLE
PP error after push-delete, repush

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#19885] opened 2021-02-01 20:48 UTC
1. Create an htmlpage 
2. Push it to receiver
3. Push delete it
4. Re-push. 

This is the log on the receiver: 
```
[01/02/21 20:15:00:040 GMT] ERROR business.PublisherQueueJob: An error occurred when updating audit status from endpoint=[http://dotcms-auth:8080], bundle=[01EN5VV56BSEZHVYP1SPZ54EWC] : HTTP 404 Not Found
javax.ws.rs.NotFoundException: HTTP 404 Not Found
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1020) ~[jersey-client-2.25.1.jar:?]
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:819) ~[jersey-client-2.25.1.jar:?]
        at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92) ~[jersey-client-2.25.1.jar:?]
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701) ~[jersey-client-2.25.1.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444) ~[jersey-common-2.25.1.jar:?]
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697) ~[jersey-client-2.25.1.jar:?]
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:420) ~[jersey-client-2.25.1.jar:?]
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:316) ~[jersey-client-2.25.1.jar:?]
        at com.dotcms.publisher.business.PublisherQueueJob.getRemoteHistoryFromEndpoint(PublisherQueueJob.java:566) ~[dotcms_21.02_999999.jar:?]
        at com.dotcms.publisher.business.PublisherQueueJob.collectEndpointInfoFromRemote(PublisherQueueJob.java:277) ~[dotcms_21.02_999999.jar:?]
        at com.dotcms.publisher.business.PublisherQueueJob.updateAuditStatus(PublisherQueueJob.java:230) ~[dotcms_21.02_999999.jar:?]
        at com.dotcms.publisher.business.PublisherQueueJob.execute_aroundBody0(PublisherQueueJob.java:121) ~[dotcms_21.02_999999.jar:?]
        at com.dotcms.publisher.business.PublisherQueueJob$AjcClosure1.run(PublisherQueueJob.java:1) ~[dotcms_21.02_999999.jar:?]
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
        at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_21.02_999999.jar:?]
        at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_21.02_999999.jar:?]
        at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_21.02_999999.jar:?]
        at com.dotcms.publisher.business.PublisherQueueJob.execute(PublisherQueueJob.java:111) ~[dotcms_21.02_999999.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:223) ~[dot.quartz-all-1.8.6_2.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) ~[dot.quartz-all-1.8.6_2.jar:?]```

**Comment by bryanboza** [comment] 2021-02-08 20:56
Tested on the release branch and I'm unable to reproduce, we can close this one.

**Closed by bryanboza** 2021-02-08 20:56 UTC
Labels: Release : 21.02, Type : Bug, WF: Can't reproduce
