### ISSUE TITLE
Limited users cannot Bundle or Push Publish folders

### ISSUE THREAD

**Issue by jdcmsd** [dotCMS/core#24931] opened 2023-05-12 18:00 UTC
### Parent Issue

n/a

### Problem Statement

I'm unable to perform push publishing operations on folders when I can otherwise create them, edit them, push publish individual items contained in them, etc.

While attempting to add a folder to a bundle, I received this error:

![image](https://github.com/dotCMS/core/assets/102264829/3eca9dfe-0df7-457e-897b-5e5eee8ee76c)

I tried to push publish it directly, and a red `1` appeared on the modal when I hit `Push`, but nothing else happened.

![1](https://github.com/dotCMS/core/assets/102264829/644a1200-d3ef-4404-a02c-17eb5e11fb64)

I confirmed that my permissions should have been adequate to push the folder in question.

Finally, I tried making a brand new, empty `test` folder. I was unable to bundle or push it.

(Side note: I couldn't delete it, either; should limited users automatically get the ability to delete/permission content they themselves create? Probably worth a separate issue/discussion.)

### Steps to Reproduce

1. Sign in to Demo
2. Create a folder at the site root with the name `test-folder`
    ![image](https://github.com/dotCMS/core/assets/102264829/4a52476d-9ea8-4991-9a09-72b99f19fe06)
3. Grant full permissions to Contributors
    ![Screenshot 2023-05-12 at 1 21 59 PM](https://github.com/dotCMS/core/assets/102264829/4388f280-43bd-4c14-afb9-81bffe10caf4)
4. Login as "Chris Publisher"
    ![image](https://github.com/dotCMS/core/assets/102264829/9f4172e6-47d5-4d51-a00f-48ea5a7db8f0)
5. Go to the site browser, and view the folder:
    ![Screenshot 2023-05-12 at 1 26 18 PM](https://github.com/dotCMS/core/assets/102264829/396636a4-c306-45d5-a07b-aa4e5ceeda3a)
6. Attempt to add it to a bundle.*
    ![Screenshot 2023-05-12 at 1 21 14 PM](https://github.com/dotCMS/core/assets/102264829/7ff64bc6-37c2-4fbc-8638-40f07d9d734d)
7. See error.
    ![Screenshot 2023-05-12 at 1 22 29 PM](https://github.com/dotCMS/core/assets/102264829/d153cbeb-d70d-46fa-85b3-d58bee4747f6)
8. Attempt to push publish it.*
9. See error.
    ![2](https://github.com/dotCMS/core/assets/102264829/25c2a8ce-bae5-4169-ae34-1b39fa1fd42b)

* Note: This may require some basic PP configuration on Demo if none is in place already. At the time of testing, there does seem to be some sort of PP test target set up on Demo.

### Acceptance Criteria

Limited users should be able to push folders with permissions appropriate to their role.

### dotCMS Version

22.05

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/C028Z3R2D/p1683908683326199

**Comment by waqasakramdot** [comment] 2023-07-26 11:02
Customer is hitting this: https://dotcms.zendesk.com/agent/tickets/112619

**Comment by erickgonzalez** [comment] 2023-07-27 14:06
Dupe of https://github.com/dotCMS/core/issues/25371

**Closed by erickgonzalez** 2023-07-27 14:06 UTC
Labels: Type : Defect, Triage, Priority : 1 Show Stopper, OKR : Customer Support
