### ISSUE TITLE
Design System: Tags component has overflow

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#26081] opened 2023-09-13 17:55 UTC
### Parent Issue

Related to #25810 

### Problem Statement

We need some styling help here when you type long tags
![image](https://github.com/dotCMS/core/assets/2641437/5aed9e88-3cc5-4f0d-ab45-34614cfb7990)

Also when you are typing
![image](https://github.com/dotCMS/core/assets/2641437/527c6f9a-d8fc-4500-8dc8-6308b83d73fc)

Not sure if we need to add one tag by line @fmontes @Melissa-dotCMS
![image](https://github.com/dotCMS/core/assets/2641437/82f23d51-9a7d-4d34-a8cf-aaeeb231cadb)

Finally, in case you try to add a new key_tag that already exists we need to catch the exception and print just a line error in order to avoid noisy log
https://gist.github.com/bryanboza/4d43318f9bc953f2f334ca9e505be0e8

### Steps to Reproduce

- Login as admin 
- Open some page
- On edit mode try to add a new persona 

### Acceptance Criteria

We need to test every one of the mentioned cases above 

### dotCMS Version

Tested on master 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by rjvelazco** [comment] 2024-07-16 19:55
## Failed IQA

- Tested on docker: [`docker:trunk_ 430f4c7`]

### Steps to Reproduce

### Case 1: Close button barely visible

1. Go to the old page editor.
2. Open the `Add Persona Form`
3. Paste a long one-word text.
4. The longer the text is, the smaller the close button gets.

### Case 2: Text lost format

1. Go to the old page editor.
2. Open the `Add Persona Form`
3. Paste a long text with white space.
4. See the error.

### Video

https://github.com/user-attachments/assets/b202aed3-531e-44cb-9167-5ca309866ec3

**Comment by rjvelazco** [comment] 2024-07-26 14:57
## Failed IQA

- Tested on docker: [`docker:trunk_ 2c23184`]

### Video 

https://github.com/user-attachments/assets/4537f43c-779c-4e82-82dc-e3d27284aa07

**Comment by bryanboza** [comment] 2024-07-29 18:16
We need some work here: 

- We need to include this functionality in the UVE as soon as possible, since we are unable to access this form from the new editor.  However we still having issues with long tags here, If you try to add some basic tag it is working as expected, but when you try with a really log tag (something like 255 characters that is the limit) we still getting the same problem 

Tested using this tag:
```
Track the percentage of time the trunk is releasable and display it on the next 90-day data scorecard. Conduct mini-retros for escape defects and release blockers, understand blockers, log every trunk blockage to ensure smooth and efficient release cycles."

```

**Comment by fmontes** [comment] 2024-07-30 15:37
> We need to include this functionality in the UVE as soon as possible, since we are unable to access this form from the new editor
This is not a priority now, I will set this priority accordingly.


> 255 characters that is the limit
We can add `max-width` and ellipsis.

**Comment by zJaaal** [comment] 2024-08-08 17:59
I will change the title of this card since is misleading.

**Comment by dcolina** [comment] 2024-08-13 10:55
Internal QA: Needs work.

It was tested using the docker image `dotcms/dotcms:trunk_5205ee6` on Google Chrome as an incognito.

In the video below we can see how the Persona tags have the correct style, however we have noticed the tag length validation isn't working well. The error message says the maximum length for a tag is 255 character, but the real limit is under 200 characters. We have tested with:

- 150 characters (worked fine)
- 200 characters (failed)
- 199 characters (worked fine)



https://github.com/user-attachments/assets/dd896303-80e3-4fa6-9c42-a124f7c28804

**Comment by zJaaal** [comment] 2024-08-13 15:59
I created a card to check that out, since this card has almost 1 year opened and the issue that is being reported is out of scope, we wanted to solve style issues. 

https://github.com/dotCMS/core/issues/29559

cc: @dcolina

**Comment by dcolina** [comment] 2024-08-13 16:02
Internal QA: Passed.

As @zJaaal commented above the validation issue will be solved in another card. The one related to style is completed now.

**Closed by dcolina** 2024-08-13 16:02 UTC
Labels: Type : Defect, Merged, Team : Scout, QA : Failed Internal, NW Removed, Release : 24.07.30

**Comment by bryanboza** [comment] 2024-08-14 16:47
Fixed, now I'm unable to reproduce this problem since the tag style has been changed. 

Tested on the latest trunk // Docker // FF
