### ISSUE TITLE
Refactor: Migrate JobProcessor Discovery from Jandex to CDI

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#30545] opened 2024-11-01 14:55 UTC
### Parent Issue

https://github.com/dotCMS/core/issues/29474

## Overview
Replace the current Jandex-based JobProcessor discovery mechanism with a standard CDI-based approach to improve maintainability and align with Java EE standards.

## Current Implementation
The `JobProcessorScanner` class currently:
- Uses Jandex index to scan for `JobProcessor` implementations
- Requires manual class instantiation testing
- Needs explicit registration with `JobQueueManagerAPI`
- Depends on a static index file (META-INF/jandex.idx)

## Proposed Changes
1. Remove Jandex-based scanning mechanism
2. Convert JobProcessor implementations to CDI beans
3. Implement CDI-based discovery using `@Inject Instance<JobProcessor>`
4. Leverage CDI events for processor registration
5. Update `JobQueueHelper` to use CDI discovery

## Benefits
- Standard Java EE component discovery
- Automatic dependency injection
- Improved testability
- Better integration with existing CDI infrastructure
- Reduced manual error-prone operations
- More maintainable codebase

### Files to Modify
- `com.dotcms.jobs.business.api.JobProcessorScanner`
- `com.dotcms.jobs.business.api.JobProcessorFactory`
- `com.dotcms.jobs.business.processor.JobProcessor`
- `com.dotcms.rest.api.v1.job.JobQueueHelper`

### Implementation Steps
1. Add CDI qualifier annotations if needed for specific processor types
2. Update JobProcessor interface with appropriate CDI annotations
3. Modify JobQueueHelper to use CDI for processor discovery
4. Remove Jandex-specific code and dependencies
5. Update documentation
6. Add/update unit tests

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by fabrizzio-dotCMS** [comment] 2024-12-13 20:16
I confirmed that the discovery process no longer relies on the Jandex index. A new restriction has been introduced, requiring beans to have the “Dependent” scope, ensuring a unique and independent instance per job—which is reasonable.

However, this restriction introduces a validation step that throws an exception if a non-dependent bean is detected. This behavior disrupts the entire queue subsystem. Implementing a non-disruptive mechanism to log an exception when an unsuitable bean is marked as a Queue candidate would be highly beneficial. This would allow the system to report the issue while keeping the remaining valid queues functional and available.
Here some screenshots showing what it looks like when an invalid bean is found.
![Screenshot 2024-12-13 at 11 43 27 AM](https://github.com/user-attachments/assets/383f1e71-bc61-465d-99ee-605825491646)

**Comment by fabrizzio-dotCMS** [comment] 2024-12-23 18:40
I repeated the same exercise and this time the error was handled in a non-disruptive way:
 
```
18:22:22.042  ERROR api.JobProcessorDiscovery - JobProcessor com.dotcms.jobs.business.processor.impl.EchoLine must use @Dependent scope, found: javax.enterprise.context.ApplicationScoped scope. Won't be registered.
18:22:22.043  INFO  api.JobQueueManagerAPIImpl - Registering JobProcessor: com.dotcms.jobs.business.processor.impl.LargeFileReader
18:22:22.044  INFO  api.JobQueueManagerAPIImpl - Registering JobProcessor: com.dotcms.jobs.business.processor.impl.FailSuccessJob
18:22:22.044  INFO  api.JobQueueManagerAPIImpl - Registering JobProcessor: com.dotcms.jobs.business.processor.impl.ImportContentletsProcessor
18:22:22.045  INFO  api.JobQueueManagerAPIImpl - Starting JobQueue with 10 threads.

```

I can tell the other functionality remains working

**Closed by fabrizzio-dotCMS** 2024-12-23 18:40 UTC
Labels: Merged, QA : Passed Internal, Team : Scout, Triage, Type : Task, Next Release
