### ISSUE TITLE
Replace Alert(...) to an Angular Component/Service to show successfully when the user edits info in My Account

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#22276] opened 2022-05-23 18:41 UTC
**Is your feature request related to a problem? Please describe.**
As a user, when I switch to My Account, passing all validations and saving the form successfully, I get a browser's native `alert (...)` to show that the form was saved successfully.

**Describe the solution you'd like**
Create a shared reusable service to create(or reuse) a toast to inform the user.

**Describe alternatives you've considered**
use something like: https://www.primefaces.org/primeng/toast

**Additional context**
To Reproduce
- Login as an admin
- Go to My Account
- Type the current password and save a new one

![Screen Shot 2022-05-23 at 1.36.27 PM.png](https://images.zenhubusercontent.com/621e3b2d355dc73757435ad6/70738748-b962-4789-ad1e-639d507b2aa0)

**Comment by fabrizzio-dotCMS** [comment] 2022-07-12 15:15
I can confirm the old Alert has been replaced by a new dialog.

![Screen Shot 2022-07-12 at 09 07 40](https://user-images.githubusercontent.com/37148755/178524522-9be499d9-e989-442c-9715-51bfe37acc71.png)

**Comment by bryanboza** [comment] 2022-07-18 15:55
Fixed, tested on release-22.07 // Docker // FF

**Comment by bryanboza** [comment] 2022-07-29 16:44
We need to keep the My account modal open after you change the password, now we are showing a pop-up with the notification, but we need to go back to the same window after closing it.

**Comment by wezell** [comment] 2022-08-02 18:30
Can be done in a separate card.

**Comment by nollymar** [comment] 2022-08-02 19:10
New card: https://github.com/dotCMS/core/issues/22666

**Comment by bryanboza** [comment] 2022-08-02 20:12
Fixed, now we are showing the alert. New related card open in the issue #22666

**Comment by alfredo-dotcms** [comment] 2022-08-05 17:02
> We need to keep the My account modal open after you change the password, now we are showing a pop-up with the notification, but we need to go back to the same window after closing it.

this is a new requirement and not a bug, before doing this task My Account Modal closes after the alert so the behaviour is the same
https://monosnap.com/file/QgSG8S0BYmTtttY7W84ymU9MVa2NL2

**Closed** 2022-08-09 18:09 UTC
Labels: Type : Enhancement, Passed QA, Merged, Cat : UI, Passed Internal QA, Team: Scout, Release : 22.08
