### ISSUE TITLE
Blurrier Images as resultant of Using "Resize" and "Crop" together in Image processing api

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#24044] opened 2023-02-06 17:10 UTC
### Problem Statement

When Reize and crop filters are used together the resulting image is slightly blurry.  This can be more problematic, depending on how much larger the working source image is.

### Steps to Reproduce

By using the aforementioned "Resize" and "Crop" filters together to process an image, the resulting images are more blurry than expected. An example set of images from the demo site will be provided below. For the easiest way to compare, open each image in a separate tab, and switch between them. You will see that, despite being identical in size, one is more blurry than the other:

Resize only: https://demo.dotcms.com/contentAsset/image/d331052e-8220-42d8-a4e4-3ea80e088123/fileAsset/filter/Resize,Crop/resize_w/1280
Resize + Crop: https://demo.dotcms.com/contentAsset/image/d331052e-8220-42d8-a4e4-3ea80e088123/fileAsset/filter/Resize,Crop/resize_w/1330/crop_w/1280/crop_h/467/fp/0.5,0.5

### Acceptance Criteria

Image processing API should resize and crop images without compromising image quality

### dotCMS Version

23.01

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/109916

**Comment by swicken-dotcms** [comment] 2023-09-14 20:18
This is a dupe of https://github.com/dotCMS/core/issues/25193, which is resolved

**Closed by swicken-dotcms** 2023-09-14 20:18 UTC
Labels: Type : Defect, OKR : Customer Support
