### ISSUE TITLE
Pushing sites from within the sites folder fails 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#28473] opened 2024-05-07 23:22 UTC
### Problem Statement

if you're working with sites and you cd  into the sites folder make some changes and then call the global push from within the sites folder an error occurs like :

```
fabrizzioaraya@Fabrizzios-MacBook-Pro sites % dot push
/
 ──────
 No changes in Languages to push


|
 ──────
 Push Data: [1] Sites to push: (0 New - 1 Modified)


-███████████████████████████████████████████████████████████████████████████████████████████████████  100%
 ──────
 No changes in ContentTypes to push


[ERROR] ❗  Error in command [push] with message:
  Invalid source path. Source path must be inside the files folder or at the root of the workspace
run with -e or --errors for full details on the exception.
```

### Steps to Reproduce

 cd  into the  workspace/sites folder make some changes to any of the site json files Maybe add a site variable as 

```
{
  "dotCMSObjectType" : "Site",
  "inode" : "2ba7223d-4b9a-4f33-b7d5-fa3e782ecb84",
  "identifier" : "8a7d5e23-da1e-420a-b4f0-471e7da8ea2d",
  "aliases" : null,
  "systemHost" : false,
  "siteName" : "default",
  "tagStorage" : "8a7d5e23-da1e-420a-b4f0-471e7da8ea2d",
  "siteThumbnail" : "",
  "runDashboard" : false,
  "keywords" : null,
  "description" : null,
  "googleMap" : null,
  "googleAnalytics" : null,
  "addThis" : null,
  "proxyUrlForEditMode" : null,
  "embeddedDashboard" : null,
  "languageId" : 1,
  "variables" : [ {
    "name" : "foo",
    "key" : "bar",
    "value" : "bar"
  } ],
  "modDate" : "2024-05-07T23:14:21.802+00:00",
  "modUser" : "dotcms.org.1",
  "live" : true,
  "default" : true,
  "locked" : true,
  "archived" : false,
  "working" : true
}
```

    then call the global push from within the sites folder as follows 

user@user-MacBook-Pro sites % dot push

### Acceptance Criteria

We should be able to call global any operation from with any folder within the workspace and the command should be able to find its way within the workspace 

### dotCMS Version

master

### Proposed Objective

Customer Success

### Proposed Priority

Priority 3 - Average

**Comment by fabrizzio-dotCMS** [comment] 2024-08-08 16:29
I think the changes introduced to improve handling relative paths 
[here](https://github.com/dotCMS/core/issues/28593)  could have fixed this problem

**Comment by jgambarios** [comment] 2024-08-08 21:35
**Note to QA:**

As Fabrizzio already mentioned, this was fixed in https://github.com/dotCMS/core/issues/28593
Passed Internal QA as I was unable to reproduce the issue.

**Closed** 2024-08-08 21:35 UTC
Labels: Type : Defect, QA : Passed Internal, Team : Scout, dotCMS : CLI

**Comment by bryanboza** [comment] 2024-08-12 23:19
Fixed unable to reproduce after the fix mentioned in the thread. 

Tested on the last CLI // Docker
