### ISSUE TITLE
Self related content cannot be saved using Content REST API

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#17492] opened 2019-10-18 17:15 UTC
Reported via Support: Ticket [99492](https://dotcms.zendesk.com/agent/tickets/99492)
Reproducible in dotCMS 5.2.0

When saving a content item using Content API, for a content type that has a self-joined relationship, two different fields can be populated to save related content for that relationship: the first field can be used to saved children items, and the second field to save parent items. However, dotCMS only saves the related content included in the first field, the second field is skipped.

### Steps to reproduce the behavior:
1. Create a content type with a couple of fields, for example 'My Collection'.
2. Add a relationship field to the content type to create a one-to-many relationship from the content type to itself. For example, name the field as 'childrenCollections'.
3. A another field to the content type to represent the other side of the relationship. For example, name the field as 'parentCollection'.
4. Add some content items for the content type using UI or REST API, for example add items A,B,C,D.
5. Send a request to dotCMS Content REST API to save a new content item. Include both fields for the self-joined relationship, to save related content in both sided of the relationship for the item. For example:
```
{
  "stName": "MyCollection",
  "contentHost":"demo.dotcms.com",
  "collectionId": "E",
  "collectionName" : "Collection E",
  "childrenCollections" : "c6c72761-1d04-493a-8f45-deac8ad4fef6,a735438b-5a06-4cc1-a91b-c4e4fe896bdd",
  "parentCollection" :  "0b445ff9-2374-4220-8983-2fceade1b9cf"
}
```
6. Check the content item added in the previous step. It only saved the related content for the first field ('childrenCollections') but didn't save the related content for the second field ('parentCollection').

### Expected behavior
Related content should be saved for both fields from the self-joined relationship.

### Screenshots
Added relationship field to create self-joined relationship:
![image](https://user-images.githubusercontent.com/2894221/67114094-5b43be00-f198-11e9-8127-f623dc4ed2b6.png)

Added relationship field pointing the other side of the self-joined relationship:
![image](https://user-images.githubusercontent.com/2894221/67114140-73b3d880-f198-11e9-8fa7-1a068e9771b4.png)

Result after saving content item via REST API: only the related content from the first field was saved:
![image](https://user-images.githubusercontent.com/2894221/67114173-8dedb680-f198-11e9-8fe8-4cc643364793.png)

### Additional context
This has been reported by customer via Support: Ticket [99492](https://dotcms.zendesk.com/agent/tickets/99492)

**Comment by wezell** [comment] 2019-10-18 17:22
Related or dupe of #17477

**Comment by nollymar** [comment] 2019-10-21 19:48
Fixed. PR: https://github.com/dotCMS/core/pull/17499/files

**Comment by nollymar** [comment] 2019-10-21 22:08
**Note to QA:** Please test the following functionalities with self-relationships: 
- Save Content using the rest api
- Save as Draft using the rest api
- Push Publishing

**Comment by erickgonzalez** [comment] 2019-10-24 21:33
Tested against release-5.2.1. 
We have an issue when using the Workflow endpoint `/api/v1/workflow/actions/default/fire/PUBLISH` we are using a wrong checkin method and make the call fail. After talking with @jdotcms we found a workaround that is adding the **Publish** action to the **New** Step and check **New** on **Show When**. Issue Reported Here: https://github.com/dotCMS/core/issues/17529

If you use the Content endpoint `/api/content/newpublish/1` works without issues and without the need of any workaround.

**Comment by nollymar** [comment] 2019-10-24 22:07
We might be losing categories when the Workflow endpoint is used. Please, consider this case for your tests @erickgonzalez . I think it might affect content dependencies in general, not just relationships

**Comment by erickgonzalez** [comment] 2019-10-30 21:53
Tested on master and release-5.2.1. WorkflowResource endpoint creates successfully content with relationships and respects each field.

**Closed** 2019-11-18 18:08 UTC
Labels: Cat : Rest API, Changelog, Merged, Merged Release, Note to QA, Passed Internal QA, Passed Internal QA Release, Release : 5.2.1, Severity : Support Requested, Type : Bug

**Comment by bryanboza** [comment] 2019-11-20 22:00
Fixed, tested on master
