### ISSUE TITLE
Create actionlet Save Content and Save Content as Draft

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#13320] opened 2018-01-05 20:18 UTC
Save Content and Save Content as Draft

## Expected Behavior
Save Content has to do a commit and Save Content as Draft has to do a checkinNoVersion
## Current Behavior
Do not exists

**Comment by wezell** [comment] 2018-01-05 20:26
You will need to set some flag so that the save actionlet cannot be called recursively.

**Comment by jgambarios** [comment] 2018-01-12 18:43
PR: https://github.com/dotCMS/core/pull/13383

**Comment by bryanboza** [comment] 2018-01-19 16:17
After test this functionality we have some weird behaviors 

- [ ] We do double checking here, then we are creating two new versions of the content 
SC: https://screencast.com/t/K9qWXGIM

- [ ] Error after execute the save as draft action 
SC: https://screencast.com/t/iRo6WhtyqUMP

- [ ] We are changing the top version when you execute the save as draft 
SC: https://screencast.com/t/z1PBK1xXG
_The idea of the draft is just create a new version of the content but without change the top version_

**Comment by jgambarios** [comment] 2018-02-01 17:03
PR: https://github.com/dotCMS/core/pull/13533

**Comment by bryanboza** [comment] 2018-02-02 18:48
New errors on this actions
- Save Content: https://gist.github.com/bryanboza/869ee5c0110988e933c6186e8bfef4e6

**Comment by bryanboza** [comment] 2018-02-07 21:22
Since this is a new feature in the system, I am based in the specs to test.  

The main difference between the Save & Save as Draft is: 

**Save:** Saves a new version of the content (with no conditions).
**Save as Draft:** If the user taking the action is a different user than the last user who saved the content, then it saves a new version of the content; otherwise (if it's the same user), it saves the changes but does *not* create a new version (it just overwrites the most recent version).
So Save as Draft is a new thing that allows the same user to save the content multiple times without creating multiple versions.

Right now the Save is working fine, but have problems with the Save as Draft

- [ ] When you have a live content, and edit it, and you try to save as draft, the first time we are creating a new working version. (That's ok too)

- [ ] After that you can edit multiple times the same version, and if you  continue saving as draft, the system overwrites the same version. (That's ok)

- [ ] **But if you try to edit the same content as a different user, We get the draft version, not the live one, also if you edit something and save this as draft, we are not creating a new version to this user, we just overwrite the draft of the other user.**

**Comment by bryanboza** [comment] 2018-02-07 21:23
@wezell and @john-thomas-dotcms
 
Please take look of this comment, to make sure I'm not wrong, this based in the last time we talk about it

**Comment by jgambarios** [comment] 2018-02-08 17:08
PR: https://github.com/dotCMS/core/pull/13597

**Comment by bryanboza** [comment] 2018-02-08 22:09
New error with the file asset structure when you try to create a draft of multi-language content 
Error:  https://gist.github.com/bryanboza/437d35df535d2b05414aa98187235143
SC:  https://screencast.com/t/8rL3HjVyhp

To recreate: 
- Create a new workflow 
- Create two actions with the sub-actions "save" and "save as draft" 
- Assign this workflow to the file asset content type
- Upload a new file asset and save and publish
- Edit the file and execute the "Save" action
- Now execute the save as draft

**Comment by jgambarios** [comment] 2018-03-08 20:41
Unable to reproduce

**Comment by bryanboza** [comment] 2018-03-12 21:47
After talk with @jdotcms now he is able to reproduce the problem

**Comment by jgambarios** [comment] 2018-03-21 17:34
PR: https://github.com/dotCMS/core/pull/13921

**Comment by bryanboza** [comment] 2018-03-26 23:21
Fixed, tested in the last master and now I am unable to recreate this problems

**Closed** 2018-04-10 20:35 UTC
Labels: Doc : Needs Doc, WF : Merged, WF : Passed QA
