### ISSUE TITLE
Copying Content does not copy its relationships

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#7661] opened 2015-04-27 20:13 UTC
If you copy a piece of content with relationships, the relationships are lost on the copied piece of content.

Tested on demo.dotcms.com running 3.2.

**Comment by rogelio-blanco** [comment] 2015-05-15 16:27
I did a test, however I was not able to reproduce it.

Could you please include the steps to reproduce the issue?

**Comment by levosgien** [comment] 2015-05-15 17:56
I can't reproduce anymore, let's resolve this I can't remember what I did last time.

**Comment by oarrietadotcms** [comment] 2015-05-15 17:57
Closing this one as not reproducible.

**Closed** 2015-05-15 17:57 UTC
Labels: Cat : Content Management, Type : bug
