### ISSUE TITLE
Unable to deploy hotfix

### ISSUE THREAD

**Issue by shayngr** [dotCMS/core#7832] opened 2015-06-09 17:37 UTC
Unable perform a successful deploy-plugin of hotfix-leonteq-4

Tested on:  3.2 Nightly build 2015-06-05 22:40/ Ubuntu 14.04 // Postgres // Firefox

Log:
BUILD FAILED
/Users/shayng/Desktop/dotcms-3.2/bin/ant/build.xml:585: The following error occurred while executing this line:
/Users/shayng/Desktop/dotcms-3.2/bin/ant/build.xml:563: The following error occurred while executing this line:
/Users/shayng/Desktop/dotcms-3.2/plugins/common.xml:59: Class not found: javac1.7

**Comment by erickgonzalez** [comment] 2015-06-09 17:40
Jonathan and I found the fix for this issue is to change the compiler in the common.xml in the plugins directory.

This:
<javac debug="true" debuglevel="lines,vars,source" fork="true" srcdir="${src.dir}" destdir="${build.classes}" source="1.7" target="1.7" compiler="modern" nowarn="true" optimize="true" memoryinitialsize="256m" memorymaximumsize="512m">

Instead of this:
<javac debug="true" debuglevel="lines,vars,source" fork="true" srcdir="${src.dir}" destdir="${build.classes}" source="1.7" target="1.7" compiler="javac1.7" nowarn="true" optimize="true" memoryinitialsize="256m" memorymaximumsize="512m">

**Comment by jgambarios** [comment] 2015-06-09 17:48
The issue is when a static plugin have code to compile under the **src** folder, as Erick explained one workaround is to change the ```compiler="javac1.7"``` to ```compiler="modern"```.

**Comment by jtesser** [comment] 2015-06-09 18:22
this is fixed already in 3.2.1

**Comment by jtesser** [comment] 2015-06-11 14:10
OK so we need to add the compiler="modern" as deploy plugins in the distro uses an older ANT and this fails without the modern flag

**Closed** 2015-06-11 14:23 UTC
Labels: Merged, Type : bug, WF : Needs QA

**Comment by bryanboza** [comment] 2015-06-16 17:20
Fixed, testen in the 3.2.1 release...
