### ISSUE TITLE
Download link on file assets not working - 5.2.8

### ISSUE THREAD

**Issue by craigWagner99** [dotCMS/core#18561] opened 2020-05-28 17:49 UTC
From Zendesk ticket: https://dotcms.zendesk.com/agent/tickets/101462 

When you open a File Asset in the admin tool, the Download link is non-functional.

### Steps to reproduce the behavior:
1. Upload a file asset
2. Open it to view details.
3. Click 'Download"
4. Nothing happens.

### Expected behavior
Clicking the link should download the file. It does not. 

The code on the link is:

`<a class="bg" href="javascript: serveFile('','89b5a88e-4be8-45fd-8195-912b74359872','fileAsset');" id="fileAssetBinaryFile">Download</a>`

### Screenshots

![image](https://user-images.githubusercontent.com/49727631/83175445-848adc00-a0e1-11ea-930d-bf3fccf8d79d.png)

### Desktop (please complete the following information):
 - OS:n/a
 - Browser FF/Chrome

**Comment by wezell** [comment] 2020-06-16 15:18
We need to set <%PageMode.PREVIEW_MODE%> in the edit contentlet jsp

**Comment by wezell** [comment] 2020-06-16 15:20
PR: #18561

**Comment by fmontes** [comment] 2020-06-17 15:39
NEW PR: https://github.com/dotCMS/core/pull/18677/files

**Comment by fmontes** [comment] 2020-06-17 15:40
NEW PR: https://github.com/dotCMS/core/pull/18677/files

**Comment by bryanboza** [comment] 2020-06-17 19:57
After the discussion in the #lunik channel we need to add a `?force_download=true` in order to have a download directly instead open in a new window

**Comment by fmontes** [comment] 2020-06-18 16:17
PR: https://github.com/dotCMS/core/pull/18696

**Comment by bryanboza** [comment] 2020-06-19 22:03
We need some work here, still failing after the changes: 
SC: https://www.screencast.com/t/ZgCSebtH

**Comment by bryanboza** [comment] 2020-06-24 22:42
Please check the merge in to the release branch, still having the same results

**Comment by fmontes** [comment] 2020-06-25 21:01
Is merged in the release branch: https://github.com/dotCMS/core/pull/18753/files and I just retested and working.

**Comment by bryanboza** [comment] 2020-06-25 22:50
We have different behaviors here, depending the extension of the file, if you try with a s.css that comes in the full starter we still having the same behavior, if you try with an image or something like that, we are forcing the download. 

![image](https://user-images.githubusercontent.com/2641437/85803127-bfddf200-b703-11ea-9411-dd72ed917eb8.png)


We need the same behavior to all the files. Tested with a .vtl file and I'm unable to download.

**Comment by bryanboza** [comment] 2020-06-26 23:37
Seems the problem is related to FF.

**Comment by bryanboza** [comment] 2020-06-29 18:56
Fixed, tested on FF and now works as expected

**Closed** 2020-06-29 22:12 UTC
Labels: Cat : Content Management, Merged, Passed QA, Release : 5.3.3, Severity : Support Requested, Type : Bug
