### ISSUE TITLE
$workflow.abortProcessor() does not stop subsequent subactions from firing

### ISSUE THREAD

**Issue by swicken-dotcms** [dotCMS/core#21251] opened 2021-11-08 14:53 UTC
**Describe the bug**
Calling `$workflow.abortProcessor()` does not stop subsequent subactions from firing.

This is how it should function, per our documentation: https://dotcms.com/docs/latest/custom-workflow-actions#Example

Ticket: https://dotcms.zendesk.com/agent/tickets/105648
Reproduced on: 5.2.8.4, 21.10

**To Reproduce**
1. On any workfllow action create a velocity script actionlet. Make sure it is ahead of other subactions
2. Make the code for this actionlet only `$workflow.abortProcessor()` 
3. Fire this workflow action, the subsequent subactions will still fire. 

**Expected behavior**
`$workflowtool.abortProcessor()` should stop all processing at that point, including subsequent subactions.

**Comment by jcastro-dotcms** [comment] 2021-11-10 19:14
Closing ticket as it is a dupe of ticket #21252

**Closed by jcastro-dotcms** 2021-11-10 19:14 UTC
Labels: Type : Bug, Cat : Workflow, Severity : Support Requested, Cat : Viewtools
