### ISSUE TITLE
Unable to import categories 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#23389] opened 2022-11-17 18:37 UTC
When you have a categories backup, we are unable to import this CSV file. We are getting an error and we can't import 

Here is the stack: https://gist.github.com/bryanboza/4e584b5e1e6ff681cfcdfe4f7f9b1019

### To Reproduce
- In a running instance, create some categories 
- Export the categories in a csv file 
- Delete the categories from your instance 
- Try to import the backup 

### Expected behavior
We need to be able to import this file without errors 

### Desktop (please complete the following information):
Tested on release-22.11 // Docker

**Comment by swicken-dotcms** [comment] 2023-10-04 16:24
Dupe of https://github.com/dotCMS/core/issues/25653 (keeping newer one as its now customer impact)

**Closed by swicken-dotcms** 2023-10-04 16:24 UTC
Labels: Type : Defect, OKR : Customer Support
