### ISSUE TITLE
Log viewer : highlight and filter

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21848] opened 2022-03-14 15:52 UTC
When using the log viewer in dotCMS, customers often want to be able to filter the lines by a specific string.  We should give people a "search" textbox that they can enter a string to highlight and a "filter" checkbox that that will filter any new messages for the presence of that string.

When a user enters a string to filter by, we find and replace matches of that string with highlighted version of it.  The highlight should happen on keyup if the search String has a length of >=3.  We will need to debounce onkeyup for like a second so we are not going crazy when a user is typing.   Then, when a new message is printed, we should check for that string's presence and highlight that text as well.

If the user hits enter with a filter entered, we should hide the non-matching lines and only print new lines that match the filter.

**Comment by wezell** [comment] 2022-03-22 18:39
1. We need to execute the filter in the native jsp.
2. Let's make the background black and the font white or off-white - like 225, 225, 225
3. Resize the iframe window to fit its bounding box - full height.

**Comment by alfredo-dotcms** [comment] 2022-03-28 21:09
PR: https://github.com/dotCMS/core/pull/21911/files

**Comment by alfredo-dotcms** [comment] 2022-03-31 20:41
PR: https://github.com/dotCMS/core/pull/21933/files

**Comment by fabrizzio-dotCMS** [comment] 2022-05-20 19:46
Noticed a 2 things here: 

1. We don't have a **filter** checkbox to do this
   `If the user checks the "filter" checkbox, we should hide the non-matching lines and only print new lines that match the filter.` We're only doing the highlighting 
2. The filter is applied to strings of length greater than or equal to 2. It says it must be of length 3.

**Comment by alfredo-dotcms** [comment] 2022-05-20 21:54
@wezell question for you:

Fabrizzio, did qa and follows your description, but on *point 1*, do you really think a CHECKBOX is needed to demostrate/show what the user can do by pressing ENTER? (IMO it's making the user do an extra step and it's not needed)

![image](https://user-images.githubusercontent.com/37185433/169617495-821dcaa0-894f-4d9e-bd59-9c77e6e81e26.png)


after pressing ENTER (this is what the CHECKBOX missing will also do)

![image](https://user-images.githubusercontent.com/37185433/169617521-fdb515d1-05e7-4587-bcd7-97ae3f1da0b4.png)

**Comment by alfredo-dotcms** [comment] 2022-05-23 17:06
PR: https://github.com/dotCMS/core/pull/22275

**Comment by bryanboza** [comment] 2022-05-27 17:49
We have a weird case here that seems to be a race condition, if you filter something this is working as expected, but if you clear the filter type another word and hit enter quickly, we are including another filter over the existing one, instead to clear everything and filter again 

https://user-images.githubusercontent.com/2641437/170764070-22d12464-c3d2-4363-bedf-64188c18896a.mov

**Comment by alfredo-dotcms** [comment] 2022-06-01 23:02
PR: https://github.com/dotCMS/core/pull/22341/files

**Comment by nollymar** [comment] 2022-06-06 21:23
**Internal QA:** The race condition is now fixed. Passed.

**Comment by bryanboza** [comment] 2022-06-07 16:35
We need some work here, after the fix after pressing any key we are restarting the filter, which is not the expected behavior and can be confusing
https://user-images.githubusercontent.com/2641437/172435028-292f5d2d-38ce-4d93-b5f9-73bcd4f30fdf.mov

**Comment by alfredo-dotcms** [comment] 2022-06-08 15:31
PR: https://github.com/dotCMS/core/pull/22369/files

**Comment by nollymar** [comment] 2022-06-13 16:13
**Internal QA:** Needs work

Now, the highlight disappears when I use the arrow keys: 


https://user-images.githubusercontent.com/8741395/173397821-73687a0c-be81-4221-ba1a-7ce500cd730a.mov

**Comment by nollymar** [comment] 2022-06-13 17:25
New fix: https://github.com/dotCMS/core/pull/22398

**Comment by alfredo-dotcms** [comment] 2022-06-13 17:25
PR: https://github.com/dotCMS/core/pull/22398/files

**Comment by nollymar** [comment] 2022-06-13 21:38
**Internal QA:** Passed

**Closed** 2022-06-15 20:14 UTC
Labels: Type : Enhancement, Passed QA, Merged, Cat : UI, Passed Internal QA, Team: Scout, Release : 22.06
