### ISSUE TITLE
Implement UI changes to Experiment Configurations

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#23968] opened 2023-01-31 21:18 UTC
### Parent Issue

https://github.com/dotCMS/core/issues/23612

### Task

Standardize the buttons of the UI, implementing the final design.

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

<img width="1030" alt="Screenshot 2023-01-31 at 4 15 59 PM" src="https://user-images.githubusercontent.com/1909643/215885056-33afb956-d19e-4c6d-9e22-9226ec366e1f.png">

**Comment by john-thomas-dotcms** [comment] 2024-03-07 19:50
Duplicate of https://github.com/dotCMS/core/issues/27122

**Closed by john-thomas-dotcms** 2024-03-07 19:50 UTC
Labels: Team : Falcon, dotCMS : Experiments, Type : Task
