### ISSUE TITLE
Visibility of Delete Button on Content Types Portlet in Community Edition

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#29473] opened 2024-08-06 20:43 UTC
### Problem Statement

In the Community Edition of the content management system, users have reported that the delete button is not visible on the content types portlet. This issue prevents users from deleting unwanted or obsolete content types, impacting their ability to manage content effectively.
https://github.com/user-attachments/assets/f4e7fc0b-4afa-4f8f-95c3-69b9c63cffd5

### Steps to Reproduce

- Log into the backend using the Community Edition.
- Navigate to the content types portlet.
- Attempt to locate the delete button for any content type.
- Observe that the delete button is not visible, preventing the deletion of content types.

### Acceptance Criteria

- **Visible Delete Button:** Ensure that the delete button is visible and accessible on the content types portlet in the Community Edition.
- **Consistent Behavior:** The delete button should function consistently across different content types, allowing users to delete content types as needed.
- **User Feedback:** Provide feedback or confirmation when a content type is successfully deleted.

### dotCMS Version

Tested on trunk // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by dcolina** [comment] 2024-08-12 19:00
Internal QA: Needs work.

The initial issue was fixed, because the word `delete` is shown but in the wrong way. 

![Image](https://github.com/user-attachments/assets/003638e5-4dbb-4e20-8de1-630867501094)

You can see more detail in the following video.

https://github.com/user-attachments/assets/b19431d0-a1f0-4772-9526-1395a6566110

**Comment by zJaaal** [comment] 2024-08-12 19:08
@dcolina 
The issue you are showing is related to the main issue and I'm not able to reproduce this issue anymore. Would it be Browser cache?


https://github.com/user-attachments/assets/b862d1a5-93f1-4a4d-9de0-5d0d68165e2f

**Comment by dcolina** [comment] 2024-08-13 09:31
@zJaaal I was using the docker image `[dotcms/dotcms:trunk]` and Google Chrome browser as an incognito. I have retested this time with the same docker image you have used  `[dotcms/dotcms: trunk_5205ee6]` and Google Chrome browser as an incognito as well.

This time I noticed that the delete icon is shown right (as expected), but I think the alt (tooltip) is missing of some style. This behavior is shown in the video below:

 
https://github.com/user-attachments/assets/9676a739-5c57-4b61-b896-c72681d0a156

**Comment by zJaaal** [comment] 2024-08-13 13:37
Hello @dcolina I was looking into that and I found out that it is a PrimeNG Issue which is the library we use for our UI Components https://github.com/primefaces/primeng/issues/13169 

We are currently on the same version that the issue is being reported but we have a PR to update the version of the library https://github.com/dotCMS/core/pull/29057

I would say that we should wait for that to merge and see if it was fixed, since it is a bug inside the library itself.

**Comment by dcolina** [comment] 2024-08-13 14:15
As @zJaaal commented above the responsive behavior is going to be fixed in #29057.

Internal QA: Passed.

**Closed by dcolina** 2024-08-13 14:15 UTC
Labels: Type : Defect, Merged, Team : Scout, Triage, QA : Failed Internal, NW Removed

**Comment by bryanboza** [comment] 2024-08-13 22:50
Fixed, tested on trunk_761ef08 // Docker // FF
