### ISSUE TITLE
?language_id in url and immediate 500. In any server

### ISSUE THREAD

**Issue by monzonj** [dotCMS/core#8557] opened 2016-02-02 14:19 UTC
http://demo.dotcms.com/?language_id=1/0

error 500. Division by 0. Should be correctly catch. It's ok to log it (I wouldn't log it with a full stacktrace, but ok) but a 500 error page?? that's too bad.

```
2016-02-02 15:11:03,689 ERROR com.dotmarketing.portlets.languagesmanager.business.LanguageFactoryImpl - getLanguage failed passed id is not numeric. Value from parameter: 4/en
java.lang.NumberFormatException: For input string: "4/en"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.parseLong(Long.java:631)
        at com.dotmarketing.portlets.languagesmanager.business.LanguageFactoryImpl.getLanguage(LanguageFactoryImpl.java:93)
        at com.dotmarketing.portlets.languagesmanager.business.LanguageAPIImpl.getLanguage(LanguageAPIImpl.java:46)
        at com.dotmarketing.business.web.LanguageWebAPIImpl.checkSessionLoc
ale(LanguageWebAPIImpl.java:59)
        at com.dotmarketing.business.web.LanguageWebAPIImpl.getLanguage(LanguageWebAPIImpl.java:119)
        at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:59)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:33)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:146)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by dsilvam** [comment] 2016-02-02 14:25
Duplicate of https://github.com/dotCMS/core/issues/8388.
Hotfixed for 3.2.4

**Comment by brentgriffin** [comment] 2016-02-02 14:49
Just tested in master-3.5 and it is still broken - must need to merge in the hotfix changes

**Comment by dsilvam** [comment] 2016-02-02 15:20
I closed it because there is already another opened github issue for the same problem

**Comment by brentgriffin** [comment] 2016-02-02 16:02
right - my bad - it is a duplicate of #8388 as you said above

**Closed by brentgriffin** 2016-02-02 16:02 UTC
Labels: Agile:Discuss for Release
