### ISSUE TITLE
Values for a Rule conditionlet do not display when you return to the rule

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20761] opened 2021-08-04 14:29 UTC
If you setup a rule and use a conditionlet such as "Request Headers" and set the values, all is good.

After doing this, if you browse around the admin and then return to the rule, the conditionlet does not always show the set values.  This is what you see instead:

![Screen Shot 2021-08-04 at 10 28 36 AM](https://user-images.githubusercontent.com/934364/128199107-c107a443-4245-4238-8736-92f741698994.png)

**Comment by wezell** [comment] 2021-08-04 16:27
Additional issue - if you have an option group that has both a key and a value, we are saving the key and not the value.

**Comment by alfredo-dotcms** [comment] 2021-08-09 20:27
unable to reproduce
https://monosnap.com/file/lKlgg0mLlDW4VfkDT1QSnxiGL0xZ1c

**Comment by nollymar** [comment] 2021-08-10 16:31
**Internal QA:** I was not able to reproduce the issue either

**Comment by bryanboza** [comment] 2021-08-19 16:57
Fixed, tested on release-21.09 using docker and FF & Chrome and I'm unable to reproduce. I'll close this card

**Closed** 2021-08-24 19:07 UTC
Labels: Type : Bug, Passed QA, WF: Can't reproduce, Passed Internal QA, Release : 21.09
