### ISSUE TITLE
[Templates] : History tab in Templates portlet not working as expected

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#23409] opened 2022-11-21 21:15 UTC
Reproducible in our Demo Site (22.10.1) and latest master.

### Describe the bug
If you have several versions of your Template, and need to go back to a previous one, all links in the `History` tab point to the `System Template`.

### To Reproduce
1. Go to `Site > Templates > Click the 'Add' button` and create an Advanced Template.
2. After saving it, publish it from the `Templates` portlet.
3. Change the HTML code in your Template about 3 times in order to get 3 different versions of it.
4. Go to the `History` tab and notice the following:
4.1. There's no `Bring Back` link for you to be able to go back to a given version.
4.2. If you click any version in the list, you'll be taken to the `System Template` instead.

### Expected behavior
The `History` tab should work as expected.

### Acceptance criteria

- [ ] The `Bring Back` link must be present.
- [ ] Clicking a specific previous version of a Template must take you to that version.

**Comment by erickgonzalez** [comment] 2022-11-21 22:10
dupe of https://github.com/dotCMS/core/issues/23366

**Closed** 2022-12-07 23:54 UTC
Labels: Type : Bug, Cat : Content Management
