### ISSUE TITLE
Edit Mode Should Always be "Default" Size

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#26258] opened 2023-09-25 17:16 UTC
[![Screenshot_2023-09-25_17-16-20.png](https://mrkr.io/s/6511c0645edebaae4376c13b/2)](https://mrkr.io/s/6511c0645edebaae4376c13b/0)

### Parent Issue

https://github.com/dotCMS/core/issues/24862

### Problem Statement

We want to get rid of the concept of "editing mobile" so any time someone hits edit they should be taken to the default edit view.

Currently the default devices work this way, but custom devices still take the user to the "mobile" view when editing.

<img width="1037" alt="Pasted_Image_9_25_23__12_13_PM" src="https://github.com/dotCMS/core/assets/114953617/c6009751-f900-40a0-83fb-e3b7fcd8c93a">

### Steps to Reproduce

From the Preview Menu, open one of the site-defined device sizes, then click edit.

Note how the behavior should be the same as if you click on of the predefined sizes, then hit edit.

https://github.com/dotCMS/core/assets/114953617/3e3efcb5-6c77-4172-aec2-6860d7e9a0c3

### Sub-Tasks & Estimates

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fdestinations%2Fcolorado&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797](https://dotcms-qa-master.dotcms.site/dotAdmin/#/edit-page/content?url=%2Fdestinations%2Fcolorado&language_id=1&host_id=48190c8c-42c4-46af-8d1a-0cd5db894797)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6511c0645edebaae4376c13e_63e51b12f50c98ab?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 117.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 1172</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by nollymar** [comment] 2023-10-04 17:03
Dupe of: #25278

**Closed by nollymar** 2023-10-04 17:03 UTC
Labels: Type : Defect, Team : Scout
