### ISSUE TITLE
Homologate chained Error messages in Pull and Push 

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#27796] opened 2024-03-01 18:03 UTC
### Parent Issue

https://github.com/dotCMS/core/issues/27386

### Problem Statement

due to the recent changes introduced to fix the limited user problem certain inconsistencies were introduced in how chained Error messages are displayed between Global pull and push. 

We need to homologate the way they both look.

### Steps to Reproduce

It is tough to create such a scenario. 
For the pull to show exceptions try pulling everything down then switch to a restricted user and do another pull
Then Run a Push also using the restricted user. 

### Acceptance Criteria

Error messages should be displayed using the same fashion by both PULL & PUSH 

### dotCMS Version

current master 

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

**Comment by wezell** [comment] 2024-03-04 15:57
I had to look up the word `Homologate`!!!  Nice one Fabro!

**Comment by nollymar** [comment] 2024-03-06 22:59
Dupe of #27869

**Closed by nollymar** 2024-03-06 22:59 UTC
Labels: Type : Defect, Team : Scout, OKR : Core Features, dotCMS : CLI
