### ISSUE TITLE
Inline Editing is broken

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10720] opened 2017-02-14 19:21 UTC
When you hit edit mode with an enterprise license and try to edit text via inline editing (say, on the /about-us/index page, it is failing with a javascript error.

**Comment by dsilvam** [comment] 2017-02-22 16:07
Not able to reproduce anymore. Fixed by @oswaldogallango

**Comment by nollymar** [comment] 2017-02-22 16:16
PR: https://github.com/dotCMS/core/pull/10758

**Closed** 2017-03-07 15:07 UTC
Labels: Release : 4.0.0, WF : Merged, WF : Passed QA
