### ISSUE TITLE
Edit Contentlet page breaks when backend is in italian

### ISSUE THREAD

**Issue by oarrietadotcms** [dotCMS/core#11485] opened 2017-05-04 18:46 UTC
dotCMS: 3.7.1
Client ticket: https://my.dotcms.com/tickets/detail.dot?id=40fba207-a8cf-4dcc-bd89-54968b79ad5c

Page breaks because of [this line](https://github.com/dotCMS/core/blob/3.7.1/dotCMS/html/portlet/ext/contentlet/edit_contentlet_js_inc.jsp#L705) + [this translation](https://github.com/dotCMS/core/blob/3.7.1/dotCMS/WEB-INF/messages/Language_it.properties#L3178). 

Browser console error because of **_dell'_** is creating problems: 
```
+ '<div class="callOutBox">'
+ '"Advanced Image Tools" è una funzione solo dell'Enterprise dotCMS'
+ '</div>'
```

Steps to reproduce: Try to edit properties of Page demo -> About Us -> What We Do

**Comment by jdotcms** [comment] 2017-06-01 20:42
PR: https://github.com/dotCMS/core/pull/11799

**Comment by erickgonzalez** [comment] 2017-09-25 14:19
Can not be reproduced anymore on master because the translation was changed. There is no need to merge the PR, should I close it? @dsilvam @jgambarios

**Comment by dsilvam** [comment] 2017-09-25 14:24
yes @erickgonzalez closing this one

**Closed by dsilvam** 2017-09-25 14:24 UTC
Labels: Severity : Support Requested, Type : Bug
