### ISSUE TITLE
One key/value field add others key/value field values on Drag Drop

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#25596] opened 2023-07-24 11:39 UTC
### Problem Statement

If a content type has more than one key/value field and both have values, so If drag and drop is used for one field, it adds other field values by multiplying each time. (see recording for more clarity)

[drag drop bug.webm](https://github.com/dotCMS/core/assets/102758033/ec9f8ee8-c4a3-40fd-a6de-e08f68ab2be2)

### Steps to Reproduce

Create a content type with more than one key/value field for example three key/values fields.

Add content for each key/value field after that use drag and drop for one field. You will notice it will add other 2 fields values as well by multiplying each time when you use drag and drop

### Acceptance Criteria

Drag and drop should only affect to desire key/value field. And don't add other values nor change other key/value fields as well.

### dotCMS Version

23.1.* - 23.07

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/112511

**Comment by erickgonzalez** [comment] 2023-07-26 17:36
Dupe of https://github.com/dotCMS/core/issues/25189

**Closed by erickgonzalez** 2023-07-26 17:36 UTC
Labels: Type : Defect, Triage, OKR : Customer Support
