### ISSUE TITLE
Update content variable references in containers

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#23006] opened 2022-09-16 15:13 UTC
When adding variables to a container, our javascript uses old variable references for the content properties.  We need to change this to use the $dotContentMap to reference the variables. So, instead of adding `$title`  we need to add `$dotContentMap.title`.

https://user-images.githubusercontent.com/934364/190672313-8802c053-79f8-455a-8d84-8000028c169d.mov

**Comment by rjvelazco** [comment] 2023-03-02 14:23
### Passed Internal QA

Docker Image: [`dotcms/dotcms:master_bd915908`]


https://user-images.githubusercontent.com/72418962/222455326-4d657cbf-5b24-47d0-80f7-9b6fa1165a82.mov

**Comment by bryanboza** [comment] 2023-04-04 20:21
Fixed, tested on release.-23.05 // Docker // FF

**Comment by freddyucv** [comment] 2023-10-04 20:24
This Card was initially fixed with this PR 

https://github.com/dotCMS/core/commit/cfbdd82fb055aa94fbbe438145ef9887eb41220b#diff-9b0fe28c9ed5bd046f991d2c246a%5B%E2%80%A6%5D47a173e28a7648897e1d4f1c600d2R153

but it cause some problems with the auto generated code when you add a Variant inside a Container because some of the attribute used there was not set inside the dotContentMap Object

The Attribute not set was all the used here:

https://github.com/dotCMS/core/commit/cfbdd82fb055aa94fbbe438145ef9887eb41220b#diff-9b0fe28c9ed5bd046f991d2c246ac02446247a173e28a7648897e1d4f1c600d2R163-R184

**Comment by john-thomas-dotcms** [comment] 2023-10-04 22:24
To be clear, the problems caused by the original PR are not related to variants or Experiments at all.  The problems happen in all containers, with or without Experiments.

The original code changes assumed that all variables that were could be added with the "Add Variable" button in containers were also available as properties of the $dotContentMap object.  Unfortunately, they're not.  The $dotContentMap object is simply a regular content map, and some variables available in containers are missing from regular content maps - and thus are also missing from $dotContentObject.

So, for this change to work properly, one of the following needs to happen:
1. The missing variables must be added to the regular content map (and thus to the $dotContentObject).
2. The missing variables must be implemented as code blocks which calculate the appropriate values from the properties that are already available in the regular content map.

Of these 2 options, #1 is a better long-term solution.  But #2 may be simpler/faster to implement, and would definitely touch less code, so it's also likely to have lower risk and lower impact on QA.

**Closed** 2024-01-12 16:58 UTC
Labels: QA : Approved, dotCMS : Admin Tools, QA : Passed Internal, Team : Lunik, Release : 23.05
