### ISSUE TITLE
Problems using personas as limited user 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#17411] opened 2019-10-01 21:03 UTC
After the last permissions changes, now we have some problems using personas as limited users: 

- if you add permissions to some limited user to View all the personas (this directly from the content type), we are unable to see the list of personas from the preview mode of the page, we are able to show this just from live. 

- Also, from the live tab, we are unable to see if the page has personalized versions for some specific persona

SC: https://screencast.com/t/pIBPkwM3P

_Originally posted by @bryanboza in https://github.com/dotCMS/core/issues/17075#issuecomment-536807153_

**Comment by fabrizzio-dotCMS** [comment] 2019-10-02 15:19
These are the urls sent to the endpoint for every particular case

- LIVE Mode -> http://localhost:8080/api/v1/page/ed9d6acd-946d-4812-a502-67fa1826519f/personas?per_page=10&orderby=title&hostId=48190c8c-42c4-46af-8d1a-0cd5db894797&page=1&respectFrontEndRoles=false&pageId=ed9d6acd-946d-4812-a502-67fa1826519f&direction=ASC&per_page=10

- PREVIEW Mode -> http://localhost:8080/api/v1/page/ed9d6acd-946d-4812-a502-67fa1826519f/personas?per_page=10&orderby=title&hostId=48190c8c-42c4-46af-8d1a-0cd5db894797&page=1&respectFrontEndRoles=true&pageId=ed9d6acd-946d-4812-a502-67fa1826519f&direction=ASC&per_page=10

- EDIT Mode -> http://localhost:8080/api/v1/page/ed9d6acd-946d-4812-a502-67fa1826519f/personas?per_page=10&orderby=title&hostId=48190c8c-42c4-46af-8d1a-0cd5db894797&page=1&respectFrontEndRoles=false&pageId=ed9d6acd-946d-4812-a502-67fa1826519f&direction=ASC&per_page=10 

I believe the problem is tied to the value passed on the param **respectFrontEndRoles** if I set it to **true** with my debugger I get the list of Personas that are expected.  Probably this value must be always set to true.

Additionally.. the button that is expected to appear next to the Persona showing that for that particular persona exists personalization isn't showing because it is tied to the edit capabilities that current user has at the moment. In other words such button isnt visible because the current user can not edit the page.

This is should be addressed by a front-end dev.

**Comment by jgambarios** [comment] 2019-10-03 17:18
PR: https://github.com/dotCMS/core/pull/17422

**Comment by bryanboza** [comment] 2019-10-04 21:12
We have problems here:  

- After this fix now we are able to see the list of personas just respecting the FE role, but If you have a personalized page and you add full edit permissions to a limited user, when you try to remove the personalization as the limited user we are unable to do it and we have an error on logs. Nothing in UI.

FYI: This is because we are validating permissions to the persona. And I don't have permissions to the personas content type. If I add permissions to the specified persona that works 


ST: https://gist.github.com/bryanboza/dfb44848600d8e970d16d51e812fdb7c
SC: https://screencast.com/t/vp6egJYkRMRy

**Comment by wezell** [comment] 2019-10-04 21:34
PR #17436

**Comment by bryanboza** [comment] 2019-10-09 14:50
Fixed, the problems were moved to a separate card

**Closed** 2019-10-09 16:10 UTC
Labels: Merged, Passed Internal QA, Passed QA, Release : 5.2.0, Type : Bug
