### ISSUE TITLE
Can't save content by checkbox with similar values

### ISSUE THREAD

**Issue by litked** [dotCMS/core#7670] opened 2015-04-29 13:04 UTC
1. Create new ContentType 'MyContentType'
2. Create new field 'MyCheckbox' (type Checkbox)
3. Edit field 'MyCheckbox'. Set value
 - canada|Canada
 - canada-new|Canada New

4. Create new contentlet of type 'MyContentType'
5. Edit new contentlet. Check both checkboxes. Save. Result: both checkboxes are 'checked'. OK
6. Edit new contentlet. Check off both checkboxes. Save. Result: both checkboxes are still 'checked'!

Reproduced on http://demo.dotcms.com/

**Comment by bryanboza** [comment] 2015-05-06 20:13
Tested on the last 3.2 and not able to reproduce...

**Comment by oarrietadotcms** [comment] 2015-05-08 20:15
Closing this one as it is not reproducible in latest release.

**Comment by litked** [comment] 2015-05-10 16:08
Sorry, here is correct description:
1. Create new ContentType 'MyContentType'
2. Create new field 'MyCheckbox' (type Checkbox)
3. Edit field 'MyCheckbox'. Set value
 Canada|canada
 Canada New|canada-new
4. Create new contentlet of type 'MyContentType'
5. Edit new contentlet. Check only 'Canada New'. Save. Result: both checkboxes are 'checked'!

Reproduced today on http://demo.dotcms.com/
Screencast: http://screencast.com/t/h7VLq7L1e

**Comment by oarrietadotcms** [comment] 2015-05-11 13:19
@rogelio-blanco could you please try to reproduce and fix it? Thanks!

**Comment by rogelio-blanco** [comment] 2015-05-11 19:54
I was able to reproduce it.   I will continue with the fix

**Comment by rogelio-blanco** [comment] 2015-05-13 15:03
pull request #7728

**Closed by rogelio-blanco** 2015-05-13 15:03 UTC
Labels: Cat : Content Management, in progress, Type : bug

**Comment by shayngr** [comment] 2015-05-14 16:04
Tested on:  3.2 Nightly build 2015-05-14 04:13 // Ubuntu 14.04 // Postgres // Firefox

**Comment by shayngr** [comment] 2015-06-15 19:41
Added TC http://qa.dotcms.com/index.php?/cases/view/59161
