### ISSUE TITLE
Unclear error message on duplicate content

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#15971] opened 2019-02-05 19:35 UTC
Creating duplicate Page Asset at the Host results in an error message of "Unable to Save/Update Object to Hibernate Session" rather than the expected messages of "Another page with the same URL already exists" which is what happens when you save to the folder rather than the Host.

## Steps to Reproduce (for bugs)
1. Create page asset, select demo as the Host/Folder
2. Create identical page asset,  select demo as the Host/Folder

Notes this is not present in 5.0.3, where there is no error message at all, it simply declines to create the duplicate content.

* dotCMS version used: 4.0.1

**Comment by wezell** [comment] 2019-02-05 21:44
We were just talking about this case!  Closing this one as a dupe of #15951

**Closed by wezell** 2019-02-05 21:44 UTC
