### ISSUE TITLE
Invalid permission - using a workflow action (from the workflow screen) is dependent on portlet access 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#13810] opened 2018-03-08 14:13 UTC
If you try to run a workflow with a limited user who does not have access to the workflow portlet it fails - because of this code :

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPIImpl.java#L667-L668

and 

https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/portlets/workflows/business/WorkflowAPIImpl.java#L694-L696

Please reproduce before fixing,  using the document workflow and the login as.

## We need integration tests 
1. to insure that a particular user is seeing the correct workflows 
2. to insure a particular user can execute the correct workflows

**Comment by wezell** [comment] 2018-03-08 14:36
dupe: #13782

**Comment by oswaldogallango** [comment] 2018-03-12 17:09
Hi @wezell the problem with the "Document Management" workflow is caused because of the "Save as Draft" action when you try to create a new contentlet. The workflow on master uses the "save as draft" actionlet and this one requires that the content already exist (because it's using the "save" without a new version). The difference with the previous copies of dotCMS is that before we always execute the save as it's working currently on demo.dotcms.com. If you check demo you will see that the "save as draft" action doesn't have any actionlet associated.

 In this case, we should modify the Workflow to include a "Save" and only show the "Save as Draft" if the content is not new, or modify the Content Types using that workflow to allow to use that one plus the system workflow maybe. What do you think?

This is a dupe of this issue https://github.com/dotCMS/core/issues/13799

**Comment by oswaldogallango** [comment] 2018-03-16 20:12
P.R https://github.com/dotCMS/core/pull/13884

**Comment by bryanboza** [comment] 2018-03-27 22:32
Fixed, after the last changes now i am unable to reproduce the problem

**Closed** 2018-04-10 20:36 UTC
Labels: Type : Bug, WF : Merged, WF : Passed QA
