### ISSUE TITLE
Error trying to get templates from a different host 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#6710] opened 2014-11-13 19:37 UTC
We are having a error when you try to use the templates from a different host that the default

Steps: 
1- Add a new blank host and set as default 
2- Create a new folder 
3- Try to add a new html page 
4- Select any template from a other host

When you click to the "All sites" option, we are getting this error

https://gist.github.com/bryanboza/04c2f270efd954555315

Tested on nightly 2014-11-12 // H2 // FF

**Comment by john-thomas-dotcms** [comment] 2018-03-23 06:11
This problem still exists (I'm seeing it right now when trying to work with a blank site).

Note that this problem has a higher impact on Community edition, since on Community edition you can't copy a site, so you can only create multiple sites by creating each as a blank site.  And since this issue prevents you from sharing templates among sites, you need to recreate all containers and templates on each site.

**Comment by john-thomas-dotcms** [comment] 2018-03-24 18:56
Update:

* Initially I got a 500 error when trying to just **_view_** a page which was created using a template from a different host.I was able to make that go away by creating a local template which included containers from the other host.
* However I still get a 500 error when trying to **_edit_** the page if I create new containers and templates locally, but include a VTL from a different host in the container code.

**Comment by john-thomas-dotcms** [comment] 2018-03-25 16:31
So I isolated the problem I'm having here, and the problem is when using any template from another host which references a theme from the other host.I saw this with _both_ template designer templates and with advanced templates, but I was able to fix the problem with the advanced template by changing the theme path reference to explicitly specify the host (e.g.

**Comment by john-thomas-dotcms** [comment] 2018-03-25 16:50
So I isolated the problem I'm having with this, and the problem is when using any template from another host which uses a **theme** from the other host.

* I saw this with _both_ template designer templates and with advanced templates.
    * But I was able to fix the problem with the advanced template by changing the theme path reference to explicitly specify the host.  In other words:
        * Line which caused a 500 error: `#set($blah1 = $dotTheme.put("path", "/application/themes/one-pager/"))`
        * Line which worked without problems: `#set($blah1 = $dotTheme.put("path", "//demo.dotcms.com/application/themes/one-pager/"))`

### Impact

This totally makes sense, since the path references in the remote theme are all set up as relative to the root (rather than having an explicit site reference).  And _some_ of this can be fixed by just updating the paths referenced in the template (as in the advanced template fix mentioned above).

But the bigger issue is that the default path assigned to $dotTheme.path does **not** reference the site.

* So at least from my tests, it's not currently possible to use themes from other hosts without finding and explicitly adding the site to every path reference in the theme.
* I'm not sure if this can be solved in the template code by re-assigning the `$dotTheme.path` variable (I didn't try), but it seems like we would want the default values assigned to all the `$dotTheme` properties to explicitly reference the site so the theme can easily be used from another site without doing code gymnastics in the theme.

I realize that this may be something that we decide to just leave as it is.  But if so, I recommend that we at least update all the themes in the starter site to include explicit site references, so they can be used easily if a customer creates a new blank site.

**Comment by john-thomas-dotcms** [comment] 2018-03-25 16:54
Also, one last note: It seems like a bug that we give a 500 error when a theme references a file/path that doesn't exist, rather than some kind of file not found error.

Even if the paths in a remotely referenced theme are relative to the root (and so don't exist on the site that's trying to use them), it would be nice to fail more gracefully - like with a "File not found" and full file path instead of a 500 error.

**Comment by john-thomas-dotcms** [comment] 2018-03-25 18:25
Another update:

I was finally able to get a template working when referencing it from another site.  It took two steps:

1. Add explicit references to the site (where the template is located) to every root-relative path in every file in the template that has a path.
    * There were 40-50 path references scattered throughout the template files, in everything from vtl to js to less files.
        * Many of these are ugly, referencing the full root path (e.g. /application/themes/**quest**/...) inside the template files, so even if you just copy a template you really need to go edit all these paths to make sure you don't end up pulling files from the original template (the one you copied from).
    * Note, however, that you can **not** add site references to the paths in the template.vtl file (see below).
        * All path references in the template.vtl file have to just be left with standard (root-relative) $dotTheme.path references or you'll get a 500 error.
2. Remove a single "//default" reference in the template.vtl file.
    * Specifically, line 13 of the template.vtl file (`#dotParse("//default${dotTheme.path}html_head.vtl")` had to be changed to `#dotParse("${dotTheme.path}html_head.vtl")`
    * This one line may be the source of the problem that Bryan originally reported in this issue.
        * And thus a simple fix for the originally reported issue may be to edit that one line in the standard bootstrap template.vtl.

I expect that we're going to be re-creating the themes at some point (hopefully soon) in bootstrap 4 (and thus Sass).  It might make sense to leave all this messiness as it is for now, but just make sure when we re-create the themes, we try to (if at all possible) make sure that they play nice (e.g. don't require manual path editing) when being copied or referenced from a different site.

**Comment by john-thomas-dotcms** [comment] 2018-03-26 14:13
So a couple more notes on this that may (or may not) be helpful:

1. The 500 error appears to be thrown if any file referenced directly in the template.vtl file can't be found.
    * But if there's an unrecognized reference in the header_html.vtl or footer.vtl file, these don't appear to cause the 500 error (even though those files are included by the template.vtl file).
        * I don't know whether that's because the site-referenced paths in those included files can be found, or because for some reason unfound files in the included files don't cause a 500 error).
2. The `//default` notation at the beginning of a path **is** properly resolved to the default host within the template.vtl file.
    * The error message shows the full site-referenced path to the file correctly (e.g. it looks like `//demo.dotcms.com/path`, not like `//default/path`).
    * But - at least in the template.vtl file - a full site reference (either using `//default` or using explicit `//demo.dotcms.com` notation) is not recognized (and causes the 500 error).
    * And note that it appears the `//default` reference in the template.vtl shouldn't be there anyway - I just thought it was worth noting that it did get resolved properly, but the file still couldn't be found even when the site-referenced path was correct.
3. Full site references (e.g. `//site.dotcms.com/path`) appear to work properly in some but not all files in the theme.
    * I could get the theme to work after changing the paths to include a site reference, but there were still some elements that didn't display properly.  I didn't take any time to isolate which references worked and which didn't.

**Closed** 2019-10-28 07:41 UTC
Labels: Type : Bug, wontfix
