### ISSUE TITLE
Integrity Checker issues

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#11812] opened 2017-06-05 14:36 UTC
--- Description by @DeanGonzalez ---

Tested on authoring.dotcms.com push publishing to training server with latest 4.1 release build.

To reproduce:

1. Set up a new 4.1 install that Authoring can push to
2. Set up Push Publishing connection where Authoring is the sender and the new server is the receiver
3. Create a folder on the RECEIVING SERVER called "Test"
4. Run the integrity checker, view conflicts and resolve conflicts for each object type, MAKING SURE TO CHECK "FIX AT REMOTE NODE" so that id's do not change on the authoring server.

**Bug One:** Look at the id's Test folder on Authoring and the Test folder in the receiving server - they are not the same, meaning that the "resolve at remote node" in the integrity checker did not work.

**Bug Two:** Create a new folder on authoring, then a folder of the same name on the receiving server, then run the integrity checker and view conflicts and examine the folders tab - nothing appears there as a conflict - the integrity checker is not picking up conflicted objects.

screencast: https://screencast.com/t/99R5PZVRxXnj

**Comment by agomez-dotcms** [comment] 2017-06-12 05:23
Hi Guys,

This ticket is not related to Integrity Checker issues but may be turned out into actual Push-Publishing problems. After analyzing issues reported above some days ago, it was found that folder in question does not cause conflicts on Integrity Checker because the Hosts/Sites on Sender and Receiver servers are not the same. So, Integrity Checker won't report any conflicts.

However, when exercised the functionality that was tried to accomplish as ultimate goal (ie. pushing the test folder from Authoring to Receiver server), Push-Publishing did not work and instead aborted with errors. After analysis, below is more information about the issue that was found, which was compiled after discussions with @jgambarios and @dsilvam (to be taken into consideration for proper resolution). More discussion is needed to decide what solution to implement:

## FINDINGS/FACTS:
1. Ids for Default Workflow's steps differ between Authoring and Starter databases
2. Synchronization of Workflow currently delete Workflow Steps that did not come from Sender
3. Deletion of Workflow Steps can not always be performed successfully whenever there are assets/contentlets referencing them

```
public class WorkflowHandler implements IHandler {
  ...
  private void handleWorkflows(Collection<File> workflows) throws DotPublishingException, DotDataException{
    ...
    // delete those not mentioned in the bundle
    for (WorkflowStep step : workflowAPI.findSteps(remoteScheme)) {
      if(!stepIds.contains(step.getId())) {
        workflowAPI.deleteStep(step);      //<-------------
      }
      ...
    }
    ...
}
```

```
public class WorkflowAPIImpl
  ...
  public void deleteStep(WorkflowStep step) throws DotDataException {
    ...
    int contentletsRefeceningStep = getCountContentletsReferencingStep(step);
    if(contentletsRefeceningStep > 0){
      throw new DotDataException("</br> <b> Step : '" + step.getName() + "' is being referenced by: "+contentletsRefeceningStep+" contenlet(s)</b> </br></br>");
    }
    ...
  }
  ...
}
```

## SOLUTIONS/APPROACHES:
1. Do Nothing (Let's assume Receiver is initially a copy of the Sender Database... like has been done so far)
2. Not sync the Default Workflow (even if it has changed on Sender)
3. Fix ids for Default Workflow's steps on starter (so they match the previous values)
4. Implement Integrity Checker for Workflow Steps (so it would let find and fix Workflow Steps with same name but different ids between Sender and Receiver)
5. Enhance Error Report to state that problem is at Receiver side (and include references for the involved contentlets)
6. As part of the deletion of a Workflow Step, to automatically remove any reference having the workflow step being deleted
7. Automatically fix ids on Receiver (Workflow Handler) for Workflow Steps with same name but different ids
8. Others?

Thanks,
Anibal

**Comment by agomez-dotcms** [comment] 2017-06-16 16:27
PR Core (Master): https://github.com/dotCMS/core/pull/11920
PR Enterprise (Master): https://github.com/dotCMS/enterprise-2.x/pull/473

**Comment by agomez-dotcms** [comment] 2017-06-16 16:28
Hi Guys,

This issue is now fixed in an **unobtrusive way** (trying to not introduce regressions) by supporting Push-Publishing of "Test" folder from Authoring (Sender) to Starter (Receiver). Please notice Integrity Checker need to be executed prior to exercising Push-Publishing functionality in order to fix/resolve all conflicts at REMOTE NODE (Receiver). As Hosts/Sites differ between Authoring and Starter instances (ie. dotcms.com vs. demo.dotcms.com), pushing "Test" folder from Authoring instance performs following operations on Starter instance:
1. Host is pushed/created as dependency (dotcms.com)
2. Default Workflow is pushed/synced as dependency (This was actually the operation causing errors)
3. Test folder is finally pushed under the newly pushed/created Host (This was the operation sought to achieve in first instance)

As documented above, Push-Publishing for "Test" folder was not working on this Authoring vs. Starter scenario and instead aborted with errors. An enhanced version of Solution/Approach #6 described in comment above was implemented. As of now, references to existing workflow steps are either (1) replaced by references to incoming workflow steps when there is a one-to-one name correspondence or (2) removed/cleared out from existing workflow tasks/actions. This is done prior to deletion of Workflow Steps -that did not come from Sender- in order to preserve consistency on pushed/synced workflow/references so old Workflow Steps can be automatically removed without any integrity issues. **This approach/fix is intended to be unobtrusive** as it just makes more robust the operations that Workflow Handler was already performing when syncing the Default Workflow.

Following is the exception that was being thrown at Receiver, which caused abortion of Push-Publishing process:
```
[11/06/17 14:31:01:483 CST] ERROR business.PublisherAPIImpl: </br> <b> Step : 'Initial State' is being referenced by: 1 contenlet(s)</b> </br></br>
com.dotcms.publishing.DotPublishingException: </br> <b> Step : 'Initial State' is being referenced by: 1 contenlet(s)</b> </br></br>
	at com.dotcms.enterprise.publishing.remote.handler.WorkflowHandler.handleWorkflows(WorkflowHandler.java:231) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.WorkflowHandler.handle(WorkflowHandler.java:74) ~[ee_clean.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:201) [dotcms_4.2.0_999999.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_4.2.0_999999.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: com.dotmarketing.exception.DotDataException: </br> <b> Step : 'Initial State' is being referenced by: 1 contenlet(s)</b> </br></br>
	at com.dotcms.enterprise.publishing.remote.handler.WorkflowHandler.handleWorkflows(WorkflowHandler.java:231) ~[ee_clean.jar:?]
	... 4 more
Caused by: com.dotmarketing.exception.DotDataException: </br> <b> Step : 'Initial State' is being referenced by: 1 contenlet(s)</b> </br></br>
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.deleteStep(WorkflowAPIImpl.java:272) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.WorkflowHandler.handleWorkflows(WorkflowHandler.java:231) ~[ee_clean.jar:?]
	... 4 more
[11/06/17 14:31:01:492 CST] ERROR lang.String: Error Publishing: com.dotcms.publishing.DotPublishingException: </br> <b> Step : 'Initial State' is being referenced by: 1 contenlet(s)</b> </br></br>
[11/06/17 14:31:01:492 CST]  INFO rest.PublishThread: Finished bundle publish process
```

Finally, another problem was detected after implementing/testing solution described above. Integrity Checker was leaving cached the old Default Workflow (Scheme and Steps) after conflicts were fixed/resolved at REMOTE NODE. This caused following exception on Push-Publishing at Receiver side, which was fixed **unobtrusively** on Scheme Integrity Checker:
```
[15/06/17 14:31:01:483 CST] ERROR business.PublisherAPIImpl: Error Publishing Bundle: Already exist a scheme with the same name (Default Scheme). Create different schemes with the same name is not allowed. Please change your workflow scheme name.
com.dotcms.publishing.DotPublishingException: Already exist a scheme with the same name (Default Scheme). Create different schemes with the same name is not allowed. Please change your workflow scheme name.
	at com.dotcms.enterprise.publishing.remote.handler.WorkflowHandler.handleWorkflows(WorkflowHandler.java:332) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.WorkflowHandler.handle(WorkflowHandler.java:74) ~[ee_clean.jar:?]
	at com.dotcms.publisher.receiver.BundlePublisher.process(BundlePublisher.java:201) [dotcms_4.2.0_999999.jar:?]
	at com.dotcms.rest.PublishThread.run(PublishThread.java:41) [dotcms_4.2.0_999999.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: com.dotmarketing.exception.DotDataException: Already exist a scheme with the same name (Default Scheme). Create different schemes with the same name is not allowed. Please change your workflow scheme name.
	at com.dotcms.enterprise.publishing.remote.handler.WorkflowHandler.handleWorkflows(WorkflowHandler.java:276) ~[ee_clean.jar:?]
	... 4 more
Caused by: com.dotmarketing.exception.DotDataException: Already exist a scheme with the same name (Default Scheme). Create different schemes with the same name is not allowed. Please change your workflow scheme name.
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.deleteStep(WorkflowAPIImpl.java:297) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.WorkflowHandler.handleWorkflows(WorkflowHandler.java:268) ~[ee_clean.jar:?]
	... 4 more
Caused by: com.dotmarketing.exception.DotDataException: Already exist a scheme with the same name (Default Scheme). Create different schemes with the same name is not allowed. Please change your workflow scheme name.
	at com.dotmarketing.portlets.workflows.business.WorkflowFactoryImpl.saveScheme(WorkflowFactoryImpl.java:918) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowFactoryImpl.deleteWorkflowActionClassParameters(WorkflowFactoryImpl.java:281) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotmarketing.portlets.workflows.business.WorkflowAPIImpl.deleteStep(WorkflowAPIImpl.java:279) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotcms.enterprise.publishing.remote.handler.WorkflowHandler.handleWorkflows(WorkflowHandler.java:268) ~[ee_clean.jar:?]
	... 4 more
[15/06/17 14:31:01:492 CST] ERROR lang.String: Error Publishing: com.dotcms.publishing.DotPublishingException: Already exist a scheme with the same name (Default Scheme). Create different schemes with the same name is not allowed. Please change your workflow scheme name.
[15/06/17 14:31:01:492 CST]  INFO rest.PublishThread: Finished bundle publish process
```

Thanks,
Anibal

**Closed** 2017-06-20 15:20 UTC
Labels: Release : 4.2.0, WF : Merged, WF : Passed QA
