### ISSUE TITLE
Future Time Machine does not display future publish content

### ISSUE THREAD

**Issue by jgambarios** [dotCMS/core#17594] opened 2019-11-06 15:27 UTC
Original issue reported in https://github.com/dotcms/core/issues/17467 where we fixed future publish content to display in listings when using content pulls. PR: https://github.com/dotCMS/core/pull/17588 but we still we are not able to display individual future publish content.

---

Recreated on two servers running 5.2 release version

To reproduce:
Create a new news content and set the publication date to the future and the expiration date to the future and "Save" as draft.

Go to the time machine and place the future date in between the publish and expire dates on the content, then navigate to the news listing page.  **Bug is that the future news does not display at all.**

See video:  

![TimeMachine](https://user-images.githubusercontent.com/1569167/66677473-f1229a80-ec26-11e9-846d-312bfaeef5e8.gif)

**Comment by jgambarios** [comment] 2019-11-19 19:49
PR: https://github.com/dotCMS/core/pull/17619

**Comment by jgambarios** [comment] 2019-11-25 18:33
I'm unable to see URL maps of future publish date contents.

1. Create a news contentlet with a future publish date
2. Go to the time-machine and select a future date where the created content should be publish.
3. The content is displayed in the news listing.
4. Clicking on the new content redirects to a 404 page:

```
12:32:12.095  WARN  cache.LegacyContentTypeCacheImpl - Structure with inode: 'system_hostnews' not found in db
12:32:12.113  WARN  cache.LegacyContentTypeCacheImpl - Structure with inode: 'system_hostnews' not found in db
12:32:12.125  WARN  cache.LegacyContentTypeCacheImpl - Structure with inode: 'system_hostnews' not found in db
12:32:12.130  ERROR servlet.VelocityServlet - ResourceNotFoundExceptionorg.apache.velocity.exception.ResourceNotFoundException: Can't find content. Identifier: , Live: true, Lang: 1 @ url:GET//demo.dotcms.com/news/aaa-test1 | lang:1 | ip:0:0:0:0:0:0:0:1 | Admin:false | start:11-25-2019 11:10:39 CST  ref:http://localhost:8080/news-events/news/
org.apache.velocity.exception.ResourceNotFoundException: Can't find content. Identifier: , Live: true, Lang: 1
	at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.findPageInDefaultLanguageDifferentThanProvided(HTMLPageAssetAPIImpl.java:913) ~[classes/:?]
	at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.findByIdLanguageFallback_aroundBody24(HTMLPageAssetAPIImpl.java:886) ~[classes/:?]
	at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl$AjcClosure25.run(HTMLPageAssetAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[classes/:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[classes/:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[classes/:?]
	at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.findByIdLanguageFallback(HTMLPageAssetAPIImpl.java:874) ~[classes/:?]
	at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.findByIdLanguageFallback(HTMLPageAssetAPIImpl.java:868) ~[classes/:?]
	at com.dotcms.rendering.velocity.servlet.VelocityLiveMode.serve(VelocityLiveMode.java:106) ~[classes/:?]
	at com.dotcms.rendering.velocity.servlet.VelocityLiveMode.serve(VelocityLiveMode.java:63) ~[classes/:?]
	at com.dotcms.rendering.velocity.servlet.VelocityServlet.service_aroundBody0(VelocityServlet.java:68) ~[classes/:?]
	at com.dotcms.rendering.velocity.servlet.VelocityServlet$AjcClosure1.run(VelocityServlet.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[classes/:?]
	at com.dotcms.aspects.interceptors.CloseDBMethodInterceptor.invoke(CloseDBMethodInterceptor.java:34) ~[classes/:?]
	at com.dotcms.aspects.aspectj.CloseDBAspect.invoke(CloseDBAspect.java:42) ~[classes/:?]
	at com.dotcms.rendering.velocity.servlet.VelocityServlet.service(VelocityServlet.java:37) ~[classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CMSFilter.doFilterInternal(CMSFilter.java:176) ~[classes/:?]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:47) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:119) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:104) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:399) ~[urlrewritefilter-4.0.4.jar:4.0.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:106) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:88) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:48) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:99) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:90) ~[classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[catalina.jar:8.5.32]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[catalina.jar:8.5.32]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.32]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650) ~[catalina.jar:8.5.32]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[catalina.jar:8.5.32]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[catalina.jar:8.5.32]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) ~[tomcat-coyote.jar:8.5.32]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.32]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.32]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.dotmarketing.portlets.contentlet.business.DotContentletStateException: Can't find contentlet:  lang:1 live:true
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findContentletByIdentifier_aroundBody12(ESContentletAPIImpl.java:383) ~[classes/:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure13.run(ESContentletAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[classes/:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[classes/:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[classes/:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findContentletByIdentifier(ESContentletAPIImpl.java:364) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.findContentletByIdentifier(ContentletAPIInterceptor.java:831) ~[classes/:?]
	at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.findByIdLanguageFallback_aroundBody24(HTMLPageAssetAPIImpl.java:881) ~[classes/:?]
	... 77 more
Caused by: com.dotmarketing.portlets.contentlet.business.DotContentletStateException: No contentlet found for given identifier
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findContentletByIdentifier_aroundBody12(ESContentletAPIImpl.java:372) ~[classes/:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure13.run(ESContentletAPIImpl.java:1) ~[classes/:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[classes/:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[classes/:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[classes/:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findContentletByIdentifier(ESContentletAPIImpl.java:364) ~[classes/:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.findContentletByIdentifier(ContentletAPIInterceptor.java:831) ~[classes/:?]
	at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.findByIdLanguageFallback_aroundBody24(HTMLPageAssetAPIImpl.java:881) ~[classes/:?]
	... 77 more
12:32:12.136  WARN  business.RulesEngine - we have already run the rules for:48190c8c-42c4-46af-8d1a-0cd5db894797_EVERY_PAGE
```

**Comment by dsilvam** [comment] 2020-01-06 15:14
PR: https://github.com/dotCMS/core/issues/17594

**Comment by fabrizzio-dotCMS** [comment] 2020-01-10 03:12
Unfortunately, after a few attempts, the content with future publish-date becomes unavailable. 
For example, You can create a  couple of news with future publish dates. And try to visualize them in time machine. The news will appear in the listing. By clicking on the news entry itself the user should see the News displayed as a page. This doesn't always seem to work. After a few attempts to visualize the contant, using the same link. It becomes a 404 accompanied with the following exception:

 `Caused by: com.dotmarketing.portlets.contentlet.business.DotContentletStateException: Can't find contentlet:  lang:1 live:true
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findContentletByIdentifier_aroundBody12(ESContentletAPIImpl.java:383) ~[dotcms_5.0.0_c129083.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure13.run(ESContentletAPIImpl.java:1) ~[dotcms_5.0.0_c129083.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:42) ~[dotcms_5.0.0_c129083.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.0.0_c129083.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.0.0_c129083.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findContentletByIdentifier(ESContentletAPIImpl.java:364) ~[dotcms_5.0.0_c129083.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.findContentletByIdentifier(ContentletAPIInterceptor.java:831) ~[dotcms_5.0.0_c129083.jar:?]
	at com.dotmarketing.portlets.htmlpageasset.business.HTMLPageAssetAPIImpl.findByIdLanguageFallback_aroundBody24(HTMLPageAssetAPIImpl.java:881) ~[dotcms_5.0.0_c129083.jar:?]
	... 77 more
Caused by: com.dotmarketing.portlets.contentlet.business.DotContentletStateException: No contentlet found for given identifier`

But suddenly the constant can comeback even without having to invalidate the cache.

**Comment by fabrizzio-dotCMS** [comment] 2020-01-10 03:14
Apparently this Pull-Request solves the problem. https://github.com/dotCMS/core/pull/17769
But at the moment it hasn't been merged in master to properly test the issue.

**Comment by fabrizzio-dotCMS** [comment] 2020-01-10 03:20
Related to: #16684

**Comment by freddyucv** [comment] 2020-01-28 14:18
> Related to: #16684

Ready https://github.com/dotCMS/core/issues/16684, so this issue should be tested again

**Comment by dsilvam** [comment] 2020-02-03 15:31
Passed Internal QA: Future news content is shown after following the described steps in the ticket description.

**Comment by dsilvam** [comment] 2020-02-03 16:22
@bryanboza the fix for this one was already merged into 5.2.5, just putting the label to this issue.

**Comment by bryanboza** [comment] 2020-02-03 22:26
We are unable to test this specific case since we have multiple JS errors and we are unable to load the events page from a future time machine snapshot. 

We need some work here: https://www.screencast.com/t/astm5vcVX

**Comment by wezell** [comment] 2020-02-03 22:36
@bryanboza  - Please test with the news content type.  The JS issues from the timemachine frame are out of the current scope of this bug.

**Comment by bryanboza** [comment] 2020-02-04 16:56
Hey @wezell, since the card was reported with this specific case, I need to make sure the case does not happen anymore before to pass or close the card. 

But also tested with another content type and seems neither is working 
SC: https://www.screencast.com/t/qzji2Iw4zo

**Comment by wezell** [comment] 2020-02-04 18:09
@bryanboza  not quite - what you are testing there is not the core issue of not returning the content, you are testing a javascript implementation issue that is in the starter site.

**Comment by wezell** [comment] 2020-02-04 18:11
@bryanboza in your second case looks legit.

**Comment by freddyucv** [comment] 2020-02-10 18:28
Testing this issue was found this one: https://github.com/dotCMS/core/issues/17964

**Closed** 2020-02-11 21:17 UTC
Labels: Changelog: Documented, Merged, Release : 5.2.5, Type : Bug, Waiting for ticket

**Comment by bryanboza** [comment] 2020-02-21 20:26
This issue was moved to #17951
