### ISSUE TITLE
Edit Page V2: Automate the deploy of the SDK libraries

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28259] opened 2024-04-16 17:58 UTC
### Parent
#27546 

### Task description
As a developer working on dotCMS, I want to automate the deployment process of the SDK libraries so that whenever a dotCMS release is generated, the SDK libraries are published to npm with tagged versions and a tag is created for the `example/nextjs`.

### Acceptance Criteria
- The SDK libraries are automatically published to npm with tagged versions when a dotCMS release is generated.
- A tag is created for the `example/nextjs` repository in the dotCMS GitHub organization.
- The deployment process is triggered automatically and does not require manual intervention.

### External Links
- GitHub Repository: [dotCMS SDK Libraries](https://github.com/dotCMS/dotCMS-sdk-js)
- NPM Registry: [dotCMS SDK Libraries](https://www.npmjs.com/package/@dotcms/dotcms-js)

### Assumptions & Initiation Needs
- Access to the dotCMS GitHub organization and npm registry is required.
- The deployment process will be set up using a continuous integration/continuous deployment (CI/CD) tool like Jenkins or GitHub Actions.

### Quality Assurance Notes & Workarounds
- Ensure that the correct version numbers are used when tagging the SDK libraries for npm publication

**Comment by dcolina** [comment] 2024-08-13 18:52
We are going to change the approach previously implemented. The main idea is to use husky (pre-commit) to detect if the SDKs have been affected in the commit. If that occurs an update version script will run.
In this scenario our workflow would only publish the SDK into the NPM registry, so it would simplify our process and we would avoid automatic PR and possible loop issues.

**Comment by dcolina** [comment] 2024-08-29 15:46
## Note to QA:

## Verification of SDK Version Bumping and NPM Deployment

#### Objective:
The purpose of this QA task is to verify that the automated version bumping for the SDK libraries works correctly when changes are made to the codebase and that the updated versions are published to the NPM registry as part of the deployment workflow.

#### Steps for Verification:

**Part 1: Pre-Commit Hook Validation**

1. **Make a Change in the Local Repository:**
   - Open your local copy of the repository.
   - Navigate to any of the SDK libraries located under `core-web/libs/sdk/` (e.g., `sdk-client`, `sdk-angular`, `sdk-react`, `sdk-experiments`).
   - Apply a minor change to the code, such as adding a comment or modifying some code.

2. **Stage the Changes:**
   - Add the modified files to the Git staging area by running:
   ```bash
   git add path/to/modified-file.js
   ```

3. **Commit the Changes:**
   - Commit the changes to trigger the pre-commit hook:
   ```bash
   git commit -m "Test commit to trigger version bump"
   ```
   - Ensure that the pre-commit hook (Husky) executes successfully and updates the versions of the SDK libraries and example package 
dependencies (examples).

4. **Push and Open a Pull Request (PR):**
   - Push the changes to the remote repository:
   ```bash
   git push origin your-feature-branch
   ```
   - Open a Pull Request (PR) on the repository.

   - Review the PR to ensure that:
   - - The version numbers of all SDK libraries (`client`, `angular`, `react`, `experiments`) are incremented.
   - - The dependencies in all example projects (`examples`) have been updated to reflect the new SDK versions.

**Part 2: Deployment Workflow and NPM Publication**

5. **Merge the Pull Request:**

   - Once the PR has been reviewed and approved, merge it into the master branch.

6. **Verify the Deployment Workflow:**

   - Ensure that the deployment workflow is triggered upon merging the PR.
   - Check the workflow logs to confirm that:
   - - All updated SDK packages are published to the NPM registry.

7. Validate the Version Increment on NPM:

   - After the workflow completes, use the terminal to check the new versions published on NPM. Run the following command:
   ```bash
   npm view @dotcms/client
   ```
   - Verify that the version has been incremented as expected.

#### Expected Results:

- The PR should display incremented version numbers for all SDK libraries and updated dependencies for the example projects.
- The deployment workflow should successfully publish the updated packages to the NPM registry.
- The npm view command should reflect the new version for each package.

**Comment by zJaaal** [comment] 2024-09-03 18:59
# IQA Failed 

We have an small issue in the assignment of versions in the pre-commit 

The case happens when we have 2 PRs that are making changes in the SDKs 

Let's set the hypothetical case that the SDKs are in version `1.0` 


## Steps

1. PR N1: Makes a huge change and commits. The pre-commit hook run and set the version everywhere to `2.0`
2. PR N2: Created afterwards and make an small change and commits: The pre-commit hook run and set the version everywhere to `2.1`
3. PR N2: Goes through the merge Queue and is published to NPM as `2.1` skipping from `2.0` that is in a Big PR that is pending to be merged in the future 


This happened with this to PRs:

PR N1: https://github.com/dotCMS/core/pull/29665 from `0.0.1-alpha.33` -> `0.0.1-alpha.34`
PR N2: https://github.com/dotCMS/core/pull/29653 from `0.0.1-alpha.34` -> `0.0.1-alpha.35` -> Merged

In this case, `0.0.1-alpha.35` was published without the `0.0.1-alpha.34` published before and now PR N1 has to change the versions up to `0.0.1-alpha.36`

**Comment by fabrizzio-dotCMS** [comment] 2024-09-10 14:00
I followed this PR https://github.com/dotCMS/core/pull/29916 which introduces changes in SDKs
I verified the run and found that the step that presents the changes and actions that need to be taken shows that no SDK was modified which is wrong.  

![Screenshot 2024-09-09 at 3 47 24 PM](https://github.com/user-attachments/assets/7380a7cd-5f18-439a-94e5-9ce6e8740200)

There is not a pass

**Comment by dcolina** [comment] 2024-09-13 12:20
### QA Testing Notes: How to Test the Complete Workflow

To verify the changes in this pull request, follow these steps to test the full CI/CD workflow in GitHub Actions, ensuring correct state persistence and propagation across PR Checks, Merge Queue Checks, and Master Checks.

#### 1. **Test PR Checks Workflow**

- **Open a Pull Request:**
  1. Create a new branch and make changes that affect the SDK (e.g., modify SDK-related files).
  2. Open a pull request (PR) to the `master` branch.
  
- **Verify Artifact Creation:**
  1. Ensure the `PR Checks` workflow runs.
  2. Confirm the `sdk-status` artifact is uploaded with the correct name (`sdk-status-${BASE_SHA}`).
  3. Check that the `sdk_libs` value is correctly determined and stored.

#### 2. **Test Merge Queue Workflow**

- **Approve and Queue the PR:**
  1. Approve the PR and add it to the merge queue.
  
- **Verify Artifact Retrieval:**
  1. Confirm the `Merge Queue Checks` workflow is triggered.
  2. Ensure it attempts to download the `sdk-status-${BASE_SHA}` artifact and retrieves the correct `sdk_libs` state.

#### 3. **Test Master Checks Workflow**

- **Merge the PR:**
  1. Complete the PR merge to the `master` branch.

- **Verify State and Deployment:**
  1. Ensure the `Master Checks` workflow runs.
  2. Check the logs for the download of the `sdk-status-${BASE_SHA}` artifact.
  3. Verify that the `sdk_libs` state is correctly retrieved, and if `true`, confirm the SDK is deployed to the NPM registry.

#### 4. **Edge Case Testing**

- **No SDK Changes:**
  1. Open a PR without SDK changes.
  2. Verify no `sdk-status` artifact is uploaded and `sdk_libs` remains `false`.

- **Multiple PRs:**
  1. Open multiple PRs that modify SDK files.
  2. Ensure each PR has a unique `sdk-status` artifact and the correct state is propagated.

#### 5. **Check SDK Deployment to NPM Registry**

- **Confirm SDK Deployment:**
  1. After merging, verify the SDK is correctly published to the NPM registry with the expected updates.

### Expected Results

- `sdk_libs` state is consistently maintained across all workflow phases.
- Correct artifact management and state propagation.
- Accurate deployment to the NPM registry when necessary.

By following these steps, you will ensure that the workflow changes work as intended across all phases.

**Comment by nollymar** [comment] 2024-09-23 15:58
This card can be tested only when an SDK needs to be generated. As we don't need to do it now, in case an issue comes up at that moment, a new card will be filed.

**Closed by nollymar** 2024-09-23 15:58 UTC
Labels: Type : Defect, Merged, Note to QA, QA : Needs Internal, Team : Scout, Team : Lunik, OKR : Core Features, Priority : 3 Average, NW Removed
