### ISSUE TITLE
Too much error if focal point parsing fails

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#20239] opened 2021-04-13 14:29 UTC
If I edit an image for the first time, I get a nasty error and stack trace in the logs - this should be a debug at best.  We need to be mindful of spitting out ERRORs and really only use the ERROR level for "Someone has to get up in the night to fix something" type errors.  WARNS should be used instead in most places.

```
10:25:44.222  ERROR focalpoint.FocalPointAPIImpl - Error parsing FP Metadata 
java.lang.NullPointerException: null
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283) ~[?:1.8.0_282]
	at java.util.regex.Matcher.reset(Matcher.java:309) ~[?:1.8.0_282]
	at java.util.regex.Matcher.<init>(Matcher.java:229) ~[?:1.8.0_282]
	at java.util.regex.Pattern.matcher(Pattern.java:1093) ~[?:1.8.0_282]
	at java.util.regex.Pattern.split(Pattern.java:1206) ~[?:1.8.0_282]
	at java.util.regex.Pattern.split(Pattern.java:1273) ~[?:1.8.0_282]
	at com.dotmarketing.image.focalpoint.FocalPointAPIImpl.parseFocalPoint(FocalPointAPIImpl.java:135) ~[classes/:?]
	at com.dotmarketing.image.focalpoint.FocalPointAPIImpl.readFocalPointMeta(FocalPointAPIImpl.java:123) ~[classes/:?]
	at com.dotmarketing.image.focalpoint.FocalPointAPIImpl.readFocalPoint(FocalPointAPIImpl.java:152) ~[classes/:?]
	at org.apache.jsp.html.portlet.ext.contentlet.field.edit_005ffield_jsp._jspService(edit_005ffield_jsp.java:1359) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71) ~[jasper.jar:9.0.41]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[servlet-api.jar:4.0.FR]
```

**Comment by fabrizzio-dotCMS** [comment] 2021-04-15 23:41
This PR fixes that problem and it is already merged
https://github.com/dotCMS/core/pull/20258

**Comment by alfredo-dotcms** [comment] 2021-04-20 00:35
fixed, when uploading an img and starting to add/change focus point no messy Errors logs appear anymore!

![image](https://user-images.githubusercontent.com/37185433/115319914-0b073c80-a13e-11eb-8a96-e1721835d1f8.png)

**Comment by bryanboza** [comment] 2021-05-12 16:18
Fixed, unable to reproduce. Tested on release-21.05 // Postgres // FF

**Closed** 2021-05-18 19:13 UTC
Labels: Merged, Passed Internal QA, Passed QA, Release : 21.05, Type : Bug
