### ISSUE TITLE
Multi-tenant Improvement - Content default host should be the ContentType.Host if Not specified

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#15699] opened 2018-12-12 15:18 UTC
## Use case:
In a multi-tenant environ, I want to delegate to the ability for tenants create their own content types and then content that will live specifically on their host -say hostA.  

## What happens
You can delegate the content type creation but if the tenant creates a content type but DOES NOT add a host/folder field to it, then all content they add to this new content type will end up living on the SYSTEM_HOST.  So you end up with a content type on hostA and the content of that type on SYSTEM_HOST.

What should happen is that if a content is being added which does not have a host/folder set, we should default the content to the host/folder field of the content type for the content which is being added.  Additionally, any tags that are being added to this new content object should default to live on the same content type host, rather than the system_host.

**Comment by erickgonzalez** [comment] 2019-08-12 17:55
This is working as it should, if the content type does not have a site or folder field, the content lives under the host the content type live. E.g:
Content-Type lives under hostA -> content lives under hostA
Content-Type lives under SYSTEM_HOST -> content lives under SYSTEM_HOST

If the Content-Type has a site or folder field the content will live under the value is set.

**Comment by erickgonzalez** [comment] 2019-08-12 20:43
dupe of https://github.com/dotCMS/core/issues/16043

**Closed** 2019-09-27 18:31 UTC
Labels: Changelog, Doc : Needs Doc, Passed Internal QA, Passed QA, Release : 5.2.0
