### ISSUE TITLE
Content query via REST API retrieves related content with default language

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#16917] opened 2019-07-24 17:09 UTC
Reported via Support: Ticket [98775](https://dotcms.zendesk.com/agent/tickets/98775)
Reproducible in dotCMS 5.1.6

dotCMS Content API includes a 'depth' parameter to retrieve related content when returning query results. It also includes a 'language' parameter to retrieve content in the given language. If both parameters are used to retrieve related content for other language than the default one, dotCMS returns related content in the default language instead of the specified language in the query.

### Steps to reproduce the behavior:
1. Create a content type as the parent for the relationship, for example 'Banner Holder'.
2. Create a content type as the child for the relationship, for example 'Banner'.
3. A field of relationship type to relate the above content types. For example, add a 'Banners' field to the 'Banner Holder' content type to include a one-to-many relationship from 'Banner Holder' to 'Banner'.
4. Add a content item in the default language for the parent content type.
5. Add a version in other language for the above parent content.
6. Add a content item in the default language for the child content type.
7. Add a version in other language for the above child content.
8. Relate the child content item to the parent content item.
9. Send a request to dotCMS API to retrieve the related content for the other language (not the default one):
```
/api/content/depth/2/language/2/query/+contentType:BannerHolder%20+deleted:false%20+working:true/orderby/modDate%20desc
```
10. Returned related content is not returned in the specified language (2), it's returned in the default language (1):
```
{
  "contentlets": [
    {
      ...
      "contentType": "MyBannerHolder",
      "live": true,
      "owner": "dotcms.org.1",
      "identifier": "bc5ab1f6-9939-4fd4-ae90-184fb9133501",
      "languageId": 2,
      ...
      "banners": [
        {
        ...
          "contentType": "MyBanner",
          "live": true,
          "owner": "dotcms.org.1",
          "identifier": "a7ef9ec0-7ec6-4202-aa2b-33dbc28dc1fe",
          "languageId": 1,
        ...
        }
      ]      
    }
  ]
}
```

### Expected behavior
Related content should be returned in the language specified as parameter for the content query.

### Screenshots
Related content with a language different that the default language:

![image](https://user-images.githubusercontent.com/2894221/61813603-57a3d380-ae03-11e9-90d1-6f4ea8177f9e.png)

### Additional context
This has been reported by customer via Support: Ticket [98775](https://dotcms.zendesk.com/agent/tickets/98775)

**Comment by nollymar** [comment] 2019-09-16 15:54
**Note to QA and Doc:** 

Filters for the REST API should work as follow: 

- Any params that are supplied to the REST API method (via the /live or /languageId params) should be respected for both parent and related content.  But any params supplied via the query (e.g. "+contentType:blah +languageId:1`) should only apply to the parent content.  If the query includes a languageId:1 param but the REST method call does not include the /languageId param, then the parent content will be limited by languageId, but the related content returned for each parent should include related content of all languages.

- Anonymous users should never see non-live content. Not in the primary list or the related list

**Comment by nollymar** [comment] 2019-09-18 19:18
PR: https://github.com/dotCMS/core/pull/17286

**Comment by nollymar** [comment] 2019-09-19 19:23
**Note to QA:**
Please test these cases from the content rest api using anonymous user:

- filter by inode a non-live content
- filter by identifier and live param set to false, a content with non-live version

Both cases should return an empty list.
Otherwise, the live version should be returned if apply

**Comment by dsilvam** [comment] 2019-09-25 21:55
Needs work:
Relationships are being returned when cache is empty but after the first request is made, the subsequent requests return 0 relationships until cache is flushed.

To test you can use:
`/api/content/depth/2/language/2/id/<your-identifier>`

**Comment by nollymar** [comment] 2019-09-26 16:11
Good catch @dsilvam . Fixed in https://github.com/dotCMS/core/pull/17369

**Comment by erickgonzalez** [comment] 2019-10-01 22:58
https://github.com/dotcms/core/issues/16917#issuecomment-535238003 This is working as it should, relationships are pulled regardless the cache is empty or not.

**Comment by bryanboza** [comment] 2019-10-17 17:20
Fixed, unable to reproduce in the last master. Now this works as expected

**Closed** 2019-11-18 18:07 UTC
Labels: Cat : Content Management, Cat : Rest API, Doc : Needs Doc, Merged, Note to QA, Passed Internal QA, Release : 5.2.0, Severity : Support Requested, Type : Bug
