### ISSUE TITLE
[Site Copy] : Copying a Site randomly fails

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#21204] opened 2021-10-27 18:30 UTC
Reported via Support: [105577](https://dotcms.zendesk.com/agent/tickets/105577)
Reproducible in dotCMS 5.3.8.4, 5.3.8.5

Copying a Site is randomly failing for both the customer, and the Support Team when trying to reproduce it. This problem was present since they were on version 5.3.8.4, and it seems like it's still present in 5.3.8.5.

**To Reproduce**
For more details, please reach out to me or Scott.

**Expected behavior**
The Job that takes care of the Site Copy operation needs to fire up without problems.

**Additional context**
Back when they were on dotCMS 5.3.8.4, I had sent them a Debug Plugin to troubleshoot the Site Copy operation. After adding poor man's debugging, it was noted that dotCMS would randomly fail to retrieve information of the new Site to be created from the database. This was causing the NPE stack trace in the log.

The temporary workaround was to sleep the Quartz Job for 3 seconds **BEFORE** retrieving the information of the "source" and "destination" Sites, and then carry on with the creation of the new Site. The "hack" was left in their previous 5.3.8.4 instance in order to verify if it worked or not.

**Comment by wezell** [comment] 2021-11-01 16:15
I think we need to fire the copy site job in a commit listener and possibly pull the site from the db and not from the index

**Comment by jcastro-dotcms** [comment] 2021-11-01 17:25
Temporary PR: https://github.com/dotCMS/enterprise/pull/837

**Comment by wezell** [comment] 2022-01-04 20:26
The fix for this is to only fire the CopyHost Job once the original db transaction is finished, e.g. in the ContentAjax.saveContent

```java
				final Contentlet contentToCopy =contentlet;
				if (UtilMethods.isSet(copyOptionsStr)) {
				   HibernateUtil.addCommitListener(()->{
				        copyHostContentUtil.checkHostCopy(contentToCopy, user, copyOptionsStr);
				    });
					
				}
```

**Comment by erickgonzalez** [comment] 2022-01-21 15:33
Also there is a EE PR https://github.com/dotCMS/enterprise/pull/847

**Comment by bryanboza** [comment] 2022-02-09 16:51
Fixed, unable to reproduce. Tested on release-22.02 // Docker // FF

**Closed** 2022-02-15 14:57 UTC
Labels: Type : Bug, Passed QA, Merged, Cat : Content Management, Severity : Support Requested, Passed Internal QA, Cat : Useability, LTS: Next, Release : 22.02, Maintenance Sprint, Release : 21.06.7
