### ISSUE TITLE
Local temp directory in containers grows without bound

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#25047] opened 2023-05-25 23:02 UTC
### Parent Issue

Perhaps this falls under the guise of "autoscaling"  as it relates to issues running dotCMS containers in kubernetes. 

We need to understand how dotCMS containers make use of local disk storage, which is often constrained. 

### Problem Statement

Cloud Engineering encountered issues caused by unexpectedly high use of "ephemeral storage" by dotCMS containers, which exhausted the local disk space on k8s nodes. 

While a customer was adding new content comprised of large files, we found multiple containers had accrued many GB of temp files in
`/srv/dotserver/tomcat-9.x.x/temp`  - these files were about 50-200M in size and named `multipartSecxxxx.tmp`

@spbolton found these were from `MultiPartSecurityRequestWrapper` and we do not currently clean up these temp files.

Additionally, this temp directory contains 3 subdirectories, I don't know if they have similar issues.
```
dotwebdav
fileinstall-7391651867672058230
libjsass-16255251002222669212
```

### Steps to Reproduce

Add large files to dotCMS using the workflow API (I think?)

Check the size of the temp dir `/srv/dotserver/tomcat/temp` in the container

### Acceptance Criteria

Probably prune these files. Define and document the expected behavior of temp directories in containers.

### dotCMS Version

21.06

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

[Slack discussion](https://dotcms.slack.com/archives/G5VQBQ4H0/p1685022804658049)

**Comment by spbolton** [comment] 2023-05-26 00:07
The issue is that the MultiPartSecurityRequestWrapper creates a temp file for every multi part message over 1024*1000*50 bytes in size and this file is never removed.   In getInputStream when we have a file we pass it with return new ServletInputStreamImpl(new BufferedInputStream(Files.newInputStream(tmpFile.toPath()))) .  Part of the problem is that this class does not know when the stream has been full read and is available to be removed.   We should also handle deleting the file if there is an IOException related to it when we are processing it.   Using the DELETE_ON_CLOSE option is one way to catch the closing of the file.  Another option is to create our own InputStream wrapper that catches the input stream.  



```
try {
            return new ServletInputStreamImpl(new BufferedInputStream(Files.newInputStream(tmpFile.toPath(), StandardOpenOption.DELETE_ON_CLOSE)));
        } catch (IOException e) {
            Logger.error(this, “Error opening input stream from temporary file”, e);
            Files.deleteIfExists(tmpFile.toPath());
            throw e;
        }
```

Some of this functionality may be better handled with Apache Commons FileUpload as the above is not guaranteed to get cleaned up.  In particular the DiskFileItemFactory that handles using in memory vs on disk and FileCleaningTracker to handle cleaning up of temp files.


https://commons.apache.org/proper/commons-fileupload/using.html

**Comment by spbolton** [comment] 2023-05-26 00:19
dotwebdav does create temporary files that may get created if customer is using webdav,  Individual files may not be cleaned up during running of the app.  It does seem that the temporary files may not get removed.   A strange method is used to create this folder.   A random temp file is created then it looks at its parent path to then create the dotwebdav folder, deleting the original random tempfile.   The random tempfile is placed in the system property System.getProperty("java.io.tmpdir") so you don't need a temp file to find this.    I cannot see that the temp files created in this folder are ever removed.

**Comment by yolabingo** [comment] 2023-08-24 01:53
commenting to un-stale

**Comment by spbolton** [comment] 2023-08-25 15:35
@wezell I think we should prioritize this put in the work for the commons fileupload as it will help with security maintainability of any of our file uploads.

**Comment by spbolton** [comment] 2023-08-25 15:53
@yolabingo we can configure the location of the tomcat temp which these files are being placed.   The folder should be clear on restart of the pod, but will build up if pod does not restart.  For security it should be ensured there is no execute permission.   As a temporary measure if we do not want to restart the pods we could have a process to delete old files in the folder.   Nothing should stick around in the temp folder and is mainly used as a staging point as files are uploaded etc.   As such it can be difficult to know exactly when the system has finished with the file but in general it should not be multiple hours and if the system is still expecting a file to be there after a day then there is a problem in the design.   The comons fileupload has a component that cleans up the files it creates but the other are dealt with separately.    We should fix the code not to leave files lying around but I can understand a background process or a cron to clean up may be a good mechanism especially if it can warn what files it is cleanup up that are sitting around too long that would help us to identify the code that should be fixed.

**Comment by spbolton** [comment] 2023-08-25 16:00
Note that while putting in a cleanup job to run daily for example would help the gradual buildup over time, if the customer uploads many files in a short period of time unless we are cleaning up as we go we will still use up a lot of space so need to handle this case.   Any testing should include uploading a large amount of files and making sure this folder does not have to be as large as the total amount of files uploaded.   As files are uploaded and processed they should be removed from the temp folder.

**Comment by wezell** [comment] 2023-08-25 16:04
Reference: #25677

**Comment by yolabingo** [comment] 2023-08-25 18:23
Perhaps, by default, dotCMS should use the "assets" dir for "tomcat temp"? This temp space is a per-application resource, but it is currently being shared by multiple dotCMS containers from multiple clusters that happen to share a k8s Node. Therefore, any single application cannot control its fate by ensure that purging "tomcat temp" will make more temp space available if other clusters/applications/customers have exhausted this shared resource.

On any dotCMS cluster, the "assets" volume will be a mounted NFS volume can possibly grow without bound (e.g. EFS), or at least should already have its available disk space monitored.

Anyone running containerized dotCMS cannot otherwise ensure adequate disk space on the k8s nodes/docker host without pre-emptively provisioning massive disks on those servers - which we would rather avoid and which would still be difficult to monitor. In the case of k8s, each node will contain disparate dotCMS applications - not multiple "dotCMS nodes" from a single dotCMS cluster.

**Comment by jcastro-dotcms** [comment] 2024-07-08 21:38
I tried reproducing this issue in a local environment -- using both the source code and the Docker image -- but was not able to. Here are my findings:

I tried uploading a 835MB video via the back-end, and the Workflow REST Endpoint. When the `/temp/` folder is pointing to the one inside Tomcat, I can see several temporary files being created during the upload/saving process. However, once the File Asset is created inside dotCMS, all of those temporary files disappear as expected. I tried cancelling the request and even manually bringing the server down while the upload request was in progress, but the `/temp/` ended up without the temporary files.

Then, I set the property just like Todd mentioned:
```
CATALINA_TMPDIR: /data/shared/assets/tmp_upload
```
But in this case, the 835MB temporary file was not removed. I'm not sure whether I need to wait more time, but setting the temporary folder location outside of Tomcat seems to be causing that the temporary file does not get deleted right after the File Asset is created.

Now, the `BinaryCleanupJob` is set to run using the following default CRON Expression:
```
0 */3 0 * * ?
```
Which can be translated to:
```
At second :00, every 3 minutes starting at minute :00, at 00am, of every day
```
And it will delete all files inside the `/tmp_upload/` and the `$TOMCAT_HOME/tmp/` folders that are older than 3 hours, by default. We can bring this number down as well, if necessary.

**Comment by jcastro-dotcms** [comment] 2024-07-09 17:05
As per discussion with Steve Bolton, we can mark this issue as `Resolved` for now. Adjusting the CRON expression and config props for the `BinaryCleanupJob`, and the local storage in the k8s nodes helped solving this problem. It hasn't been reproducible since then.

Moreover, replacing the `MultiPartSecurityRequestWrapper` with the use of the Commons Upload component will be taken care of in another ticket.

**Closed by jcastro-dotcms** 2024-07-09 17:05 UTC
Labels: Type : Defect, Team : Falcon, OKR : Code Maintenance, OKR : Customer Support
