### ISSUE TITLE
Push Publishing users fails

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#8392] opened 2015-11-25 22:11 UTC
I just tested this on 3.2.4 on demo.dotcms.com

Easy to reproduce:
1) Create a new user
2) Right click the new user and add to a bundle
3) Try to upload the bundle to the same server - fails with the following message
Failed to publish because an error occurred: non valid bundle

**Comment by DeanGonzalez** [comment] 2015-11-25 22:12
This fails when uploading the bundle to another server as well - FYI

**Comment by john-thomas-dotcms** [comment] 2015-11-30 13:30
Reproduced in 3.3 nightly 11/25, but only for uploading the bundle to the same server where it was created.  I was able to successfully upload the bundle to a different server in 3.3.

**Comment by dsilvam** [comment] 2016-06-10 17:34
This is because of License validation, can't upload a bundle in the same server that generated it, and can't also if they are different servers but use the same licenseId. We need to get a more descriptive message https://github.com/dotCMS/core/issues/8989

**Comment by dsilvam** [comment] 2016-06-14 18:08
We now have a better message to understand the cause of the issue. See #8989. Closing this one.

**Closed by dsilvam** 2016-06-14 18:08 UTC
Labels: Type : Bug
