### ISSUE TITLE
no vertical scroll in Settings -> Apps

### ISSUE THREAD

**Issue by yolabingo** [dotCMS/core#27612] opened 2024-02-13 17:58 UTC
### Problem Statement

You cannot scroll down to see all installed apps in Settings -> Apps.
Workaround is to zoom out in the browser, or to search by app name to filter apps.

### Steps to Reproduce

See apps on demo https://demo.dotcms.com/dotAdmin/#/apps

### Acceptance Criteria

Be able to scroll down to view all installed apps.

### dotCMS Version

- latest
- 23.10 LTS
- maybe others?

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

<img width="1386" alt="Screenshot 2024-02-13 at 10 55 09 AM" src="https://github.com/dotCMS/core/assets/628954/6805d818-37fb-4264-8e05-0a860eb2a799">
<img width="1370" alt="Screenshot 2024-02-13 at 10 54 52 AM" src="https://github.com/dotCMS/core/assets/628954/e4d0a6c7-68c4-420f-884e-8f1a23303371">

**Comment by erickgonzalez** [comment] 2024-03-04 15:40
dupe of https://github.com/dotCMS/core/issues/26834

**Closed by erickgonzalez** 2024-03-04 15:40 UTC
Labels: Type : Defect, Triage, OKR : Customer Support, Team : Bug Fixers
