### ISSUE TITLE
Need to create postman test for the promote endpoint 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#25592] opened 2023-07-21 17:53 UTC
### Problem Statement

As part of the rules, every new endpoint should have the postman test in order to have a good testing coverage in our CI/CD process, after create this endpoint we don't add those test. 

### Steps to Reproduce

Promote Experiments API

### Acceptance Criteria

- Positive tests
- Negative tests
- Validate response codes 

### dotCMS Version

Tested on master // Docker // FF 

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment] 2024-02-15 15:48
Duplicate of https://github.com/dotCMS/core/issues/26208

**Closed by john-thomas-dotcms** 2024-02-15 15:48 UTC
Labels: Type : Test Automation, Team : Falcon, dotCMS : Experiments, Priority : 3 Average
