### ISSUE TITLE
Duplicate Langauge Keys break Keys resource

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#26688] opened 2023-11-15 15:28 UTC
### Problem Statement

If there are 2 language keys that share the same key it causes the language resource and thus the whole backend to fail with the message

![Screenshot 2023-11-15 at 10 16 55 AM](https://github.com/dotCMS/core/assets/934364/5ce6e837-14e5-49f8-b08f-1fb0c70eddcb)

The failing resource is this one:
https://local.dotcms.site:8443/api/v2/languages/default/keys

### Steps to Reproduce

- Remove the "unique" property of the language key content type.   
- Add two language keys with the same key.   
- Hit the resource https://local.dotcms.site:8443/api/v2/languages/default/keys

Because our uniques use the index rather than the database,  this can happen when language keys (as content) are being inserted simultaneously  and the unique constraint is not respected because the index is not up to date - like when an OSGI plugin adds language keys in its Activator method and the plugin is installed in a 3 node cluster - each node runs the activator the same time and tries to insert the new language keys. 

### Acceptance Criteria

We should ignore duplicate language keys and our API not fail.

### dotCMS Version

23.10

### Proposed Objective

Reliability

### Proposed Priority

Priority 2 - Important

**Comment by erickgonzalez** [comment] 2023-11-15 15:30
Dupe of https://github.com/dotCMS/core/issues/24082

**Closed** 2023-11-15 15:31 UTC
Labels: Type : Defect, Triage
