### ISSUE TITLE
VanityUrls are inconsistent in a cluster

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17278] opened 2019-09-18 03:37 UTC
When running in a cluster, vanity urls can suddenly disappear and reappear, depending on the state of the cache.

We need to rewrite the VanityUrl cache completely, simplify it and load it eagerly

**Comment by jcastro-dotcms** [comment] 2020-04-28 16:05
PR including fix from Support: https://github.com/dotCMS/core/pull/18378/files

**Comment by dsilvam** [comment] 2020-04-30 15:37
PR: https://github.com/dotCMS/core/pull/18377

**Comment by nollymar** [comment] 2020-05-26 21:49
**Note to QA:** These changes haven't been merged yet because VanityURLs need to be tested carefully before merging it.

**Comment by wezell** [comment] 2020-06-02 18:13
@fmontes this needs internal QA

**Comment by DannyGloudemans** [comment] 2020-06-07 12:44
Hi @wezell,

We are experiencing similar issues in dotCMS 5.2.6. We were able to reproduce this issue in both a single and clustered instance. We've tried to fix it with creating a hotfix plugin of the merge request: https://github.com/dotCMS/core/pull/18378/files.

However, this 'hotfix' will put the vanity URLs in a timed cache, in other words if the issue occurs it will only occur for X-seconds, however this doesn't resolve the actual issue or did we miss a part of the merge request to resolve the issue?

Thank you

**Comment by bryanboza** [comment] 2020-06-29 22:24
Fixed, tested on release-5.3.3 and I'm unable to reproduce

**Closed** 2020-06-30 15:05 UTC
Labels: Cat : Clustering, Cat : Performance, Merged, Note to QA, Passed Internal QA, Passed QA, Release : 5.3.3, Severity : Support Requested, Type : Bug
