### ISSUE TITLE
Unable to edit other languages from on-default-language page

### ISSUE THREAD

**Issue by m27iu4** [dotCMS/core#27404] opened 2024-01-23 14:18 UTC
### Problem Statement

- if we create a page in default language, the other languages of the same page can also be accessed in edit
- if we create a page in a non-default language, we are unable to access other languages of the same page

Impact- We have to manually create the pages for other languages, if we are creating a page from a non-default language.

Result: We get a page not found / redirected to listing page.
Expected: We should be able to see the default page.

- i tested the above and when you are in the ESP page and choose English it will pop up a URL not found error, which is not happening when you do it for the english page
- it should switch from 2Fspanish&language_id=2 to 2Fenglish&language_id=1
- it works the other way around though: 2Fenglish&language_id=1 to 2Fspanish&language_id=2

### Steps to Reproduce

Create a new page (Home Page) for a non-default locale (Spanish).
Switch locale back to the default (English).

### Acceptance Criteria

We have to manually create the pages for other languages, if we are creating a page from a non-default language.

### dotCMS Version

22.03.13 lts

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/114932

**Comment by erickgonzalez** [comment] 2024-01-23 15:04
Dupe of https://github.com/dotCMS/core/issues/27281

**Closed by erickgonzalez** 2024-01-23 15:04 UTC
Labels: Type : Defect, Triage
