### ISSUE TITLE
Problems with WebDAV locking code

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/core#16018] opened 2019-02-12 13:19 UTC
WebDAV code is locking based on contentlet inode.  When debugging another issue I noticed that the inode of the initial contentlet version is locked but when unlocked is called, it is passing in the inode of the new version of the contentlet.  This has two results:
* WebDAV locking is not really working on contentlets
* this list of open locks continues to grow until the server is restarted

Please note that the locks Map is not thread safe:  https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/webdav/DotWebdavHelper.java#L1185

Since these locks are only in memory, they would seem to not have the desired affects in a multinode cluster.  Is this locking necessary, if so it also needs to work in a multinode cluster

While you are in the code, please remove the HashTable resourceLocks as it is not used at all:  https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/webdav/DotWebdavHelper.java#L106

## Possible Solution

Given that the content locks have not worked properly in some time (if ever), are not threadsafe, and don't seem to have the desired affect in a multinode cluster, not sure they are necessary.  Can this locking code just be removed?  Perhaps the locking is needed on folders but not on contentlets?

**Comment by fabrizzio-dotCMS** [comment] 2019-02-28 17:52
@brentgriffin Can you please describe what actions you performed to trigger the lock-unlock mechanism. I added a ton of debugging code inside of the following methods 
`
 public final LockResult lock(LockTimeout lockTimeout, LockInfo lockInfo, String uid) 
 public final LockResult refreshLock(String uid)	
 public void unlock(String uid)	 
 public final LockToken getCurrentLock(String uid)
`
Did a bunch of stuff (upload, deletes, renames)  via cyberduck client. And the onlyone method that see that gets triggered is  `getCurrentLock`

**Comment by wezell** [comment] 2019-02-28 18:36
Fabrizio - it is an old and long standing issue. Not sure how to reproduce,
but please rip that lock crap out :)

**Comment by brentgriffin** [comment] 2019-02-28 19:08
@fabrizzio-dotCMS - as we discussed, just created a text, vtl file and made changes to it in an editor - each save was triggering the lock and unlock behavior

**Comment by brentgriffin** [comment] 2019-02-28 19:09
not sure if client makes a difference or not - I (and the client) was using OSX Finder for the client

**Comment by fabrizzio-dotCMS** [comment] 2019-02-28 19:30
I think the client definitely does make a difference. 
Cyberduck does not trigger anything while Finder locks and unlock almost after every single action. 
That was certainly helpful. Thx!

**Comment by fabrizzio-dotCMS** [comment] 2019-03-01 20:40
There is a huge difference between how the two WebDAV clients (Finder, Cyberduck) interact with the dotCMS WebDAV implementation. In fact, it looks like Cyberduck doesn't care at all about locking and unlocking it almost seem like if it was a different protocol. I turned on logging and for `com.dotcms.repackage.com.bradmcevoy.http` and the traces are completely different. 

I tried a few options here to disable the Locks. First I tried removing these two interfaces `LockableResource, LockingCollectionResource` from all the relevant resource classes and that brakes the functionality completely on mac-finder though it doesn't seem to affect Cyberduck whatsoever.  Also tried making all the methods that return a `LockResult` return `null`. That also breaks the functionality making NPE pop-up everywhere.  

Looks like the best and cleanest option is making ` DotWebdavHelper.LockToken getCurrentLock(String uid)` always return `null`

This has an effect on the upper-level method `com.dotcms.repackage.com.bradmcevoy.http.HandlerHelper.isLockedOut(Request inRequest, Resource inResource)` where nothing is ever marked as locked again.

The old static non-threadsafe map that was used to keep `LockToken` references was removed.

**Comment by fabrizzio-dotCMS** [comment] 2019-03-01 20:42
![screen shot 2019-03-01 at 10 52 31 am](https://user-images.githubusercontent.com/37148755/53665090-0e729d80-3c30-11e9-99bd-571cf282e1db.png)
This is what it looks like if I remove the two interfaces 
`LockableResource, LockingCollectionResoure` or change the other methods to return null.

LockableResource, LockingCollectionResource
LockableResource, LockingCollectionResource

**Comment by fabrizzio-dotCMS** [comment] 2019-03-01 20:48
Also These classes `FsResource` `FsFileResource` make use of a `FsMemoryLockManager`
But they don't seem to be used whatsoever.  I think they're dead code but I'm, not 100% sure.

**Comment by jgambarios** [comment] 2019-03-04 14:41
PR: https://github.com/dotCMS/core/pull/16159

**Comment by bryanboza** [comment] 2019-03-11 22:37
After the last changes, we are unable to reproduce if you are working with Cyberduck, but if you are working with finder we have multiple errors...

- Editing some file https://www.screencast.com/t/mUe0DRKD
_Also this is crashing the file_ https://screencast.com/t/95xmHMz6i

- Uploading files https://gist.github.com/bryanboza/d81a1af21e2be3227f2f20cb890c4040

We need to fix that error if continue supporting finder as WebDAV client

**Comment by jgambarios** [comment] 2019-03-11 22:46
The errors described above by Bryan happen even without these recent changes, the fixes on this ticket are not related to those errors.

**Comment by jgambarios** [comment] 2019-03-14 16:07
The described issues reported by Bryan will be fix in: https://github.com/dotCMS/core/issues/16231

**Closed by jgambarios** 2019-03-14 16:07 UTC
Labels: Passed Internal QA, Release : 5.1.0, WF : Merged, WF : Needs Work
