### ISSUE TITLE
Navtool fails to re-populate the menus after a cache refresh

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#20032] opened 2021-03-03 23:02 UTC
## Describe the bug

When clearing cache, navtool doesn't attempt to repopulate the navigation tree.

_As reported in comments by the original filer in https://github.com/dotCMS/core/issues/19926._

### Comment 1 (https://github.com/dotCMS/core/issues/19926#issuecomment-775523448):
```
When clearing cache, navtool doesn't attempt to repopulate the navigation tree. In order for navigation to repopulate:

Visiting the individual site browser folders will get the corresponding link to populate.
(not shown) In order to get links to populate, they have to be republished from what I can tell.
```

https://user-images.githubusercontent.com/9543257/107292550-0b959f80-6a38-11eb-8fbb-fc86e8b5e25f.mp4

### Comment 2 (https://github.com/dotCMS/core/issues/19926#issuecomment-777055525):
```
In 21.01 after dumping caches, in addition to the NPE on page requests, most nav entries disappear as shown in the video. The missing nav entries could reappear after viewing the folder/page properties in site-browser. If that didn't work, republishing the folder/page would get them to reappear.

In 5.3.8.2, after dumping caches, most nav entries disappear in the same manner as 21.01, there is no NPE on page requests. However, using the same trick for the nav doesn't appear to fix the problem. I have been unsuccessful in getting the navigation to reappear. I have tried republishing, disabling and enabling the "Show on Menu" option for folders and Page Assets. This is the same environment, deployed with the starter site "starter-20201119.zip".

In addition, I verified that "CMS Anonymous" has read access to the missing items, along with "Show on Menu" being enabled.

"TravelLux" navigation after dumping caches:
```

https://user-images.githubusercontent.com/9543257/107576301-f26b2b00-6bbe-11eb-83de-1e7117b51fea.png

## *Expected behavior

After a cache refresh, navtool should display results correctly, pulling results from the DB to repopulate the cache.

## Additional context

Support Ticket: https://dotcms.zendesk.com/agent/tickets/103548

**Comment by dsilvam** [comment] 2021-07-09 15:23
Unable to reproduce by testing as shown in the video. Tried on versions `21.01`, `21.07-prerelease` and current `master`.

**Comment by bryanboza** [comment] 2021-07-20 19:40
Fixed, tested on master and release branch and we are unable to reproduce, seems this was fixed in another card

**Closed** 2021-07-27 19:13 UTC
Labels: Passed QA, Severity : Support Requested, Type : Bug, WF: Can't reproduce
