### ISSUE TITLE
Permissions: Limited user cannot edit host from site browser, site portlet only

### ISSUE THREAD

**Issue by levosgien** [dotCMS/core#8758] opened 2016-03-16 15:50 UTC
Ref: https://my.dotcms.com/tickets/detail.dot?id=6bddbdd5-ef81-4b08-a2a0-97639b5e738a
Version: 3.3
Test: demo.dotcms.com

When a limited user is given permissions to edit a host, right-clicking on the host from the site browser tool does not work or show and sub-menu. However, this same user can properly edit and right-click that same host form the "Sites" tool.

![cannot edit host in site browser](https://cloud.githubusercontent.com/assets/1823543/13818680/3eee732e-eb6d-11e5-9773-6b5f29f696cc.gif)

**Comment by jgambarios** [comment] 2016-03-21 19:16
I was unable to reproduce the issue in latest **3.3.1** with **postgres** and **Firefox**

![permissions](https://cloud.githubusercontent.com/assets/923947/13931033/135e1716-ef67-11e5-83ca-8302f04562f3.gif)

**Comment by jgambarios** [comment] 2016-03-21 19:21
Looks like is was fixed in #8443 for **3.3.1**

**Closed** 2016-03-21 19:50 UTC
Labels: Type : bug
