### ISSUE TITLE
[UI] Add new Goal Type CLICK_ON_ELEMENT

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#22986] opened 2022-09-14 16:47 UTC
### User Story
As a user,
I want to be able to add a new goal type called "CLICK_ON_ELEMENT" to the Experiments Configuration,
So that I can track and analyze user interactions specifically related to clicking on elements within my experiments.

### Acceptance Criteria
- When you Select Click On Element, the default Goal Name is `Track users interaction`
- When you click on the Goal type, you can see the condition's inputs
- All the conditions are required
- Parameter input is a select option required with the list: `Class` and `Id`
- Value is a string input required

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

New Goal: Click On Element
<img width="1409" alt="Screenshot 2023-06-01 at 11 56 22 AM" src="https://github.com/dotCMS/core/assets/1909643/24cecf48-f772-495b-87e3-11e0ffbd50dd">

Configuration

<img width="823" alt="Screenshot 2023-06-01 at 1 18 17 PM" src="https://github.com/dotCMS/core/assets/1909643/2d2f3970-fe0d-4043-9697-7c0cfd51ae53">

**Comment by oidacra** [comment] 2022-09-14 18:16
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Falcon-6176e9d907eb0000106ee8e1/issues/dotCMS/core/22986?planning-poker) with Zenhub @alfredo-dotcms @fmontes @hmoreras @rjvelazco

**Comment by john-thomas-dotcms** [comment] 2023-10-09 14:41
Duplicate of https://github.com/dotCMS/core/issues/25026

**Closed by john-thomas-dotcms** 2023-10-09 14:41 UTC
Labels: dotCMS : Admin Tools, Team : Falcon, dotCMS : Experiments
