### ISSUE TITLE
Add a app system folder under WEB-INF/apps

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18880] opened 2020-07-14 18:52 UTC
This folder will hold the yaml files that we ship with.  We should also read the files in the asset/server/apps folder and merge the results as our available apps.

System folder app should take precedence over apps in the `asset/server/apps` folder

**Comment by nollymar** [comment] 2020-07-27 15:41
Dupe of: https://github.com/dotCMS/core/issues/18939

**Closed** 2020-07-27 15:42 UTC
