### ISSUE TITLE
Push Publishing: Exception if Assignable (user/role) from Workflow Task does not exist on Receiver side

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#9767] opened 2016-09-09 21:10 UTC
If a Content tied to a Workflow Task gets pushed, the Workflow-related info is pushed as well. However, depending on the current Assigned To value for the content being pushed, it fails if the user/role does not exist on the other endpoint.
## Expected Behavior

The expected behavior should be one of the following:
- Assign the current Workflow Task the content is tied to, to a system user/role (which we knows it exists on both endpoints).
- Push the Assigned to User/Role as dependency once the Content tied to a Workflow Task is pushed.
- Push the Workflow Scheme and all its dependencies (including roles/users) before dealing with contents.
## Current Behavior

The Push Publish task fails. Stacktrace: https://gist.github.com/joseorsini/ddecda60bc4b0e0d8e374eac5afcc114
## Known Workarounds
- Push the User/Role.
- Edit the current Workflow Task and assign it to users/roles that exist on the Receiver side, then resolve it.
## Steps to Reproduce
1. Set up a Push Publishing environment: 1 Node for Sender, 1 Node for Receiver, both running same version of dotCMS.
2. In Sender side, create an user. For testing purposes, the user is called "Jose Orsini".
3. Open the Document Management Workflow Scheme
4. Under "Legal Approval Step", edit the "Assign To" field and select "Jose Orsini. Add "Push Publish" as a sub-action of this same step.
5. In Website Browser, add a Document under /about-us/. Upload a file and click on "Send to Legal".
6. Reopen the same content and then click on Publish. The Push Publish Dialog box will pop up, so select a Push Date/Time and the Receiver environment. Click on "Push".
## Context

Related to Support Tickets: 
- https://my.dotcms.com/tickets/detail.dot?id=77c65881-82b0-43c0-9b0f-5f4ea2abf6e1
- https://my.dotcms.com/tickets/detail.dot?id=117feff5-738c-4bb9-a16d-87cc604796bd
## Your Environment
- dotCMS Distribution Version (3.5.1 and 3.6.0).
- Google Chrome Version 52.0.2743.116 (64-bit).
- Mac OS X El Capitan Version 10.11.6.
- Built-in Tomcat Application Server.
- Java 8.
- Postgres version 9.4.1.

**Comment by joseorsini** [comment] 2016-11-14 16:53
Since the integrity checker includes a new feature that solves conflicts with Roles (as per [this ticket](https://github.com/dotCMS/core/issues/9793)) it would be important to include Roles as objects that can be pushed. 

This is affecting customers using Push Publishing and Workflow Schemes, since creating all required roles on both endpoints may end up in doing the same operations, twice. By pushing roles, it's easier to make consistent content management workflows that would involve user actions on both endpoints. Any potential issue with Roles definition is already covered by the Integrity Checker.

**Comment by jcastro-dotcms** [comment] 2017-06-09 21:15
@wezell from the 3 potential solutions to the problem that @joseorsini mentions, which one do you want to go with?

For example, when pushing a content whose user does not exist in the receiver environment, we're just setting it to "system" in order to solve the user-missing issue. In this case, is that a valid fix?

**Comment by jcastro-dotcms** [comment] 2017-06-12 17:43
As discussed with @wezell @jtesser @jgambarios the fix for this issue will be the first approach proposed by @joseorsini : "Assign the current Workflow Task the content is tied to, to a system user/role (which we knows it exists on both endpoints)."

**Comment by jcastro-dotcms** [comment] 2017-06-14 17:11
PR: https://github.com/dotCMS/enterprise-2.x/pull/472

**Comment by bryanboza** [comment] 2017-06-20 19:06
Fixed,  tested in the last master // postgres... This to both environments, and after the last changes, now we are able push the document without problems, also the WF step is pushed, but now we assign that to the CMS Administrator role... Then now we don't have problems with this case....

**Comment by bryanboza** [comment] 2017-06-20 20:58
After the meeting discussion, we should use the property of the card #11559, to make that, because is the same concept... Also we need set that property to true by default...

**Comment by jcastro-dotcms** [comment] 2017-06-21 14:09
PR core: https://github.com/dotCMS/core/pull/11955
PR enterprise: https://github.com/dotCMS/enterprise-2.x/pull/478

**Comment by jgambarios** [comment] 2017-06-21 20:43
@john-thomas-dotcms this is related to https://github.com/dotCMS/core/issues/11559 and the ```HEADLESS_USER_CONTENT_DELIVERY``` property that now by default is set to **TRUE**, please contact @jcastro-dotcms to get more detail about this change, also the comments here can help you to update the doc https://github.com/dotCMS/core/pull/11955/files#diff-9eef290d7e7caa46fa38e7f59dfe65cdR845

**Comment by bryanboza** [comment] 2017-06-22 21:22
Ok... @jcastro-dotcms, @jgambarios, after do some testing with this property we still having problems because maybe we are misunderstanding the expected behavior... 

**Right now:**
- If the property is true, the system is sending the document without problems, and assigning to system user. (that case is ok)

- If the property is false and the user does not exist on receiver, the system is failing at all, and shows the original stack trace and the push is not completed: https://gist.github.com/joseorsini/ddecda60bc4b0e0d8e374eac5afcc114

- If the property is false and the user exist on receiver, we are not failing, the push is complete, but we are not assigning this to the user... 
Sender: https://screencast.com/t/hKsje0jqOhh0
Receiver: https://screencast.com/t/hmJ65jQO

**Expected:** 
- We have two options, push and show a type of WARN in the log because does not exist the user on receiver, and assign to system user. 

or

- Just fail and show the current stack trace.

Not sure what do you think here @wezell....

**Comment by bryanboza** [comment] 2017-06-23 20:03
Fixed, tested on master-4.1 // Postgres... This on both environments... Now if the property is set to **true** the system use the system user and if is false and the user doesn't exist the is trowing the exception...

**Comment by john-thomas-dotcms** [comment] 2017-06-28 12:43
I believe this is already documented here: https://auth.dotcms.com/docs/latest/push-publishing-permissions#headless.  From the information on this ticket, I don't think any additional documentation is needed, but please let me know if it is.

**Closed** 2017-07-21 23:54 UTC
Labels: Agile : Discuss for Release, Cat : Push Publishing, Doc : Documented, Release : 4.2.0, Severity : Support Requested, Type : Bug, WF - Passed QA - P8, WF : Merged, WF : Passed QA
