### ISSUE TITLE
Search And replace Utility doesn't work properly

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#26836] opened 2023-11-29 18:08 UTC
### Problem Statement

When using Search and Replace utility, it doesn't replace content. Most probably, It doesn't work in recent version because of dotCMS changed content saving as JSON format.

Here is doc https://www.dotcms.com/docs/latest/search-and-replace-utility

### Steps to Reproduce

Pick a text and replace it with some other text. It won't be replaced.

### Acceptance Criteria

String and replace utility should replace text

### dotCMS Version

23.1.7-23.10.24

### Proposed Objective

Customer Support

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/114215

**Comment by erickgonzalez** [comment] 2023-12-28 22:09
Dupe of https://github.com/dotCMS/core/issues/25576

**Closed by erickgonzalez** 2023-12-28 22:09 UTC
Labels: Type : Defect, Triage, OKR : Customer Support
