### ISSUE TITLE
Moving Folders

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#21801] opened 2022-03-02 19:56 UTC
Folders should always have the knowable/consistant id.

If someone wants to "move" a folder, we should not update the folder record. Instead, we should create a new folder record that has the correct id generated and delete the old folder / identifier when done.

I believe we will also need to update the info in the permission/permission_reference table as well.

**Comment by nollymar** [comment] 2022-03-15 00:35
PR: #21851

**Comment by fabrizzio-dotCMS** [comment] 2022-03-30 18:00
Notes: 
When moving/copying a folder the resulting mod_user is the system user while the expected should be the current logged in user.
when a folder contains archived items the move/copy operation gets aborted by an exception like `Caused by: com.dotmarketing.portlets.contentlet.business.DotContentletStateException: Unable to check-in an archived piece of content, please un-archive first` This behavior exists in demo. At least we should report the exception in the front end. Or fix it during move.
When reaming a folder that contains archived items the same thing happens. The check-in operation fails. However, this should be fixed by this PR  https://github.com/dotCMS/core/pull/21905

**Comment by bryanboza** [comment] 2022-04-05 00:03
- We are unable to get the individual permissions of an individual file that is under a folder that you has been moved 
![image](https://user-images.githubusercontent.com/2641437/161649704-b7fc62c8-7e9b-4ea1-91ed-7cb5a51a086f.png)

- We need to auto refresh once the folder has been moved, right now we made a kind of refresh but after this, we are showing the folder in both locations, then if you try to open any of those we are getting a JS error 
![image](https://user-images.githubusercontent.com/2641437/161651813-ead52aa0-c5b2-4436-aa0a-454dc20953d7.png)

**Comment by bryanboza** [comment] 2022-04-05 15:21
@nollymar  we don't need some specific steps, just cut the folder from one folder and paste in another path, that's it.

**Comment by bryanboza** [comment] 2022-04-06 21:30
We have a new case here: 

- If you cut and paste multiple times quickly some folder, at some time we are leaving something dirty and you are unable to move this folder again. We are showing an SQL error 
Here the log: https://gist.github.com/bryanboza/4118c8d5a100b002cbcb824f61df5788
![image](https://user-images.githubusercontent.com/2641437/162074520-7f9f0e2d-dc70-4e40-a864-6325197400d1.png)

To reproduce: 
- Login as admin 
- Create a new folder and upload some file 
- Cut/paste to another path quickly multiple times 

Note: Not sure if can be related to the DB, I'm testing on MSSQL

**Comment by nollymar** [comment] 2022-04-08 23:39
PR with the fix: #21999

**Comment by bryanboza** [comment] 2022-04-20 20:16
Now we are unable to reproduce the SQL error when you are moving a folder, the refresh problem will be moved to a new card. 

Fixed, tested on release-22.04 // Docker // FF

**Closed** 2022-04-26 18:09 UTC
Labels: Type : Enhancement, Passed QA, Merged, Passed Internal QA, Team: Scout, Release : 22.04
