### ISSUE TITLE
Permissions Tab spins for well over 45 seconds in Chrome

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#24262] opened 2023-03-02 18:45 UTC
### Problem Statement

Using the latest Chrome browser first clear all caches, then edit a content Type and click on Permissions tab for the Content Type.  The browser will spin and not reveal the permissions screen.  Here is a video:

https://user-images.githubusercontent.com/1569167/222522062-94c1e578-dafd-4156-bedb-4bf26c8f6790.mp4

I did see an error in the Browser error console:

```
VM745 dojo.js:2 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Object.setStyle [as set] (VM745 dojo.js:2:73820)
    at Object.setStyle [as set] (VM745 dojo.js:2:73862)
    at dojo.style (VM745 dojo.js:2:95651)
    at loadPermissions (permissions.jsp?contentTypeId=799f176a-d32e-4844-a07c-1b5fcd107578&popup=true&in_frame=true&frame=detailFrame&container=true&angularCurrentPortlet=content-types-angular:379:8)
```

The version of Chrome I was using to test was:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/1569167/222522255-91e603a9-fca5-47a3-95fe-3a20e0e3f743.png">

### Steps to Reproduce

See above

### Acceptance Criteria

Permissios screen should load in a second or two at maximum

### dotCMS Version

Tested on demo.dotcms.com running 23.02 and also on the 22.03.4 LTS version

### Proposed Objective

Application Performance

### Proposed Priority

Priority 1 - Show Stopper

**Comment by damen-dotcms** [comment] 2023-03-02 19:05
Dupe of https://github.com/dotCMS/core/issues/23889

**Closed by damen-dotcms** 2023-03-02 19:05 UTC
Labels: Type : Defect, Triage
