### ISSUE TITLE
Using Scroller on Host field disables selecting subfolders

### ISSUE THREAD

**Issue by joseorsini** [dotCMS/core#7193] opened 2015-02-05 15:55 UTC
Related to https://github.com/dotCMS/core/issues/2703 and reproduced in demo.dotcms.com (3.0.1) and demo2.dotcms.com (2.5.7). 

Steps to reproduce:

1. Try to create a new Event or any content that has a Host/Folder field.
2. Open the Host dropdown and drag the scroll bar once you have expanded the demo.dotcms.com host.
3. Try to expand one of its children folders and it will automatically set the dropdown's focus to the host.

Screencast provided by client: http://goo.gl/tlljfa

Reproduced in Safari 8.0.3, Firefox 35 and Chrome 40.0.2214.94 (64-bit).

**Comment by levosgien** [comment] 2015-02-05 16:07
This shows as closed as 2.3 so it was either not resolved or broke again later, as per https://github.com/dotCMS/core/issues/2703

**Comment by fusion27** [comment] 2015-02-05 16:38
@joseorsini 

* I wasn't able to reproduce in FireFox (it worked as expected), but could in WebKit browsers ([Chrome](https://trello-attachments.s3.amazonaws.com/53188d79bd0813e43e490216/548a1264526a240bffabff79/c4622c045275119e346b9345bfbfe988/NaomiTrujillo-03.mp4) & [Safari](https://trello-attachments.s3.amazonaws.com/53188d79bd0813e43e490216/548a1264526a240bffabff79/e410e25306f69ea2f0f8c603d0e90b75/NaomiTrujillo-05_safari.mp4)).
* The developer that reported this to me also claimed that he was able to reproduce in on 3.x demo server as well.  I, however, didn't follow up as their production server is v2.5.4.

**Comment by jkshapiro** [comment] 2015-02-06 14:51
See also #6806

**Comment by rossie70** [comment] 2015-02-10 16:52
Any update on a hotfix for this.  We would love to have this fixed in our 2.5.4 environment.  Thanks!

**Comment by fusion27** [comment] 2015-02-16 13:58
We have a paying customer waiting on this bug fix.  They've been with you guys since 1.7.  They're feeling ignored driving down your perceived value.  If their patronage is of value you to you...

**Comment by levosgien** [comment] 2015-02-16 14:38
This has been slated for 3.1.1 which is currently in development as 3.1 is in QA. @fusion27 this means that this issue has been slated for our current development cycle, please let the client know in case there is any confusion.
Once this is marked as fixed please reach out to me for a hotfix and we'll get EE clients on recent codebase taken care of as we always do.

**Comment by fusion27** [comment] 2015-02-16 15:33
@levosgien thanks for the clarification, I'm forecasting that it'll be poorly received, but I'll let them know.

**Comment by jtesser** [comment] 2015-12-03 15:08
https://dotcms.mingle.thoughtworks.com/projects/dotcms/cards/62

**Closed by jtesser** 2015-12-03 15:08 UTC
Labels: Agile : Moved to Mingle, Cat : UI, Type : bug
