### ISSUE TITLE
Removing Content Images and checkbox properties is not updating the content

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#15443] opened 2018-10-17 17:20 UTC
Reproduces on dotCMS 5.0.2

We are apparently only checking for changes or additions to certain fields, but we are not checking to see if things like checkboxes or images have been removed only - which should certainly generate an update to the content and a new content version with images, checkbox values, removed.

The example below is with page content, but we need to make sure that removal of any content value updates the content and refreshes the cache.

https://www.screencast.com/t/qglK6LWn

**Comment by wezell** [comment] 2018-10-17 18:07
Closing, this is a dupe of #15353

**Closed by wezell** 2018-10-17 18:07 UTC
Labels: Type : Bug
