### ISSUE TITLE
Site Search doesn't include content from velocity file

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#17672] opened 2019-11-29 16:36 UTC
Reported via support ticket: [99862](https://dotcms.zendesk.com/agent/tickets/99862)
Reproducible in dotCMS 5.2.1

Site search indexes pages content by generating the HTML for the page and adding it to the index entry for the page. When a VTL file is included in the page using the `#dotParse()` directive, dotCMS will try find the VTL file for the language requested for the page and if a version of the file doesn't exist for that language, it will try to find the VTL file version for the default language. However, it fails to include the VTL file version for the default language, so the HTML generated for the VTL is not included in the Site Search index.

### Steps to reproduce the behavior:
1. Go to 'Site -> Browser' and add a new file 'test-container.vtl' under '/application/vtl/containers' folder. Add this code to the VTL file in order to include contentlet 'body' and 'title' fields:
```
<h2>$!{title}</h2>
<div>
$!{body}
</div>
```
2. Save and publish the 'test-container.vtl' VTL file created in the previous step.
3. Go to 'Site -> Containers' and create a new container called 'Test Container'. Add the 'Content (Generic)' content type to the container and enter a `#dotParse()` directive to include the VTL file from step 1 for the content type:
```
#dotParse('/application/vtl/containers/test-container.vtl')
```
4. Save and publish the 'Test Container' container created in the previous step.
5. Go to 'Site -> Templates' and create a new container called 'Test Template'. Include the 'Test Container' from the step 3 in the new template.
6. Save and publish the 'Test Template' template created in the previous step.
7. Go to 'Site -> Browser' and create a new page using the template created in step 5. The page should be created for a language different from the default language, for example Spanish language.
8. Edit the page created in the previous step and a new contentlet in the language used for the page, for example Spanish. Add some words to the contentlet, that should be included in the Site Search index.
9. Save and publish the page created in the step 7. Check that the HTML page content is being generated by looking the page in preview mode.
10. Go to 'Dev Tools -> Site Search' and create a new site search index with the alias 'testIndex'. Go to the 'Job Scheduler' tab and run a new job to add the new page to the site search index. Select the site where the page was created, and the language used to create the page.
The following warning message is shown in the log after the site search index job runs:
```
[29/11/19 02:10:00:538 GMT] WARN directive.DotParse: - unable to resolve /application/vtl/containers/test-container.vtl getting this: Not found LIVE version of [/application/vtl/containers/test-container.vtl] @ DotMarketingQuartzScheduler_Worker-15
[29/11/19 02:10:00:539 GMT] WARN directive.DotParse: - at com.dotcms.rendering.velocity.directive.DotParse.throwNotResourceNotFoundException(DotParse.java:156) @ DotMarketingQuartzScheduler_Worker-15
```
11. Go to the Search tab, select the 'testIndex' index, and search some of the words added to the page content. The search doesn't return results.

### Expected behavior
All the generated HTML content for the page should be included in the Site Search index. When the page being added to the index is for other language different from the default language, and there's a VTL file included using `#dotParse()` directive, the VTL should be parsed and the generated HTML should be included in the page. If the VTL file doesn't have a version in the language used for the page, the VTL file for the default language should be used.

## Possible Solution
This code from `com.dotcms.rendering.velocity.directive.DotParse` class tries to get the version information of the VTL file to be included by `#dotParse()` directive, using the language of the page. If the VTL file doesn't have a version for that language, the code will try to get the version information using the default language:

https://github.com/dotCMS/core/blob/dfe9d71901c09254ba8a6a7c445533aee98dedad/dotCMS/src/main/java/com/dotcms/rendering/velocity/directive/DotParse.java#L95-L104

In order to work when the VTL file only exists in the default language, the previous code assumes that the call to  `APILocator.getVersionableAPI().getContentletVersionInfo()` method returns `null` if the version information is not found for the specified language. However, the `getContentletVersionInfo()` method from the `com.dotmarketing.business.VersionableFactoryImpl` class has the following code:

https://github.com/dotCMS/core/blob/dfe9d71901c09254ba8a6a7c445533aee98dedad/dotCMS/src/main/java/com/dotmarketing/business/VersionableFactoryImpl.java#L282-L284

That causes an empty version info object being returned if the version information doesn't exists, instead of the expected `null` return.

### Additional context
This has been reported by customer via Support: Ticket [99862](https://dotcms.zendesk.com/agent/tickets/99862)

**Comment by dsilvam** [comment] 2020-04-14 23:54
Passed Internal QA: This is fixed in Master. Probably with latest fixes for Site Search

**Comment by bryanboza** [comment] 2020-04-21 21:45
Fixed, tested on the last master and I'm unable to reproduce

**Closed** 2020-04-28 20:00 UTC
Labels: Cat : Content Management, Merged, Passed Internal QA, Passed QA, Release : 5.3.0, Severity : Support Requested, Type : Bug
