### ISSUE TITLE
SALES: dotCMS Cloud | Self-services

### ISSUE THREAD

**Issue by stefan-dotcms** [dotCMS/core#24252] opened 2023-03-01 21:45 UTC
### User Story

See document: https://docs.google.com/document/d/1-XAyONflyGU-WVeO0rGovWNpisRpZpw9QJjFBbNTBWg/edit#

### Acceptance Criteria

See document: https://docs.google.com/document/d/1-XAyONflyGU-WVeO0rGovWNpisRpZpw9QJjFBbNTBWg/edit#

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

**Comment by damen-dotcms** [comment] 2023-03-02 15:22
Seems like a dupe of https://github.com/dotCMS/core/issues/24003 - I added the Google Doc reference to that issue.

**Closed by damen-dotcms** 2023-03-02 15:22 UTC
Labels: Type : New Functionality, Triage
