### ISSUE TITLE
Unable to use ' in email address

### ISSUE THREAD

**Issue by mattyarbrough** [dotCMS/core#13202] opened 2017-12-11 17:49 UTC
https://dotcms.zendesk.com/agent/tickets/94488
If you create a user with an email address that looks like this:

O'Connell@dotcms.com
DotCMS will display the error message that this isn't a valid email address. This is caused by the ' character in the email address. But according to RFCs for email this is a valid character for the local part of an email address.

Note this is a recurrence of the issue https://dotcms.zendesk.com/agent/tickets/94488

## Your Environment

* dotCMS version used: 4.1.1

**Comment by erickgonzalez** [comment] 2018-01-09 15:20
With the latest master, I'm not able to reproduce this issue. I can create the user with apostrophe successfully. 
![image](https://user-images.githubusercontent.com/5278970/34727926-03124648-f51e-11e7-8b1f-bcb036698cce.png)

This one is the regex for the email: https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotmarketing/util/Constants.java#L134 it includes the apostrophe.

**Comment by erickgonzalez** [comment] 2018-01-09 16:10
@mattyarbrough this was fixed in 4.2.0

**Closed** 2018-01-16 15:19 UTC
Labels: WF: Can't reproduce
