### ISSUE TITLE
Content detailed page throwing 404 when URL contains a trailing slash.

### ISSUE THREAD

**Issue by muhammadfaizandotcms** [dotCMS/core#23276] opened 2022-11-01 12:28 UTC
### Describe the bug
Content detailed page throwing 404 when URL contains a trailing slash.
Reproduced on 22.10
Related ticket: https://dotcms.zendesk.com/agent/tickets/108893
### To Reproduce
https://demo.dotcms.com/store/products/k2-mens-mindbender-99ti-skis Works fine
https://demo.dotcms.com/store/products/k2-mens-mindbender-99ti-skis/ throws 404

### Expected behavior
The detailed page should return the desired contentlet when a trailing slash exists
### Additional context
This behavior works fine on 21.06.*, 5.3.8.*

**Comment by yolabingo** [comment] 2023-01-24 18:10
This Rule may suffice in many cases to preserve the trailing slash behavior of URL mapped content after an upgrade. It obviously could be onerous if too many paths need to be matched.

It provides a 301 HTTP redirect from 
https://demo.dotcms.com/store/products/k2-mens-mindbender-99ti-skis/ 
to
https://demo.dotcms.com/store/products/k2-mens-mindbender-99ti-skis

<img width="1253" alt="Screenshot 2023-01-24 at 11 06 23 AM" src="https://user-images.githubusercontent.com/628954/214373209-8bc310f0-57e9-4569-97d4-04cc5c17c539.png">

**Comment by waqasakramdot** [comment] 2023-04-20 12:50
Another ticket https://dotcms.zendesk.com/agent/tickets/111098

**Comment by swicken-dotcms** [comment] 2023-05-19 13:55
Another ticket: https://dotcms.zendesk.com/agent/tickets/110282

**Comment by damen-dotcms** [comment] 2023-06-16 20:59
Nice! I saw this as an issue on our site while doing a crawl. (=

Yeah Google doesn't care if you have a / or not at the end of a URL. So we should just ignore that. 

Doesn't matter if you have a / or not in the canonical URL either -- except to say that sometimes you have to write another bit of regex to get the crawls to line up if you have different canonical URLs -- so ideally we would just load the same consistent / or no / for canonical URLs between the pages. 

We don't really need to 301 one to the other... Google views them both as the same URL. And... since it views the URL as the same, adding a 301 redirect can muddy things (A 301 from one identical page to the other can inflate the "hops" if we have any other redirects present. So I think ideally they would both just load as a 200... But let me know when this is released on our demo site and I'll run some further scans to verify. @nollymar 

I just closed #25264 as a dupe of this.

**Comment by damen-dotcms** [comment] 2023-06-16 21:07
Yeah OK, so doing another test...

It's really not good to 404 on the / since if we have any links that have a / that Google finds... it'll record the 404 as being on the page -- it doesn't care if there is a / or no slash, it sees the URLs as identical.

https://demo.dotcms.com/store/products/k2-mens-mindbender-99ti-skis
https://demo.dotcms.com/store/products/k2-mens-mindbender-99ti-skis/

But also, 301 from / to no slash seems OK... as long as there are no other 301s ahead in the "chain" and as long as the final version of the page shows a 200.

But yeah, I think ideally... both should just give a 200. No redirect needed. As long as the Canonical URLs are identical (but again, that's just to be kind to people doing crawls so they don't have to write any regex to sort out the different URLs).

**Comment by nollymar** [comment] 2023-06-30 15:11
@damen-dotcms both urls give a 200 code, but this change is not yet released. It will be for the next release.

**Internal QA:** passed

Tested on master.

**Comment by josemejias11** [comment] 2023-07-03 18:14
**Approved QA** - Tested on **master_b295876_SNAPSHOT** // Docker // macOS 13.0 // FF v113.0

https://localhost:8443/store/products/atomic-hawx-ultra-130-s-ski-boots/

**Closed** 2023-08-01 23:26 UTC
Labels: Type : Defect, QA : Approved, Merged, QA : Passed Internal, Team : Scout, Next LTS Release, OKR : Customer Success, Priority : 2 High, OKR : Customer Support, Next Release, Release : 23.07, Release : 22.03.8
