### ISSUE TITLE
New Code Editor Modal in dotCMS Version 24

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#29156] opened 2024-07-08 13:18 UTC
### Problem Statement

Lack of Syntax Highlighting:
The absence of syntax highlighting for Velocity/JavaScript code is significantly hindering our workflow. Syntax highlighting is essential for code readability and debugging.

Editor Height:
The height of the code editor is significantly smaller compared to previous versions, making it difficult to read and navigate through the code. This reduction in size affects the overall user experience.

### Steps to Reproduce

![image](https://github.com/dotCMS/core/assets/139247809/007c5c45-05ed-4c53-9735-e6b976ef5bc0)

### Acceptance Criteria

Enable syntax highlighting for Velocity/JavaScript.
Adjust the height of the code editor.

### dotCMS Version

24.04

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/C01N0AU1NUC/p1719928037764969
https://dotcms.zendesk.com/agent/tickets/116997

**Comment by erickgonzalez** [comment] 2024-07-08 15:06
this is a dupe of https://github.com/dotCMS/core/issues/28084

**Closed by erickgonzalez** 2024-07-08 15:06 UTC
Labels: Type : Defect, Triage
