### ISSUE TITLE
Content Selection Screen trying to toggle selectbox

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#17396] opened 2019-09-29 23:17 UTC
If you are in edit mode and go to add a piece of content to a page and instead of hitting the button, you hit the content title (still the hit area) - we get a j/s console error saying that 
`toggleCheckbox is not defined`.  While it doesn't happen all the time, I have seen this break the page and no content can be selected.

![content-selector-looking-for-checkbox](https://user-images.githubusercontent.com/934364/65841177-bdbe4280-e2ed-11e9-8ec1-4fcd7f557be9.gif)

**Comment by fmontes** [comment] 2019-09-30 16:10
Closed in favor: https://github.com/dotCMS/core/issues/17328

**Comment by bryanboza** [comment] 2019-10-01 02:42
Fixed, unable to reproduce after the last changes

**Closed** 2019-10-01 12:50 UTC
Labels: Passed Internal QA, Passed QA, Release : 5.2.0, Type : Bug
