### ISSUE TITLE
Edit mode problem publishing changes 

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#16219] opened 2019-03-13 03:29 UTC
We have a problem in the edit mode when you try to publish the page, and change the tab without the system automatically refresh. 

We are showing an error "the page does not exist" and the page is disappearing from site browser. You need to flush the cache to see the page again. 
SC: https://screencast.com/t/g4meP1OS7
Log: https://gist.github.com/bryanboza/842a0c0155c32619d24f4a9ed3750119

## Expected Behavior
We need to show a loading gift or something like that, but not disappear completely the page 

## Current Behavior
We show an error that the page does not exist, and you are unable to see the page in the site browser, until flush the cache 

## Your Environment
Tested on master // Postgres // FF

**Comment by jgambarios** [comment] 2019-03-19 18:00
Unable to reproduce, fixed with: https://github.com/dotCMS/core/pull/16243

**Comment by bryanboza** [comment] 2019-03-19 18:57
Fixed, unable to reproduce after the last changes

**Closed** 2019-03-19 20:01 UTC
Labels: Cat : UI, Passed Internal QA, Release : 5.1.1, Type : Bug, WF : Passed QA
