### ISSUE TITLE
Field variables form breaks with long texts

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23119] opened 2022-10-06 20:40 UTC
### Describe the bug
As a user, I need to be able to type and edit anything in the field variable form. Right now, long text or comma separated text are breaking the UI.

### To Reproduce
1. Edit a field
2. Go to field variables
3. Add a paragraph or multiples comma separated strings

### Expected behavior
~~It should **multiline** and prevent the key to shrink.~~
acceptance criteria below

### Screenshots
<img width="597" alt="Screen Shot 2022-10-06 at 14 31 28" src="https://user-images.githubusercontent.com/751424/194413950-7eaa2c85-9cd7-4ffc-8a11-d6ce6c64aed8.png">

<img width="597" alt="Screen Shot 2022-10-06 at 14 29 56" src="https://user-images.githubusercontent.com/751424/194413959-7449266f-d1b8-411a-8426-e973e93932de.png">

### Acceptance criteria
- User should be able to have long text, paragraphs and comma separated strings
- when adding long text on a keyVariable, the columns should not change their width and the value should show and grow vertically
![image.png](https://images.zenhubusercontent.com/5aa153f34b5806bc2bca024d/48a64bbb-4251-46ea-adc4-da9e4f9db85e)

**Comment by fabrizzio-dotCMS** [comment] 2022-12-02 16:55
UI still breaks upon entering long keys see the screenshot below

![Screen Shot 2022-12-02 at 10 53 35](https://user-images.githubusercontent.com/37148755/205344420-b22e0c37-3c6d-406b-ab64-a65f2cf163ed.png)

**Comment by alfredo-dotcms** [comment] 2022-12-02 22:42
PR: https://github.com/dotCMS/core/pull/23498/files

**Comment by fabrizzio-dotCMS** [comment] 2022-12-06 17:07
![Screen Shot 2022-12-06 at 11 07 05](https://user-images.githubusercontent.com/37148755/205976597-dbea57f3-6826-49b5-b6da-72823b34b12e.png)
Looks good to me.

**Comment by bryanboza** [comment] 2022-12-07 17:13
Now we are ok regarding the `value` but have a db problem when you try to add a long `key` 
![image](https://user-images.githubusercontent.com/2641437/206245718-18f067c3-aecd-4d20-b2b0-337d07b1480d.png)

We need to add a FE validation here instead to show this error

**Comment by josemejias07** [comment] 2022-12-08 16:45
Related to https://github.com/dotCMS/core/issues/23546

**Comment by alfredo-dotcms** [comment] 2022-12-20 19:58
not able to reproduce on `master` and `release-23.01`

![image](https://user-images.githubusercontent.com/37185433/208755305-4411188e-585b-4d34-a09a-c2804753f69d.png)

**Comment by bryanboza** [comment] 2023-01-04 15:29
Fixed, the misaligned issue was fixes and now we are unable to reproduce, let's move the validation issue to a new card and continue working on this one. 

Tested on release-23.01 // Docker // FF

**Comment by damen-dotcms** [comment] 2023-01-11 15:09
Let's close this issue, if there are other problems we can open new issues to track them.

**Closed by damen-dotcms** 2023-01-11 15:09 UTC
Labels: Type : Defect, Passed QA, Needs Work, Merged, dotCMS : User Interface, WF: Can't reproduce, Passed Internal QA, Team : Scout, Release : 23.01
