### ISSUE TITLE
Image field variable in showFields for relationship should show image

### ISSUE THREAD

**Issue by waqasakramdot** [dotCMS/core#26418] opened 2023-10-11 13:42 UTC
### Problem Statement

If a relationship has **showFields** as a key and its value has any image field like (image, title) I will only show the title and can't show an image. Please note if image field is binary then it will not show however if the image field is **Image** then it will show against **showFields**. Moreover, if the image field is image/binary and its variable is something else than _image_ like **bioimage** then it will not show up in any case.

https://github.com/dotCMS/core/assets/102758033/1cc26f05-f04c-4190-ac1d-a1a0d5736b2a

### Steps to Reproduce

Create a Content type (Activity) with an image field like title and image.
Create a few contentlets for it.

Create another content type with relationship to previously created content type (Activity)
Add Field variable to relationship. As key use showFields and as a values use image,title
After that create a content let for it and for the relationship field select an Activity
You will see Activity will only show title not the image.

### Acceptance Criteria

The relationship field should show the image as a field

### dotCMS Version

23.01.7 - 23.09.7 (demo)

### Proposed Objective

Customer Support

### Proposed Priority

Priority 4 - Trivial

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/113447

**Comment by erickgonzalez** [comment] 2023-10-11 14:24
dupe of https://github.com/dotCMS/core/issues/25411

**Closed by erickgonzalez** 2023-10-11 14:24 UTC
Labels: Type : Defect, Triage
