### ISSUE TITLE
No padding for buttons in the tab header

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7007] opened 2015-01-16 19:23 UTC
This is in at least two places.  Something changed that caused them to lose their padding.

![screen shot 2015-01-16 at 2 21 30 pm](https://cloud.githubusercontent.com/assets/934364/5782666/212112e2-9d8b-11e4-8630-80e2454fb3ea.png)
![screen shot 2015-01-16 at 2 20 42 pm](https://cloud.githubusercontent.com/assets/934364/5782668/2214b320-9d8b-11e4-8547-80b321b6bf17.png)

**Comment by jtesser** [comment] 2015-01-21 16:42
closing as a duplicate of #6906 as we will be fixing there

**Closed by jtesser** 2015-01-21 16:42 UTC
Labels: Cat : UI, Severity : Minor, Type : bug
