### ISSUE TITLE
[core] Copying a site fails when a file asset uses the same name as a file in other language

### ISSUE THREAD

**Issue by dsolistorres** [dotCMS/core#15535] opened 2018-11-10 23:53 UTC
Reported via support ticket: [96891](https://dotcms.zendesk.com/agent/tickets/96891)
Reproducible in dotCMS 4.2.2, 5.0.3

Copying a site fails when there is a multi language file asset renamed only for one language (the other languages keep the original file name) and there is a new file asset that uses the same original name as the renamed one.

## Expected Behavior
When copying a site to a new one, all file assets should be copied to the new one, even if one of the multi language files was renamed for one language. For other languages, the file variants that weren't renamed should be copied too. 

## Current Behavior
When copying an existing site to create a new one, an error occurs because one multi language file asset was renamed only for a language, and a new one was uploaded using the original file name. The copying doesn't complete, and there are missing files in the new created site.

## Possible Solution
One possible solution is to use the name of the renamed file for the variants of the file in other languages.
Also, the logic can be fixed so all the language variants keep their names. That requires some change in the copyContentlet or checkin method from the com.dotcms.content.elasticsearch.business.ESContentletAPIImpl so the different variants don't try to use the original filename for the asset_name field of the identifier. 

## Known Workarounds
Don't use the same filename for new asset files, when the filename is still used for variants of the original file in other languages. Rename all the multi language variants and then upload the new asset.

## Steps to Reproduce (for bugs)
1. Log into dotCMS 5.0.3
2. Create a new blank site, with a folder for file assets.
3. Upload a new file asset for English language (for example "logo.png")
4. Create a version of the file asset for Spanish language.
5. Rename only the English version (for example to "new-logo.png"). The Spanish version keeps the original name ("logo.png").
6. Upload a new file asset for English language using the original name ("logo.png").
7.  Make sure the newer file asset is returned first in Content Search above the renamed file asset.
<img width="866" alt="renamed-file-asset" src="https://user-images.githubusercontent.com/2894221/48305554-77ec6600-e4f2-11e8-8474-de052499d720.png">
8. Create a new site based in the first one: In "What to copy" options choose Folders and Content on Site.
9. Go to the new site. There are missing files.

Error message is logs is shown below:
```
[10/11/18 14:45:29:033 CST] ERROR priv.HostAssetsJobImpl: Error ocurred on copy of content on host, the process will continue
com.dotmarketing.exception.DotDataException: ERROR: current transaction is aborted, commands ignored until end of transaction block{
  "SQL": ["SELECT inode FROM contentlet c INNER JOIN contentlet_version_info cvi ON (c.inode = cvi.working_inode OR c.inode = cvi.live_inode) WHERE c.identifier=? order by c.mod_date desc "],
  "maxRows": [-1],
  "offest": [0],
  "params": "22d911e9-be56-4d07-beb4-0e46a12b9a9a"
}
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:256) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect.loadObjectResults(DotConnect.java:907) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentFactoryImpl.findAllVersions(ESContentFactoryImpl.java:835) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findAllVersions_aroundBody128(ESContentletAPIImpl.java:3832) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure129.run(ESContentletAPIImpl.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.findAllVersions(ESContentletAPIImpl.java:3831) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.copyContentlet_aroundBody156(ESContentletAPIImpl.java:5183) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure157.run(ESContentletAPIImpl.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.copyContentlet(ESContentletAPIImpl.java:5176) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.copyContentlet_aroundBody162(ESContentletAPIImpl.java:5448) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure163.run(ESContentletAPIImpl.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.copyContentlet(ESContentletAPIImpl.java:5447) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.portlets.contentlet.business.ContentletAPIInterceptor.copyContentlet(ContentletAPIInterceptor.java:1902) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.enterprise.priv.HostAssetsJobImpl.processCopyOfContentlet(HostAssetsJobImpl.java:511) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.priv.HostAssetsJobImpl.copyHostAssets(HostAssetsJobImpl.java:372) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.priv.HostAssetsJobImpl.run(HostAssetsJobImpl.java:112) ~[ee_clean.jar:?]
	at com.dotcms.enterprise.HostAssetsJobProxy.run(HostAssetsJobProxy.java:17) ~[ee_clean.jar:?]
	at com.dotmarketing.quartz.DotJob.execute(DotJob.java:42) ~[dotcms_5.0.0_999999.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:223) ~[dot.quartz-all-1.8.6_2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549) ~[dot.quartz-all-1.8.6_2.jar:?]
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118) ~[postgresql-42.2.2.jar:42.2.2]
	at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc.jar:?]
	at com.sun.proxy.$Proxy75.executeQuery(Unknown Source) ~[?:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:622) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:524) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:254) ~[dotcms_5.0.0_999999.jar:?]
	... 33 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "identifier_parent_path_asset_name_host_inode_key"
  Detail: Key (parent_path, asset_name, host_inode)=(/training/, logo.png, 1bcbfbfd-6c3d-43a8-8956-e56c24e65fd0) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144) ~[postgresql-42.2.2.jar:42.2.2]
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc.jar:?]
	at com.sun.proxy.$Proxy75.execute(Unknown Source) ~[?:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:612) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect.executeQuery(DotConnect.java:524) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.common.db.DotConnect.loadResult(DotConnect.java:254) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierFactoryImpl.saveIdentifier(IdentifierFactoryImpl.java:455) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierFactoryImpl.createNewIdentifier(IdentifierFactoryImpl.java:325) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierFactoryImpl.createNewIdentifier(IdentifierFactoryImpl.java:268) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl.createNew_aroundBody18(IdentifierAPIImpl.java:152) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl$AjcClosure19.run(IdentifierAPIImpl.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl.createNew(IdentifierAPIImpl.java:145) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.business.IdentifierAPIImpl.createNew(IdentifierAPIImpl.java:141) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody118(ESContentletAPIImpl.java:3059) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure119.run(ESContentletAPIImpl.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:40) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2781) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin_aroundBody114(ESContentletAPIImpl.java:2743) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl$AjcClosure115.run(ESContentletAPIImpl.java:1) ~[dotcms_5.0.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.CloseDBIfOpenedMethodInterceptor.invoke(CloseDBIfOpenedMethodInterceptor.java:29) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.CloseDBIfOpenedAspect.invoke(CloseDBIfOpenedAspect.java:41) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2736) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.checkin(ESContentletAPIImpl.java:2718) ~[dotcms_5.0.0_999999.jar:?]
	at com.dotcms.content.elasticsearch.business.ESContentletAPIImpl.copyContentlet_aroundBody156(ESContentletAPIImpl.java:5307) ~[dotcms_5.0.0_999999.jar:?]
	... 23 more
```

Data from the identifier and contentlet tables:
```
dotcms=> select id,parent_path,asset_name,host_inode from identifier where host_inode='83e6f56f-2a60-4cd6-b3d9-1a66be98ecee' and asset_type='contentlet';
                  id                  | parent_path |  asset_name  |              host_inode
--------------------------------------+-------------+--------------+--------------------------------------
 f1b9c9b2-370f-4bb4-b485-e60007f633f5 | /training/  | logo.png     | 83e6f56f-2a60-4cd6-b3d9-1a66be98ecee
 22d911e9-be56-4d07-beb4-0e46a12b9a9a | /training/  | new-logo.png | 83e6f56f-2a60-4cd6-b3d9-1a66be98ecee

dotcms=> select inode,identifier,language_id,text3 from contentlet where identifier in ('22d911e9-be56-4d07-beb4-0e46a12b9a9a','f1b9c9b2-370f-4bb4-b485-e60007f633f5');
                inode                 |              identifier              | language_id |    text3
--------------------------------------+--------------------------------------+-------------+--------------
 f91dbf60-504d-4c6a-9d01-3dcd45ab2ae2 | 22d911e9-be56-4d07-beb4-0e46a12b9a9a |           1 | new-logo.png
 800ec1e6-8635-46f9-a1d6-b0fe8981c9f1 | 22d911e9-be56-4d07-beb4-0e46a12b9a9a |           2 | logo.png
 757a1944-2bf5-4552-bd3a-60f533e0e85b | f1b9c9b2-370f-4bb4-b485-e60007f633f5 |           1 | logo.png
```

## Context
This bug prevents a site for being copied to a new one, since all not files are copied to the new one.
This was reported by client in this support issue: [96891](https://dotcms.zendesk.com/agent/tickets/96891)

## Your Environment
* dotCMS version used: 4.2.2 and 5.0.2
* Browser Name and version: Not relevant
* Operating System and version: Not relevant
* Application Server and version: Not relevant
* Java Brand and version: Not relevant
* Database and version: Not relevant
* Application module (if apply): Site browser (creating and renaming file assets)

## Related Issues
The issue #15534 also happens in the same scenario: one renamed file asset for one language, while variants in other languages keep the original name, then a new asset uploaded using the original name.
If the issue #15534 is fixed, this issue should be fixed at the same time.

**Comment by jgambarios** [comment] 2019-01-31 19:45
Fixed in https://github.com/dotCMS/core/issues/15800

**Comment by jgambarios** [comment] 2019-02-19 18:21
We are still able to reproduce this issue, marking it as `Needs Work`.

**Comment by jgambarios** [comment] 2019-02-21 16:21
PR: https://github.com/dotCMS/core/pull/16083

**Comment by bryanboza** [comment] 2019-03-01 21:18
Unable to reproduce on master... I'll pass QA

**Closed** 2019-03-04 20:13 UTC
Labels: Cat : Content Management, Passed Internal QA, Release : 5.1.0, Severity : Support Requested, Type : Bug, WF : Merged, WF : Passed QA
