### ISSUE TITLE
Containers/Folders not allowing accents

### ISSUE THREAD

**Issue by erickgonzalez** [dotCMS/core#26375] opened 2023-10-05 18:20 UTC
### Problem Statement

When using accents in containers/folders they're encoded wrong.

### Steps to Reproduce

1- Create a container with the title: `test üçà`
2- Save and Publish
3- See that it encodes it wrongly.

### Acceptance Criteria

Should encode accents the right way.

### dotCMS Version

23.01+

### Proposed Objective

Customer Support

### Proposed Priority

Please Select

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/113581

**Comment by dsolistorres** [comment] 2024-08-28 00:00
Unable to reproduce in latest master for container names.
For folder names, it should be solved by #29392

**Comment by bryanboza** [comment] 2024-08-28 16:20
Fixed, I'm unable to reproduce on the latest trunk // Docker. 

It is working as expected, so we can close this one for now.

**Closed** 2024-10-08 16:28 UTC
Labels: Type : Defect, QA : Approved, Triage, OKR : Customer Success, OKR : Customer Support, Team : Bug Fixers, Release : 24.09.21
