### ISSUE TITLE
"Permission Individually" on a folder defaults to all permissions of its parent, not just the inheritable ones

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#19412] opened 2020-10-07 17:02 UTC
Reported via Support: [102509](https://dotcms.zendesk.com/agent/tickets/102509), and [102535](https://dotcms.zendesk.com/agent/tickets/102535)
Reproducible in dotCMS 5.3.4, 5.3.8.

Some folders are having problems showing their contents in the **Site Browser** intermittently. When checking their permissions, the portlet is not showing the actual list, only a handful of them. For example, before clicking the `PERMISSION INDIVIDUALLY` button, you see this:

<img width="1182" alt="perms-before" src="https://user-images.githubusercontent.com/8779585/95358500-5d5dcb80-0886-11eb-8b8c-7d50caee6aec.png">

Only 3 roles are displayed. But, after clicking it, you get the full list of roles and their respective permissions:

<img width="1184" alt="perms-after" src="https://user-images.githubusercontent.com/8779585/95358528-6484d980-0886-11eb-9fd9-db2b32ce3a53.png">

The only workaround for the customer is to flush all caches constantly. We're not 100% sure, but it seems like having a considerable number of role permissions for a folder might be causing this behavior.

**To Reproduce**
The Support Team has access to a test instance where this can be further tested. Please ask Jose Castro for the details.

**Expected behavior**
Permissions must be consistent and cached correctly in order to keep folders from not showing their contents.

**Additional context**
A similar problem is being reproduced in the internal dotCMS Authoring instance.

**Comment by john-thomas-dotcms** [comment] 2020-10-08 15:20
So there are 2 issues here, both of which I've seen on our own authoring server.

1. The permissions show incorrectly, until you click the "Permission Individually" button.
    * This issue is 100% reproducible for me on multiple files and folders on our authoring site.
    * This issue is not fixed by a cache clear.
2. Sometimes the contents of a folder don't show at all.
    * This issue is intermittent - I've only seen it twice on our authoring server, but the customer sees it regularly (every few days with one folder).
    * Clearing All Caches fixes this problem (both on our site and the customer site).

Before the "Permission Individually" button is pressed:

![image](https://user-images.githubusercontent.com/13456955/95363940-00ade100-0885-11eb-8af0-931acb4f816b.png)

After the folder is permissioned individually:

![image](https://user-images.githubusercontent.com/13456955/95364019-220ecd00-0885-11eb-8e8d-dc58efa8d90e.png)

**Comment by jcastro-dotcms** [comment] 2020-10-12 17:17
In a test environment, when clicking the `PERMISSION INDIVIDUALLY` button, dotCMS is also showing a modal saying that the system is saving the permissions. AFAIK, such a button should just enable the user to select individual permissions on the object, and should not trigger any data saving process.

**Comment by wezell** [comment] 2020-10-21 19:04
One reproducible case was fixed in this issue #18901 and released in 5.3.4.1

**Comment by fabrizzio-dotCMS** [comment] 2021-04-12 21:56
While I was trying to get a lock on a test data set to be able to reproduce the issue  
I discovered that.. in all the cases listed above the additional roles that make it into the list roles (Once the Permission Individually button is pressed) are in fact, individual permissions that live under the parent permissionable.
which are copied as individual permissions because they originally existed on the parent permissionable as individual permissions too. 

Here's an example:

This is the folder **codeshare** from authoring showing originally only 3 roles.

![code-share-Perms](https://user-images.githubusercontent.com/37148755/114460094-901eae80-9b9e-11eb-9148-a3b6a77598ea.png)

After hitting "Permission Individually" There 3 additional roles that were not listed initially.
**Note those are Individual permissions.**

![Job-Publisher-Individual-Perm](https://user-images.githubusercontent.com/37148755/114460209-b9d7d580-9b9e-11eb-85c6-5c553a60c539.png)
 
Actually those permissions are coming from the site the folder is inheriting their permissions from.

![Individual-Perms](https://user-images.githubusercontent.com/37148755/114466646-fd820d80-9ba5-11eb-9f22-bae62325e9f0.png)

In other words those permissions make it into the Individual permissions screen  because they were added to be so under the host screen. 
If we were to change the scope of those permissions and make them Inheritable perms from the Host Permissions screen they would make it into the list of  original permissions listed.

**In conclusion.** I think it behaves like that by desig. The individual perissions (included from the Host) are included because we are setting "Permissions individually". Therefore all indivual permissions from the permissionable-root are included. 
**Possible Solutions**

1. Maybe that's a bit confussing and those individual perms (included in the host) should be shown on the original list of perms. 

2. Or maybe we should show next to each permission where they're coming from. It would make permissions way more intuitive and a lot easier to follow. 

I dont think Individual permissions set on the permissionable root should be removed from the individual permissions screen level.

**Comment by fabrizzio-dotCMS** [comment] 2021-04-20 18:00
Note for QA: There's a new PR out there that solves this issue https://github.com/dotCMS/core/pull/20264
However, I've seen a Workflows test failing intermittently since I introduced this fix.  
Therefore I need to verify that.. given a user without access to a CT and no valid license installed we try to see the default available actions via ` @Path("/initialactions/contenttype/{contentTypeId}")`

**Comment by fabrizzio-dotCMS** [comment] 2021-04-21 22:39
Note provided by @wezell 

This is data from a fresh starter:

All Permissions on the SYSTEM_HOST - the system host 
dotcms=# select * from permission where inode_id ='SYSTEM_HOST';
  id   |                     permission_type                     |  inode_id   |                roleid                | permission
-------+---------------------------------------------------------+-------------+--------------------------------------+------------
 11716 | com.dotmarketing.beans.Host                             | SYSTEM_HOST | CMS Anonymous                        |          1  <-----
 11717 | com.dotmarketing.portlets.folders.model.Folder          | SYSTEM_HOST | CMS Anonymous                        |          1
 11718 | com.dotmarketing.portlets.files.model.File              | SYSTEM_HOST | CMS Anonymous                        |          1
 11719 | com.dotmarketing.portlets.links.model.Link              | SYSTEM_HOST | CMS Anonymous                        |          1
 11720 | com.dotmarketing.portlets.contentlet.model.Contentlet   | SYSTEM_HOST | CMS Anonymous                        |          1
 11721 | com.dotmarketing.portlets.htmlpageasset.model.IHTMLPage | SYSTEM_HOST | CMS Anonymous                        |          1
 11722 | com.dotmarketing.portlets.structure.model.Structure     | SYSTEM_HOST | CMS Anonymous                        |          1                         
 11727 | com.dotmarketing.portlets.categories.model.Category     | SYSTEM_HOST | CMS Anonymous                        |          1
 11778 | com.dotmarketing.portlets.htmlpageasset.model.IHTMLPage | SYSTEM_HOST | Campaign Manager Viewer              |         31
 12517 | com.dotmarketing.beans.Host                             | SYSTEM_HOST | John Editor                          |          1  <-----
 12518 | com.dotmarketing.portlets.folders.model.Folder          | SYSTEM_HOST | John Editor                          |          1
 12519 | com.dotmarketing.portlets.contentlet.model.Contentlet   | SYSTEM_HOST | John Editor                          |          1
(12 rows)

These are the two permissions/roles that have inheritable permissions for HOSTS on the SYSTEM_HOST.  
When you reset permissions on demo.dotcms.com, the SYSTEM_HOST inheritables are the two permissions you see.  All good. 

dotcms=# select * from permission where inode_id ='SYSTEM_HOST' and permission_type='com.dotmarketing.beans.Host';  
  id   |       permission_type       |  inode_id   |                roleid                | permission
-------+-----------------------------+-------------+--------------------------------------+------------
 11716 | com.dotmarketing.beans.Host | SYSTEM_HOST | CMS Anonymous                        |          1
 12517 | com.dotmarketing.beans.Host | SYSTEM_HOST | John Editor                          |          1
(2 rows)

When you hit "permission individually", what happens is that ALL permissions are copied from SYSTEM_HOST to the child.  This should not happen.  
What should happen is that we should copy only the permissions for the roles that have the inheritable permission_type='com.dotmarketing.beans.Host'.
Because 1. we want to mirror the Host permissions from SYSTEM_HOST  and 2. the "Campaign Manager Viewer" does not have any Host permissions, 
that permission should be excluded from the copy

dotcms=# select * from permission where inode_id ='' and permission_type='com.dotmarketing.beans.Host';
  id   |                     permission_type                     |               inode_id      |                roleid                | permission
-------+---------------------------------------------------------+-----------------------------+--------------------------------------+------------
 12715 | individual                                              | demo.dotcms.com             | CMS Anonymous                        |          1
 12716 | com.dotmarketing.beans.Host                             | demo.dotcms.com             | CMS Anonymous                        |          1
 12717 | com.dotmarketing.portlets.folders.model.Folder          | demo.dotcms.com             | CMS Anonymous                        |          1
 12718 | com.dotmarketing.portlets.files.model.File              | demo.dotcms.com             | CMS Anonymous                        |          1
 12719 | com.dotmarketing.portlets.links.model.Link              | demo.dotcms.com             | CMS Anonymous                        |          1
 12720 | com.dotmarketing.portlets.contentlet.model.Contentlet   | demo.dotcms.com             | CMS Anonymous                        |          1
 12721 | com.dotmarketing.portlets.htmlpageasset.model.IHTMLPage | demo.dotcms.com             | CMS Anonymous                        |          1
 12722 | com.dotmarketing.portlets.structure.model.Structure     | demo.dotcms.com             | CMS Anonymous                        |          1
 12723 | com.dotmarketing.portlets.htmlpageasset.model.IHTMLPage | demo.dotcms.com             | Campaign Manager Viewer              |         31  <---- this should be excluded because the "Campaign Manager Viewer" does not have any host perm
 12725 | com.dotmarketing.beans.Host                             | demo.dotcms.com             | John Editor                          |          1
 12726 | com.dotmarketing.portlets.folders.model.Folder          | demo.dotcms.com             | John Editor                          |          1
 12727 | com.dotmarketing.portlets.contentlet.model.Contentlet   | demo.dotcms.com             | John Editor                          |          1
(12 rows)

dotcms=# select * from permission where inode_id ='48190c8c-42c4-46af-8d1a-0cd5db894797' and permission_type='com.dotmarketing.beans.Host';
  id   |       permission_type       |               inode_id               |                roleid                | permission
-------+-----------------------------+--------------------------------------+--------------------------------------+------------
 12716 | com.dotmarketing.beans.Host | demo.dotcms.com                      | CMS Anonymous                        |          1
 12725 | com.dotmarketing.beans.Host | demo.dotcms.com                      | John Editor                          |          1
(2 rows)

**Comment by fabrizzio-dotCMS** [comment] 2021-05-07 21:47
**Note for QA:** The easiest way to verify this has been fixed Is... Getting a non-empty starter  and make sure that the same list of roles displayed for a Folder or Site is the same list of roles displayed after you hit  "Permission Individually"
Since that's exactly what we are trying to fix. 

You can use demo as a good point of comparison. See for example we get an initial list  of roles/user when we view the permissions of a folder like "activities"

We get 

- Campaign Manager Viewer 
- CMS Anonymous 
- John Editor 

**Once We hit  "Permission Individually" The expected is to have the exact same list of Roles/Users we initially had.**

But instead, we get an additional list of extra roles:
We also get

- Contributor
- Movie Publisher

These additional roles are getting here because somehow they are part of the roles of the parent. 
But they shouldn't make it here. Because they lack the respective permission type. Meaning they are part of the parent and they have any permission type but the one we care about right now (Folder) Therefore they should be excluded. 

One good example is this: https://github.com/dotCMS/core/issues/19412#issuecomment-818269067
Individual permissions on the parent should make it into the children. 

Always verify where the object is getting their permission from 
![Screen Shot 2021-05-07 at 15 31 03](https://user-images.githubusercontent.com/37148755/117510400-3d3fd900-af49-11eb-9adb-0e4c8e03bcf4.png)

Additionally.. if you're seeing roles/users here that are not in the parent permissionable they might be "finding their way here" through the role permissions. So check that out too. 

e.g. if the Role Movie Publisher should only appear in the list of permissions if it has a Permission of type "Folder" if we're looking at a folder or a Permission of type "Site" if we're looking at a site.

Ping me with whatever questions you might have.

**Comment by nollymar** [comment] 2021-05-14 16:19
**Passed internal QA:** Working as expected

**Comment by bryanboza** [comment] 2021-05-19 20:20
Fixed, tested on release-21.05 // Postgres // FF

**Closed** 2021-05-25 19:13 UTC
Labels: Cat : Content Management, Cat : Permissions, Cat : Useability, Changelog: Documented, Merged, Note to QA, Passed Internal QA, Passed QA, Release : 21.05, Release : 5.2.8.5, Release : 5.3.8.5, Severity : Support Requested, Type : Bug
